# This Makefile is a sample file, do not use in product.

AS		= $(CROSS_COMPILE)as
LD		= $(CROSS_COMPILE)ld
CC		= $(CROSS_COMPILE)gcc
CPP		= $(CC) -E
AR		= $(CROSS_COMPILE)ar
NM		= $(CROSS_COMPILE)nm

STRIP		= $(CROSS_COMPILE)strip
OBJCOPY		= $(CROSS_COMPILE)objcopy
OBJDUMP		= $(CROSS_COMPILE)objdump

TOPDIR := $(shell pwd)

ROOT_DIR ?= $(TOPDIR)/../../../../..

REAL_TIME_DIR := $(ROOT_DIR)/src/real_time
BAREMETAL_SAMPLES_DIR := $(ROOT_DIR)/src/samples/real_time/baremetal
BAREMETAL_DIR := $(REAL_TIME_DIR)/baremetal
DRIVERS_DIR := $(REAL_TIME_DIR)/drivers
OUTPUT_DIR := $(ROOT_DIR)/build/build_baremetal/output

CFLAGS   := -fno-builtin -ffreestanding \
	-I$(BAREMETAL_DIR)/include \
	-I$(DRIVERS_DIR)/include \
	-I$(BAREMETAL_SAMPLES_DIR)/common \
	-I$(SECUREC_PATH)/include \
	-Werror -O2 \
	-fno-pic -ffunction-sections \
	-fdata-sections -fno-common \
	-fno-common -pipe -march=armv8-a \
	-Wall -Wstrict-prototypes -fstack-protector-strong \
	$(MKFLAGS) -fno-strict-aliasing

CFLAGS += -Wextra -Wdate-time -Wmissing-declarations -Wmissing-prototypes\
	-Wfloat-equal -Wformat=2  -Wswitch-default -Wtrampolines -Winit-self \
	-Wundef -Wimplicit-fallthrough=2 -Wshadow

CFLAGS += -D__BAREMETAL__

ASFLAGS := $(CFLAGS)

LDFLAGS := --gc-sections

TARGET_LDS := $(BAREMETAL_SAMPLES_DIR)/common/hi309x.lds

ifneq ($(wildcard $(REAL_TIME_DIR)/lib/libm.a),)
EXTEND_INCLUDE += $(REAL_TIME_DIR)/lib/libm.a
else
$(error "can not find libm.a $(REAL_TIME_DIR)/lib/libm.a")
endif

ifneq ($(wildcard $(REAL_TIME_DIR)/lib/libc.a),)
EXTEND_INCLUDE += $(REAL_TIME_DIR)/lib/libc.a
else
$(error "can not find libc.a")
endif

ifneq ($(wildcard $(REAL_TIME_DIR)/lib/libsecurec.a),)
EXTEND_INCLUDE += $(REAL_TIME_DIR)/lib/libsecurec.a
else
$(error "can not find libsecurec.a")
endif

ifneq ($(wildcard $(REAL_TIME_DIR)/lib/libbaremetal.a),)
EXTEND_INCLUDE += $(REAL_TIME_DIR)/lib/libbaremetal.a
else
$(error "can not find libbaremetal.a")
endif

SOURCE  := $(wildcard *.c) $(wildcard *.S)
SOURCE  += $(wildcard $(BAREMETAL_SAMPLES_DIR)/common/*.c)
OBJS    := $(patsubst %.c,%.o,$(patsubst %.S,%.o,$(SOURCE)))

export CFLAGS LDFLAGS

TARGET := $(TARGET_NAME)

ifeq ("$(BUILD_SAMPLE_HI309X)", "bm")
include $(BAREMETAL_SAMPLES_DIR)/common/Makefile_baremetal.config
else ifeq ("$(BUILD_SAMPLE_HI309X)", "oe_bm")
include $(BAREMETAL_SAMPLES_DIR)/common/Makefile_2with2.config
else
$(error "can not find matched makefile")
endif

%.o : %.c
	$(CC) $(CFLAGS) -c -o $@ $<

%.o: %.S
	$(CC) -D__ASSEMBLY__ $(CFLAGS) -o $@ $< -c

clean:
	rm -f $(shell find -name "*.o")
	rm -f $(shell find -name "*.elf")
	rm -f $(shell find -name "*.map")
	rm -f $(shell find -name "*.bin")
	rm -f $(shell find -name "*.asm")
	rm -rf $(BAREMETAL_SAMPLES_DIR)/common/*.o
