#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_TARGET_HI309x) := hi309x.o pcie_init.o
obj-$(CONFIG_TARGET_HI309x) += uart.o uart_core.o ddr.o fdt_fix.o atf_boot.o hi309x_pm.o bd_info.o
obj-$(CONFIG_TARGET_HI309x) += dboot.o
