/*
 * Copyright (c) Hisilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 * UniProton is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 * 	http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * See the Mulan PSL v2 for more details.
 */

#ifndef __IO_CONFIG_R_T_ADDR_DEFINE_H__
#define __IO_CONFIG_R_T_ADDR_DEFINE_H__

/**
* @defgroup bm_io_config bm_io_config
*/

#define IO_CONFIG_R_BASE_ADDR 0x876e000

#define IO_CONFIG_R_IOMG000_OFFSET_ADDR 0x0
#define IO_CONFIG_R_IOMG001_OFFSET_ADDR 0x4
#define IO_CONFIG_R_IOMG002_OFFSET_ADDR 0x8
#define IO_CONFIG_R_IOMG003_OFFSET_ADDR 0xC
#define IO_CONFIG_R_IOMG004_OFFSET_ADDR 0x10
#define IO_CONFIG_R_IOMG005_OFFSET_ADDR 0x14
#define IO_CONFIG_R_IOMG006_OFFSET_ADDR 0x18
#define IO_CONFIG_R_IOMG007_OFFSET_ADDR 0x1C
#define IO_CONFIG_R_IOMG008_OFFSET_ADDR 0x20
#define IO_CONFIG_R_IOMG009_OFFSET_ADDR 0x24
#define IO_CONFIG_R_IOMG010_OFFSET_ADDR 0x28
#define IO_CONFIG_R_IOMG011_OFFSET_ADDR 0x2C
#define IO_CONFIG_R_IOMG012_OFFSET_ADDR 0x30
#define IO_CONFIG_R_IOMG013_OFFSET_ADDR 0x34
#define IO_CONFIG_R_IOMG014_OFFSET_ADDR 0x38
#define IO_CONFIG_R_IOMG015_OFFSET_ADDR 0x3C
#define IO_CONFIG_R_IOMG016_OFFSET_ADDR 0x40
#define IO_CONFIG_R_IOMG017_OFFSET_ADDR 0x44
#define IO_CONFIG_R_IOMG018_OFFSET_ADDR 0x48
#define IO_CONFIG_R_IOMG019_OFFSET_ADDR 0x4C
#define IO_CONFIG_R_IOMG020_OFFSET_ADDR 0x50
#define IO_CONFIG_R_IOMG021_OFFSET_ADDR 0x54
#define IO_CONFIG_R_IOMG022_OFFSET_ADDR 0x58
#define IO_CONFIG_R_IOMG023_OFFSET_ADDR 0x5C
#define IO_CONFIG_R_IOMG024_OFFSET_ADDR 0x60
#define IO_CONFIG_R_IOMG025_OFFSET_ADDR 0x64
#define IO_CONFIG_R_IOMG026_OFFSET_ADDR 0x68
#define IO_CONFIG_R_IOMG027_OFFSET_ADDR 0x6C
#define IO_CONFIG_R_IOMG028_OFFSET_ADDR 0x70
#define IO_CONFIG_R_IOMG029_OFFSET_ADDR 0x74
#define IO_CONFIG_R_IOMG030_OFFSET_ADDR 0x78
#define IO_CONFIG_R_IOMG031_OFFSET_ADDR 0x7C
#define IO_CONFIG_R_IOMG032_OFFSET_ADDR 0x80
#define IO_CONFIG_R_IOMG033_OFFSET_ADDR 0x84
#define IO_CONFIG_R_IOMG034_OFFSET_ADDR 0x88
#define IO_CONFIG_R_IOMG035_OFFSET_ADDR 0x8C
#define IO_CONFIG_R_IOMG036_OFFSET_ADDR 0x90
#define IO_CONFIG_R_IOMG037_OFFSET_ADDR 0x94
#define IO_CONFIG_R_IOMG038_OFFSET_ADDR 0x98
#define IO_CONFIG_R_IOMG039_OFFSET_ADDR 0x9C
#define IO_CONFIG_R_IOMG040_OFFSET_ADDR 0xA0
#define IO_CONFIG_R_PADMG000_OFFSET_ADDR 0x800
#define IO_CONFIG_R_PADMG001_OFFSET_ADDR 0x804
#define IO_CONFIG_R_PADMG002_OFFSET_ADDR 0x808
#define IO_CONFIG_R_PADMG003_OFFSET_ADDR 0x80C
#define IO_CONFIG_R_PADMG004_OFFSET_ADDR 0x810
#define IO_CONFIG_R_PADMG005_OFFSET_ADDR 0x814
#define IO_CONFIG_R_PADMG006_OFFSET_ADDR 0x818
#define IO_CONFIG_R_PADMG007_OFFSET_ADDR 0x81C
#define IO_CONFIG_R_PADMG008_OFFSET_ADDR 0x820
#define IO_CONFIG_R_PADMG009_OFFSET_ADDR 0x824
#define IO_CONFIG_R_PADMG010_OFFSET_ADDR 0x828
#define IO_CONFIG_R_PADMG011_OFFSET_ADDR 0x82C
#define IO_CONFIG_R_PADMG012_OFFSET_ADDR 0x830
#define IO_CONFIG_R_PADMG013_OFFSET_ADDR 0x834
#define IO_CONFIG_R_PADMG014_OFFSET_ADDR 0x838
#define IO_CONFIG_R_PADMG015_OFFSET_ADDR 0x83C
#define IO_CONFIG_R_PADMG016_OFFSET_ADDR 0x840
#define IO_CONFIG_R_PADMG017_OFFSET_ADDR 0x844
#define IO_CONFIG_R_PADMG018_OFFSET_ADDR 0x848
#define IO_CONFIG_R_PADMG019_OFFSET_ADDR 0x84C
#define IO_CONFIG_R_PADMG020_OFFSET_ADDR 0x850
#define IO_CONFIG_R_PADMG021_OFFSET_ADDR 0x854
#define IO_CONFIG_R_PADMG022_OFFSET_ADDR 0x858
#define IO_CONFIG_R_PADMG023_OFFSET_ADDR 0x85C
#define IO_CONFIG_R_PADMG024_OFFSET_ADDR 0x860
#define IO_CONFIG_R_PADMG025_OFFSET_ADDR 0x864
#define IO_CONFIG_R_PADMG026_OFFSET_ADDR 0x868
#define IO_CONFIG_R_PADMG027_OFFSET_ADDR 0x86C
#define IO_CONFIG_R_PADMG028_OFFSET_ADDR 0x870
#define IO_CONFIG_R_PADMG029_OFFSET_ADDR 0x874
#define IO_CONFIG_R_PADMG030_OFFSET_ADDR 0x878
#define IO_CONFIG_R_PADMG031_OFFSET_ADDR 0x87C
#define IO_CONFIG_R_PADMG032_OFFSET_ADDR 0x880
#define IO_CONFIG_R_PADMG033_OFFSET_ADDR 0x884
#define IO_CONFIG_R_PADMG034_OFFSET_ADDR 0x888
#define IO_CONFIG_R_PADMG035_OFFSET_ADDR 0x88C
#define IO_CONFIG_R_PADMG036_OFFSET_ADDR 0x890
#define IO_CONFIG_R_PADMG037_OFFSET_ADDR 0x894
#define IO_CONFIG_R_PADMG038_OFFSET_ADDR 0x898
#define IO_CONFIG_R_PADMG039_OFFSET_ADDR 0x89C
#define IO_CONFIG_R_PADMG040_OFFSET_ADDR 0x8A0
#define IO_CONFIG_R_PADMG041_OFFSET_ADDR 0x8A4
#define IO_CONFIG_R_PADMG042_OFFSET_ADDR 0x8A8
#define IO_CONFIG_R_PADMG043_OFFSET_ADDR 0x8AC
#define IO_CONFIG_R_PADMG044_OFFSET_ADDR 0x8B0
#define IO_CONFIG_R_PADMG045_OFFSET_ADDR 0x8B4
#define IO_CONFIG_R_PADMG046_OFFSET_ADDR 0x8B8
#define IO_CONFIG_R_PADMG047_OFFSET_ADDR 0x8BC
#define IO_CONFIG_R_PADMG048_OFFSET_ADDR 0x8C0
#define IO_CONFIG_R_PADMG049_OFFSET_ADDR 0x8C4
#define IO_CONFIG_R_PADMG050_OFFSET_ADDR 0x8C8
#define IO_CONFIG_R_PADMG051_OFFSET_ADDR 0x8CC
#define IO_CONFIG_R_PADMG052_OFFSET_ADDR 0x8D0
#define IO_CONFIG_R_PADMG053_OFFSET_ADDR 0x8D4
#define IO_CONFIG_R_PADMG054_OFFSET_ADDR 0x8D8
#define IO_CONFIG_R_PADMG055_OFFSET_ADDR 0x8DC
#define IO_CONFIG_R_PADMG056_OFFSET_ADDR 0x8E0
#define IO_CONFIG_R_PADMG057_OFFSET_ADDR 0x8E4
#define IO_CONFIG_R_PADMG058_OFFSET_ADDR 0x8E8
#define IO_CONFIG_R_PADMG059_OFFSET_ADDR 0x8EC
#define IO_CONFIG_R_PADMG060_OFFSET_ADDR 0x8F0
#define IO_CONFIG_R_PADMG061_OFFSET_ADDR 0x8F4
#define IO_CONFIG_R_PADMG062_OFFSET_ADDR 0x8F8
#define IO_CONFIG_R_PADMG063_OFFSET_ADDR 0x8FC
#define IO_CONFIG_R_PADMG064_OFFSET_ADDR 0x900
#define IO_CONFIG_R_PADMG065_OFFSET_ADDR 0x904
#define IO_CONFIG_R_PADMG066_OFFSET_ADDR 0x908
#define IO_CONFIG_R_PADMG067_OFFSET_ADDR 0x90C
#define IO_CONFIG_R_PADMG068_OFFSET_ADDR 0x910
#define IO_CONFIG_R_PADMG069_OFFSET_ADDR 0x914
#define IO_CONFIG_R_PADMG070_OFFSET_ADDR 0x918
#define IO_CONFIG_R_PADMG071_OFFSET_ADDR 0x91C
#define IO_CONFIG_R_PADMG072_OFFSET_ADDR 0x920
#define IO_CONFIG_R_PADMG073_OFFSET_ADDR 0x924
#define IO_CONFIG_R_PADMG074_OFFSET_ADDR 0x928
#define IO_CONFIG_R_PADMG075_OFFSET_ADDR 0x92C

#define IO_CONFIG_R_IOMG000_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG000_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG001_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG001_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG002_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG002_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG003_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG003_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG004_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG004_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG005_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG005_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG006_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG006_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG007_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG007_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG008_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG008_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG009_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG009_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG010_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG010_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG011_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG011_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG012_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG012_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG013_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG013_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG014_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG014_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG015_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG015_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG016_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG016_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG017_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG017_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG018_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG018_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG019_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG019_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG020_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG020_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG021_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG021_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG022_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG022_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG023_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG023_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG024_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG024_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG025_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG025_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG026_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG026_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG027_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG027_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG028_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG028_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG029_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG029_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG030_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG030_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG031_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG031_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG032_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG032_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG033_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG033_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG034_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG034_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG035_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG035_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG036_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG036_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG037_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG037_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG038_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG038_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG039_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG039_OFFSET_ADDR)
#define IO_CONFIG_R_IOMG040_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_IOMG040_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG000_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG000_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG001_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG001_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG002_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG002_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG003_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG003_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG004_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG004_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG005_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG005_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG006_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG006_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG007_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG007_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG008_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG008_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG009_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG009_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG010_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG010_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG011_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG011_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG012_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG012_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG013_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG013_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG014_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG014_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG015_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG015_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG016_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG016_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG017_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG017_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG018_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG018_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG019_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG019_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG020_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG020_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG021_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG021_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG022_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG022_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG023_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG023_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG024_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG024_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG025_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG025_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG026_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG026_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG027_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG027_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG028_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG028_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG029_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG029_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG030_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG030_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG031_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG031_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG032_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG032_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG033_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG033_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG034_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG034_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG035_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG035_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG036_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG036_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG037_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG037_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG038_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG038_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG039_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG039_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG040_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG040_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG041_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG041_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG042_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG042_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG043_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG043_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG044_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG044_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG045_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG045_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG046_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG046_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG047_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG047_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG048_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG048_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG049_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG049_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG050_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG050_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG051_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG051_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG052_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG052_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG053_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG053_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG054_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG054_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG055_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG055_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG056_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG056_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG057_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG057_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG058_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG058_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG059_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG059_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG060_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG060_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG061_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG061_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG062_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG062_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG063_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG063_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG064_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG064_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG065_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG065_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG066_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG066_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG067_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG067_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG068_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG068_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG069_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG069_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG070_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG070_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG071_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG071_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG072_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG072_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG073_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG073_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG074_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG074_OFFSET_ADDR)
#define IO_CONFIG_R_PADMG075_ADDR (IO_CONFIG_R_BASE_ADDR + IO_CONFIG_R_PADMG075_OFFSET_ADDR)

#define IO_CONFIG_T_BASE_ADDR 0x8745000

#define IO_CONFIG_T_IOMG000_OFFSET_ADDR 0x0
#define IO_CONFIG_T_IOMG001_OFFSET_ADDR 0x4
#define IO_CONFIG_T_IOMG002_OFFSET_ADDR 0x8
#define IO_CONFIG_T_IOMG003_OFFSET_ADDR 0xC
#define IO_CONFIG_T_IOMG004_OFFSET_ADDR 0x10
#define IO_CONFIG_T_IOMG005_OFFSET_ADDR 0x14
#define IO_CONFIG_T_IOMG006_OFFSET_ADDR 0x18
#define IO_CONFIG_T_IOMG007_OFFSET_ADDR 0x1C
#define IO_CONFIG_T_IOMG008_OFFSET_ADDR 0x20
#define IO_CONFIG_T_IOMG009_OFFSET_ADDR 0x24
#define IO_CONFIG_T_IOMG010_OFFSET_ADDR 0x28
#define IO_CONFIG_T_IOMG011_OFFSET_ADDR 0x2C
#define IO_CONFIG_T_IOMG012_OFFSET_ADDR 0x30
#define IO_CONFIG_T_IOMG013_OFFSET_ADDR 0x34
#define IO_CONFIG_T_IOMG014_OFFSET_ADDR 0x38
#define IO_CONFIG_T_IOMG015_OFFSET_ADDR 0x3C
#define IO_CONFIG_T_IOMG016_OFFSET_ADDR 0x40
#define IO_CONFIG_T_IOMG017_OFFSET_ADDR 0x44
#define IO_CONFIG_T_IOMG018_OFFSET_ADDR 0x48
#define IO_CONFIG_T_IOMG019_OFFSET_ADDR 0x4C
#define IO_CONFIG_T_IOMG020_OFFSET_ADDR 0x50
#define IO_CONFIG_T_IOMG021_OFFSET_ADDR 0x54
#define IO_CONFIG_T_IOMG022_OFFSET_ADDR 0x58
#define IO_CONFIG_T_IOMG023_OFFSET_ADDR 0x5C
#define IO_CONFIG_T_IOMG024_OFFSET_ADDR 0x60
#define IO_CONFIG_T_IOMG025_OFFSET_ADDR 0x64
#define IO_CONFIG_T_IOMG026_OFFSET_ADDR 0x68
#define IO_CONFIG_T_IOMG027_OFFSET_ADDR 0x6C
#define IO_CONFIG_T_IOMG028_OFFSET_ADDR 0x70
#define IO_CONFIG_T_IOMG029_OFFSET_ADDR 0x74
#define IO_CONFIG_T_IOMG030_OFFSET_ADDR 0x78
#define IO_CONFIG_T_IOMG031_OFFSET_ADDR 0x7C
#define IO_CONFIG_T_IOMG032_OFFSET_ADDR 0x80
#define IO_CONFIG_T_IOMG033_OFFSET_ADDR 0x84
#define IO_CONFIG_T_IOMG034_OFFSET_ADDR 0x88
#define IO_CONFIG_T_IOMG035_OFFSET_ADDR 0x8C
#define IO_CONFIG_T_IOMG036_OFFSET_ADDR 0x90
#define IO_CONFIG_T_IOMG037_OFFSET_ADDR 0x94
#define IO_CONFIG_T_IOMG038_OFFSET_ADDR 0x98
#define IO_CONFIG_T_IOMG039_OFFSET_ADDR 0x9C
#define IO_CONFIG_T_IOMG040_OFFSET_ADDR 0xA0
#define IO_CONFIG_T_IOMG041_OFFSET_ADDR 0xA4
#define IO_CONFIG_T_IOMG042_OFFSET_ADDR 0xA8
#define IO_CONFIG_T_IOMG043_OFFSET_ADDR 0xAC
#define IO_CONFIG_T_IOMG044_OFFSET_ADDR 0xB0
#define IO_CONFIG_T_IOMG045_OFFSET_ADDR 0xB4
#define IO_CONFIG_T_IOMG046_OFFSET_ADDR 0xB8
#define IO_CONFIG_T_IOMG047_OFFSET_ADDR 0xBC
#define IO_CONFIG_T_IOMG048_OFFSET_ADDR 0xC0
#define IO_CONFIG_T_IOMG049_OFFSET_ADDR 0xC4
#define IO_CONFIG_T_IOMG050_OFFSET_ADDR 0xC8
#define IO_CONFIG_T_IOMG051_OFFSET_ADDR 0xCC
#define IO_CONFIG_T_PADMG000_OFFSET_ADDR 0x800
#define IO_CONFIG_T_PADMG001_OFFSET_ADDR 0x804
#define IO_CONFIG_T_PADMG002_OFFSET_ADDR 0x808
#define IO_CONFIG_T_PADMG003_OFFSET_ADDR 0x80C
#define IO_CONFIG_T_PADMG004_OFFSET_ADDR 0x810
#define IO_CONFIG_T_PADMG005_OFFSET_ADDR 0x814
#define IO_CONFIG_T_PADMG006_OFFSET_ADDR 0x818
#define IO_CONFIG_T_PADMG007_OFFSET_ADDR 0x81C
#define IO_CONFIG_T_PADMG008_OFFSET_ADDR 0x820
#define IO_CONFIG_T_PADMG009_OFFSET_ADDR 0x824
#define IO_CONFIG_T_PADMG010_OFFSET_ADDR 0x828
#define IO_CONFIG_T_PADMG011_OFFSET_ADDR 0x82C
#define IO_CONFIG_T_PADMG012_OFFSET_ADDR 0x830
#define IO_CONFIG_T_PADMG013_OFFSET_ADDR 0x834
#define IO_CONFIG_T_PADMG014_OFFSET_ADDR 0x838
#define IO_CONFIG_T_PADMG015_OFFSET_ADDR 0x83C
#define IO_CONFIG_T_PADMG016_OFFSET_ADDR 0x840
#define IO_CONFIG_T_PADMG017_OFFSET_ADDR 0x844
#define IO_CONFIG_T_PADMG018_OFFSET_ADDR 0x848
#define IO_CONFIG_T_PADMG019_OFFSET_ADDR 0x84C
#define IO_CONFIG_T_PADMG020_OFFSET_ADDR 0x850
#define IO_CONFIG_T_PADMG021_OFFSET_ADDR 0x854
#define IO_CONFIG_T_PADMG022_OFFSET_ADDR 0x858
#define IO_CONFIG_T_PADMG023_OFFSET_ADDR 0x85C
#define IO_CONFIG_T_PADMG024_OFFSET_ADDR 0x860
#define IO_CONFIG_T_PADMG025_OFFSET_ADDR 0x864
#define IO_CONFIG_T_PADMG026_OFFSET_ADDR 0x868
#define IO_CONFIG_T_PADMG027_OFFSET_ADDR 0x86C
#define IO_CONFIG_T_PADMG028_OFFSET_ADDR 0x870
#define IO_CONFIG_T_PADMG029_OFFSET_ADDR 0x874
#define IO_CONFIG_T_PADMG030_OFFSET_ADDR 0x878
#define IO_CONFIG_T_PADMG031_OFFSET_ADDR 0x87C
#define IO_CONFIG_T_PADMG032_OFFSET_ADDR 0x880
#define IO_CONFIG_T_PADMG033_OFFSET_ADDR 0x884
#define IO_CONFIG_T_PADMG034_OFFSET_ADDR 0x888
#define IO_CONFIG_T_PADMG035_OFFSET_ADDR 0x88C
#define IO_CONFIG_T_PADMG036_OFFSET_ADDR 0x890
#define IO_CONFIG_T_PADMG037_OFFSET_ADDR 0x894
#define IO_CONFIG_T_PADMG038_OFFSET_ADDR 0x898
#define IO_CONFIG_T_PADMG039_OFFSET_ADDR 0x89C
#define IO_CONFIG_T_PADMG040_OFFSET_ADDR 0x8A0
#define IO_CONFIG_T_PADMG041_OFFSET_ADDR 0x8A4
#define IO_CONFIG_T_PADMG042_OFFSET_ADDR 0x8A8
#define IO_CONFIG_T_PADMG043_OFFSET_ADDR 0x8AC
#define IO_CONFIG_T_PADMG044_OFFSET_ADDR 0x8B0
#define IO_CONFIG_T_PADMG045_OFFSET_ADDR 0x8B4
#define IO_CONFIG_T_PADMG046_OFFSET_ADDR 0x8B8
#define IO_CONFIG_T_PADMG047_OFFSET_ADDR 0x8BC
#define IO_CONFIG_T_PADMG048_OFFSET_ADDR 0x8C0
#define IO_CONFIG_T_PADMG049_OFFSET_ADDR 0x8C4
#define IO_CONFIG_T_PADMG050_OFFSET_ADDR 0x8C8
#define IO_CONFIG_T_PADMG051_OFFSET_ADDR 0x8CC
#define IO_CONFIG_T_PADMG052_OFFSET_ADDR 0x8D0
#define IO_CONFIG_T_PADMG053_OFFSET_ADDR 0x8D4
#define IO_CONFIG_T_PADMG054_OFFSET_ADDR 0x8D8
#define IO_CONFIG_T_PADMG055_OFFSET_ADDR 0x8DC
#define IO_CONFIG_T_PADMG056_OFFSET_ADDR 0x8E0
#define IO_CONFIG_T_PADMG057_OFFSET_ADDR 0x8E4
#define IO_CONFIG_T_PADMG058_OFFSET_ADDR 0x8E8
#define IO_CONFIG_T_PADMG059_OFFSET_ADDR 0x8EC
#define IO_CONFIG_T_PADMG060_OFFSET_ADDR 0x8F0
#define IO_CONFIG_T_PADMG061_OFFSET_ADDR 0x8F4
#define IO_CONFIG_T_PADMG062_OFFSET_ADDR 0x8F8
#define IO_CONFIG_T_PADMG063_OFFSET_ADDR 0x8FC
#define IO_CONFIG_T_PADMG064_OFFSET_ADDR 0x900
#define IO_CONFIG_T_PADMG065_OFFSET_ADDR 0x904
#define IO_CONFIG_T_PADMG066_OFFSET_ADDR 0x908
#define IO_CONFIG_T_PADMG067_OFFSET_ADDR 0x90C
#define IO_CONFIG_T_PADMG068_OFFSET_ADDR 0x910
#define IO_CONFIG_T_PADMG069_OFFSET_ADDR 0x914
#define IO_CONFIG_T_PADMG070_OFFSET_ADDR 0x918
#define IO_CONFIG_T_PADMG071_OFFSET_ADDR 0x91C
#define IO_CONFIG_T_PADMG072_OFFSET_ADDR 0x920
#define IO_CONFIG_T_PADMG073_OFFSET_ADDR 0x924
#define IO_CONFIG_T_PADMG074_OFFSET_ADDR 0x928

#define IO_CONFIG_T_IOMG000_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG000_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG001_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG001_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG002_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG002_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG003_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG003_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG004_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG004_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG005_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG005_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG006_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG006_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG007_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG007_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG008_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG008_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG009_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG009_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG010_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG010_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG011_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG011_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG012_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG012_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG013_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG013_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG014_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG014_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG015_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG015_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG016_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG016_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG017_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG017_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG018_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG018_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG019_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG019_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG020_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG020_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG021_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG021_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG022_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG022_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG023_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG023_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG024_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG024_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG025_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG025_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG026_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG026_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG027_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG027_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG028_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG028_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG029_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG029_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG030_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG030_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG031_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG031_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG032_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG032_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG033_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG033_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG034_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG034_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG035_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG035_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG036_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG036_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG037_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG037_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG038_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG038_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG039_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG039_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG040_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG040_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG041_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG041_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG042_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG042_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG043_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG043_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG044_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG044_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG045_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG045_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG046_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG046_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG047_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG047_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG048_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG048_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG049_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG049_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG050_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG050_OFFSET_ADDR)
#define IO_CONFIG_T_IOMG051_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_IOMG051_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG000_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG000_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG001_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG001_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG002_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG002_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG003_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG003_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG004_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG004_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG005_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG005_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG006_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG006_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG007_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG007_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG008_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG008_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG009_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG009_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG010_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG010_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG011_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG011_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG012_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG012_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG013_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG013_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG014_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG014_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG015_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG015_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG016_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG016_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG017_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG017_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG018_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG018_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG019_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG019_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG020_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG020_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG021_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG021_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG022_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG022_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG023_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG023_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG024_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG024_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG025_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG025_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG026_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG026_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG027_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG027_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG028_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG028_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG029_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG029_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG030_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG030_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG031_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG031_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG032_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG032_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG033_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG033_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG034_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG034_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG035_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG035_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG036_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG036_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG037_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG037_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG038_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG038_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG039_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG039_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG040_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG040_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG041_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG041_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG042_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG042_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG043_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG043_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG044_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG044_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG045_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG045_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG046_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG046_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG047_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG047_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG048_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG048_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG049_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG049_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG050_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG050_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG051_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG051_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG052_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG052_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG053_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG053_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG054_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG054_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG055_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG055_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG056_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG056_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG057_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG057_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG058_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG058_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG059_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG059_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG060_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG060_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG061_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG061_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG062_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG062_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG063_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG063_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG064_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG064_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG065_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG065_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG066_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG066_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG067_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG067_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG068_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG068_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG069_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG069_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG070_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG070_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG071_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG071_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG072_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG072_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG073_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG073_OFFSET_ADDR)
#define IO_CONFIG_T_PADMG074_ADDR (IO_CONFIG_T_BASE_ADDR + IO_CONFIG_T_PADMG074_OFFSET_ADDR)

#define IO_CONFIG_R 0
#define IO_CONFIG_T 1

/**
 *
 * @ingroup bm_io_config
 * @brief io_config_r read.
 *
 * @par description:
 * io_config_r read.
 *
 * @param offset [in]: register offset
 * @param val [out]: read value
 *
 * @return BM_OK/BM_FAIL
 *
 */
int bm_io_config_r_read(unsigned int offset, unsigned int *val);

/**
 *
 * @ingroup bm_io_config
 * @brief io_config_t read.
 *
 * @par description:
 * io_config_t read.
 *
 * @param offset [in]: register offset
 * @param val [out]: read value
 *
 * @return BM_OK/BM_FAIL
 *
 */
int bm_io_config_t_read(unsigned int offset, unsigned int *val);

/**
 *
 * @ingroup bm_io_config
 * @brief io_config_r write.
 *
 * @par description:
 * io_config_r write.
 *
 * @param offset [in]: register offset
 * @param val [in]: write value
 *
 * @return BM_OK/BM_FAIL
 *
 */
int bm_io_config_r_write(unsigned int offset, unsigned int val);

/**
 *
 * @ingroup bm_io_config
 * @brief io_config_t write.
 *
 * @par description:
 * io_config_t write.
 *
 * @param offset [in]: register offset
 * @param val [in]: write value
 *
 * @return BM_OK/BM_FAIL
 *
 */
int bm_io_config_t_write(unsigned int offset, unsigned int val);

/**
 *
 * @ingroup bm_io_config
 * @brief io_config_r read write.
 *
 * @par description:
 * io_config_r read write.
 *
 * @param offset [in]: register offset
 * @param mask [in]: write mask
 * @param val [in]: write value
 *
 * @return BM_OK/BM_FAIL
 *
 */
int bm_io_config_r_read_write(unsigned int offset, unsigned int mask, unsigned int val);

/**
 *
 * @ingroup bm_io_config
 * @brief io_config_t read write.
 *
 * @par description:
 * io_config_t read write.
 *
 * @param offset [in]: register offset
 * @param mask [in]: write mask
 * @param val [in]: write value
 *
 * @return BM_OK/BM_FAIL
 *
 */
int bm_io_config_t_read_write(unsigned int offset, unsigned int mask, unsigned int val);

/**
 *
 * @ingroup bm_io_config
 * @brief io_config_r set bits.
 *
 * @par description:
 * io_config_r set bits.
 *
 * @param offset [in]: register offset
 * @param mask [in]: write mask
 * @param set_bit [in]: 0/1
 *
 * @return BM_OK/BM_FAIL
 *
 */
int bm_io_config_r_set_bits(unsigned int offset, unsigned int mask, unsigned int set_bit);

/**
 *
 * @ingroup bm_io_config
 * @brief io_config_t set bits.
 *
 * @par description:
 * io_config_t set bits.
 *
 * @param offset [in]: register offset
 * @param mask [in]: write mask
 * @param set_bit [in]: 0/1
 *
 * @return BM_OK/BM_FAIL
 *
 */
int bm_io_config_t_set_bits(unsigned int offset, unsigned int mask, unsigned int set_bit);

#endif /* __IO_CONFIG_R_T_ADDR_DEFINE_H__ */
