obj-y += common/
obj-y += dma/
obj-y += gpio/
obj-y += i2c/
obj-y += local_bus/
obj-y += spi/
obj-y += uart/
obj-y += net/
obj-y += timer/
obj-y += cache/
obj-y += watchdog/
obj-y += mmu/

CFLAGS += -I$(shell pwd)/common