// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * sfc addr
 *
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __SFC_ADDR_DEFINE_H__
#define __SFC_ADDR_DEFINE_H__

#define SFC_BASE_ADDR 0x8600000

// offset address for SFC registers
#define SFC_GLOBAL_CONFIG_OFFSET_ADDR       0x100
#define SFC_TIMING_OFFSET_ADDR              0x110
#define SFC_INT_RAW_STATUS_OFFSET_ADDR      0x120
#define SFC_INT_STATUS_OFFSET_ADDR          0x124
#define SFC_INT_MASK_OFFSET_ADDR            0x128
#define SFC_INT_CLEAR_OFFSET_ADDR           0x12C
#define SFC_INT_SET_OFFSET_ADDR             0x130
#define SFC_BUS_CONFIG1_OFFSET_ADDR         0x200
#define SFC_BUS_CONFIG2_OFFSET_ADDR         0x204
#define SFC_BUS_CONFIG3_OFFSET_ADDR         0x208
#define SFC_BUS_FLASH_SIZE_OFFSET_ADDR      0x210
#define SFC_BUS_BASE_ADDR_CS0_OFFSET_ADDR   0x214
#define SFC_BUS_BASE_ADDR_CS1_OFFSET_ADDR   0x218
#define SFC_BUS_ALIAS_ADDR_OFFSET_ADDR      0x21C
#define SFC_BUS_ALIAS_CS_OFFSET_ADDR        0x220
#define SFC_BUS_DMA_CTRL_OFFSET_ADDR        0x240
#define SFC_BUS_DMA_MEM_SADDR_OFFSET_ADDR   0x244
#define SFC_BUS_DMA_FLASH_SADDR_OFFSET_ADDR 0x248
#define SFC_BUS_DMA_LEN_OFFSET_ADDR         0x24C
#define SFC_BUS_DMA_AHB_CTRL_OFFSET_ADDR    0x250
#define SFC_TIMING_PP_CTRL_OFFSET_ADDR      0x254
#define SFC_CMD_CONFIG_OFFSET_ADDR          0x300
#define SFC_CMD_INS_OFFSET_ADDR             0x308
#define SFC_CMD_ADDR_OFFSET_ADDR            0x30C
#define SFC_CMD_DATABUF_0_OFFSET_ADDR       0x400
#define SFC_CMD_DATABUF_1_OFFSET_ADDR       0x404
#define SFC_CMD_DATABUF_2_OFFSET_ADDR       0x408
#define SFC_CMD_DATABUF_3_OFFSET_ADDR       0x40C
#define SFC_CMD_DATABUF_4_OFFSET_ADDR       0x410
#define SFC_CMD_DATABUF_5_OFFSET_ADDR       0x414
#define SFC_CMD_DATABUF_6_OFFSET_ADDR       0x418
#define SFC_CMD_DATABUF_7_OFFSET_ADDR       0x41C
#define SFC_CMD_DATABUF_8_OFFSET_ADDR       0x420
#define SFC_CMD_DATABUF_9_OFFSET_ADDR       0x424
#define SFC_CMD_DATABUF_10_OFFSET_ADDR      0x428
#define SFC_CMD_DATABUF_11_OFFSET_ADDR      0x42C
#define SFC_CMD_DATABUF_12_OFFSET_ADDR      0x430
#define SFC_CMD_DATABUF_13_OFFSET_ADDR      0x434
#define SFC_CMD_DATABUF_14_OFFSET_ADDR      0x438
#define SFC_CMD_DATABUF_15_OFFSET_ADDR      0x43C
#define SFC_CMD_DATABUF_16_OFFSET_ADDR      0x440
#define SFC_CMD_DATABUF_17_OFFSET_ADDR      0x444
#define SFC_CMD_DATABUF_18_OFFSET_ADDR      0x448
#define SFC_CMD_DATABUF_19_OFFSET_ADDR      0x44C
#define SFC_CMD_DATABUF_20_OFFSET_ADDR      0x450
#define SFC_CMD_DATABUF_21_OFFSET_ADDR      0x454
#define SFC_CMD_DATABUF_22_OFFSET_ADDR      0x458
#define SFC_CMD_DATABUF_23_OFFSET_ADDR      0x45C
#define SFC_CMD_DATABUF_24_OFFSET_ADDR      0x460
#define SFC_CMD_DATABUF_25_OFFSET_ADDR      0x464
#define SFC_CMD_DATABUF_26_OFFSET_ADDR      0x468
#define SFC_CMD_DATABUF_27_OFFSET_ADDR      0x46C
#define SFC_CMD_DATABUF_28_OFFSET_ADDR      0x470
#define SFC_CMD_DATABUF_29_OFFSET_ADDR      0x474
#define SFC_CMD_DATABUF_30_OFFSET_ADDR      0x478
#define SFC_CMD_DATABUF_31_OFFSET_ADDR      0x47C

#define SFC_GLOBAL_CONFIG_ADDR       (SFC_BASE_ADDR + SFC_GLOBAL_CONFIG_OFFSET_ADDR)
#define SFC_TIMING_ADDR              (SFC_BASE_ADDR + SFC_TIMING_OFFSET_ADDR)
#define SFC_INT_RAW_STATUS_ADDR      (SFC_BASE_ADDR + SFC_INT_RAW_STATUS_OFFSET_ADDR)
#define SFC_INT_STATUS_ADDR          (SFC_BASE_ADDR + SFC_INT_STATUS_OFFSET_ADDR)
#define SFC_INT_MASK_ADDR            (SFC_BASE_ADDR + SFC_INT_MASK_OFFSET_ADDR)
#define SFC_INT_CLEAR_ADDR           (SFC_BASE_ADDR + SFC_INT_CLEAR_OFFSET_ADDR)
#define SFC_BUS_CONFIG1_ADDR         (SFC_BASE_ADDR + SFC_BUS_CONFIG1_OFFSET_ADDR)
#define SFC_BUS_CONFIG2_ADDR         (SFC_BASE_ADDR + SFC_BUS_CONFIG2_OFFSET_ADDR)
#define SFC_BUS_CONFIG3_ADDR         (SFC_BASE_ADDR + SFC_BUS_CONFIG3_OFFSET_ADDR)
#define SFC_BUS_FLASH_SIZE_ADDR      (SFC_BASE_ADDR + SFC_BUS_FLASH_SIZE_OFFSET_ADDR)
#define SFC_BUS_BASE_ADDR_CS0_ADDR   (SFC_BASE_ADDR + SFC_BUS_BASE_ADDR_CS0_OFFSET_ADDR)
#define SFC_BUS_BASE_ADDR_CS1_ADDR   (SFC_BASE_ADDR + SFC_BUS_BASE_ADDR_CS1_OFFSET_ADDR)
#define SFC_BUS_ALIAS_ADDR_ADDR      (SFC_BASE_ADDR + SFC_BUS_ALIAS_ADDR_OFFSET_ADDR)
#define SFC_BUS_ALIAS_CS_ADDR        (SFC_BASE_ADDR + SFC_BUS_ALIAS_CS_OFFSET_ADDR)
#define SFC_BUS_DMA_CTRL_ADDR        (SFC_BASE_ADDR + SFC_BUS_DMA_CTRL_OFFSET_ADDR)
#define SFC_BUS_DMA_MEM_SADDR_ADDR   (SFC_BASE_ADDR + SFC_BUS_DMA_MEM_SADDR_OFFSET_ADDR)
#define SFC_BUS_DMA_FLASH_SADDR_ADDR (SFC_BASE_ADDR + SFC_BUS_DMA_FLASH_SADDR_OFFSET_ADDR)
#define SFC_BUS_DMA_LEN_ADDR         (SFC_BASE_ADDR + SFC_BUS_DMA_LEN_OFFSET_ADDR)
#define SFC_BUS_DMA_AHB_CTRL_ADDR    (SFC_BASE_ADDR + SFC_BUS_DMA_AHB_CTRL_OFFSET_ADDR)
#define SFC_TIMING_PP_CTRL_ADDR      (SFC_BASE_ADDR + SFC_TIMING_PP_CTRL_OFFSET_ADDR)
#define SFC_CMD_CONFIG_ADDR          (SFC_BASE_ADDR + SFC_CMD_CONFIG_OFFSET_ADDR)
#define SFC_CMD_INS_ADDR             (SFC_BASE_ADDR + SFC_CMD_INS_OFFSET_ADDR)
#define SFC_CMD_ADDR_ADDR            (SFC_BASE_ADDR + SFC_CMD_ADDR_OFFSET_ADDR)
#define SFC_CMD_DATABUF_0_ADDR       (SFC_BASE_ADDR + SFC_CMD_DATABUF_0_OFFSET_ADDR)
#define SFC_CMD_DATABUF_1_ADDR       (SFC_BASE_ADDR + SFC_CMD_DATABUF_1_OFFSET_ADDR)
#define SFC_CMD_DATABUF_2_ADDR       (SFC_BASE_ADDR + SFC_CMD_DATABUF_2_OFFSET_ADDR)
#define SFC_CMD_DATABUF_3_ADDR       (SFC_BASE_ADDR + SFC_CMD_DATABUF_3_OFFSET_ADDR)
#define SFC_CMD_DATABUF_4_ADDR       (SFC_BASE_ADDR + SFC_CMD_DATABUF_4_OFFSET_ADDR)
#define SFC_CMD_DATABUF_5_ADDR       (SFC_BASE_ADDR + SFC_CMD_DATABUF_5_OFFSET_ADDR)
#define SFC_CMD_DATABUF_6_ADDR       (SFC_BASE_ADDR + SFC_CMD_DATABUF_6_OFFSET_ADDR)
#define SFC_CMD_DATABUF_7_ADDR       (SFC_BASE_ADDR + SFC_CMD_DATABUF_7_OFFSET_ADDR)
#define SFC_CMD_DATABUF_8_ADDR       (SFC_BASE_ADDR + SFC_CMD_DATABUF_8_OFFSET_ADDR)
#define SFC_CMD_DATABUF_9_ADDR       (SFC_BASE_ADDR + SFC_CMD_DATABUF_9_OFFSET_ADDR)
#define SFC_CMD_DATABUF_10_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_10_OFFSET_ADDR)
#define SFC_CMD_DATABUF_11_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_11_OFFSET_ADDR)
#define SFC_CMD_DATABUF_12_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_12_OFFSET_ADDR)
#define SFC_CMD_DATABUF_13_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_13_OFFSET_ADDR)
#define SFC_CMD_DATABUF_14_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_14_OFFSET_ADDR)
#define SFC_CMD_DATABUF_15_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_15_OFFSET_ADDR)
#define SFC_CMD_DATABUF_16_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_16_OFFSET_ADDR)
#define SFC_CMD_DATABUF_17_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_17_OFFSET_ADDR)
#define SFC_CMD_DATABUF_18_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_18_OFFSET_ADDR)
#define SFC_CMD_DATABUF_19_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_19_OFFSET_ADDR)
#define SFC_CMD_DATABUF_20_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_20_OFFSET_ADDR)
#define SFC_CMD_DATABUF_21_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_21_OFFSET_ADDR)
#define SFC_CMD_DATABUF_22_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_22_OFFSET_ADDR)
#define SFC_CMD_DATABUF_23_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_23_OFFSET_ADDR)
#define SFC_CMD_DATABUF_24_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_24_OFFSET_ADDR)
#define SFC_CMD_DATABUF_25_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_25_OFFSET_ADDR)
#define SFC_CMD_DATABUF_26_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_26_OFFSET_ADDR)
#define SFC_CMD_DATABUF_27_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_27_OFFSET_ADDR)
#define SFC_CMD_DATABUF_28_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_28_OFFSET_ADDR)
#define SFC_CMD_DATABUF_29_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_29_OFFSET_ADDR)
#define SFC_CMD_DATABUF_30_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_30_OFFSET_ADDR)
#define SFC_CMD_DATABUF_31_ADDR      (SFC_BASE_ADDR + SFC_CMD_DATABUF_31_OFFSET_ADDR)

#endif  // __SFC_ADDR_DEFINE_H__
