// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __BT_CSR_ADDR_DEFINE_H__
#define __BT_CSR_ADDR_DEFINE_H__

#define BT_CSR_BASE_ADDR              0x8727000
#define BT_CSR_CTRL_OFFSET_ADDR       0x0
#define BT_CSR_BMC2HOST_OFFSET_ADDR   0x4
#define BT_CSR_HOST2BMC_OFFSET_ADDR   0x4
#define BT_CSR_INTMASK_OFFSET_ADDR    0x8
#define BT_CSR_BMC_INT_EN_OFFSET_ADDR 0xC

#define BT_CSR_CTRL_ADDR       (BT_CSR_BASE_ADDR + BT_CSR_CTRL_OFFSET_ADDR)
#define BT_CSR_BMC2HOST_ADDR   (BT_CSR_BASE_ADDR + BT_CSR_BMC2HOST_OFFSET_ADDR)
#define BT_CSR_HOST2BMC_ADDR   (BT_CSR_BASE_ADDR + BT_CSR_HOST2BMC_OFFSET_ADDR)
#define BT_CSR_INTMASK_ADDR    (BT_CSR_BASE_ADDR + BT_CSR_INTMASK_OFFSET_ADDR)
#define BT_CSR_BMC_INT_EN_ADDR (BT_CSR_BASE_ADDR + BT_CSR_BMC_INT_EN_OFFSET_ADDR)

#endif
