// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __C80_CSR_ADDR_DEFINE_H__
#define __C80_CSR_ADDR_DEFINE_H__

#define C80_CSR_LPC_BASE_ADDR                0x8721000
#define C80_CSR_ESPI_BASE_ADDR               0x8731000
#define C80_CSR_DAT_OFFSET_ADDR              0x0
#define C80_CSR_SIOC_OFFSET_ADDR             0x4
#define C80_CSR_DAT_PRE_OFFSET_ADDR          0x80
#define C80_CSR_CURR_ADDR_OFFSET_ADDR        0x84
#define C80_CSR_DAT_NUM_OFFSET_ADDR          0x88
#define C80_CSR_RDADDR_OFFSET_ADDR           0x8C
#define C80_CSR_WRADDR_OFFSET_ADDR           0x90
#define C80_CSR_WDI_BASEADDR_OFFSET_ADDR     0x100
#define C80_CSR_UART0_BASEADDR_OFFSET_ADDR   0x104
#define C80_CSR_UART1_BASEADDR_OFFSET_ADDR   0x108
#define C80_CSR_KCS0_BASEADDR_OFFSET_ADDR    0x10C
#define C80_CSR_KCS1_BASEADDR_OFFSET_ADDR    0x110
#define C80_CSR_KCS2_BASEADDR_OFFSET_ADDR    0x114
#define C80_CSR_KCS3_BASEADDR_OFFSET_ADDR    0x118
#define C80_CSR_BT0_BASEADDR_OFFSET_ADDR     0x11C
#define C80_CSR_MAILBOX_BASEADDR_OFFSET_ADDR 0x120
#define C80_CSR_BASEADDR_OFFSET_ADDR         0x124
#define C80_CSR_SIO_BASEADDR_OFFSET_ADDR     0x128
#define C80_CSR_SPIO_IRQ_OFFSET_ADDR         0x12C
#define C80_CSR_BT0_IRQ_SEL_OFFSET_ADDR      0x130
#define C80_CSR_MAILBOX_IRQ_SEL_OFFSET_ADDR  0x134
#define C80_CSR_KCS0_IRQ_SEL_OFFSET_ADDR     0x138
#define C80_CSR_KCS1_IRQ_SEL_OFFSET_ADDR     0x13C
#define C80_CSR_KCS2_IRQ_SEL_OFFSET_ADDR     0x140
#define C80_CSR_KCS3_IRQ_SEL_OFFSET_ADDR     0x144
#define C80_CSR_WDI_IRQ_SEL_OFFSET_ADDR      0x148
#define C80_CSR_UART0_IRQ_SEL_OFFSET_ADDR    0x14C
#define C80_CSR_UART1_IRQ_SEL_OFFSET_ADDR    0x150
#define C80_CSR_LPC_UNHEART_OFFSET_ADDR      0x154
#define C80_CSR_MODULE_ACT_OFFSET_ADDR       0x158
#define C80_CSR_LPC_STATE_OFFSET_ADDR        0x160
#define C80_CSR_SIRQ_STATE_OFFSET_ADDR       0x164
#define C80_CSR_IRQ_GEN_OFFSET_ADDR          0x168
#define C80_CSR_HOSTUART0_DIVSR_OFFSET_ADDR  0x170
#define C80_CSR_HOSTUART1_DIVSR_OFFSET_ADDR  0x174
#define C80_CSR_BT1_BASEADDR_OFFSET_ADDR     0x178
#define C80_CSR_BT1_IRQ_SEL_OFFSET_ADDR      0x17C

#define C80_CSR_DAT_ADDR              (C80_CSR_BASE_ADDR + C80_CSR_DAT_OFFSET_ADDR)
#define C80_CSR_SIOC_ADDR             (C80_CSR_BASE_ADDR + C80_CSR_SIOC_OFFSET_ADDR)
#define C80_CSR_DAT_PRE_ADDR          (C80_CSR_BASE_ADDR + C80_CSR_DAT_PRE_OFFSET_ADDR)
#define C80_CSR_CURR_ADDR_ADDR        (C80_CSR_BASE_ADDR + C80_CSR_CURR_ADDR_OFFSET_ADDR)
#define C80_CSR_DAT_NUM_ADDR          (C80_CSR_BASE_ADDR + C80_CSR_DAT_NUM_OFFSET_ADDR)
#define C80_CSR_RDADDR_ADDR           (C80_CSR_BASE_ADDR + C80_CSR_RDADDR_OFFSET_ADDR)
#define C80_CSR_WRADDR_ADDR           (C80_CSR_BASE_ADDR + C80_CSR_WRADDR_OFFSET_ADDR)
#define C80_CSR_WDI_BASEADDR_ADDR     (C80_CSR_BASE_ADDR + C80_CSR_WDI_BASEADDR_OFFSET_ADDR)
#define C80_CSR_UART0_BASEADDR_ADDR   (C80_CSR_BASE_ADDR + C80_CSR_UART0_BASEADDR_OFFSET_ADDR)
#define C80_CSR_UART1_BASEADDR_ADDR   (C80_CSR_BASE_ADDR + C80_CSR_UART1_BASEADDR_OFFSET_ADDR)
#define C80_CSR_KCS0_BASEADDR_ADDR    (C80_CSR_BASE_ADDR + C80_CSR_KCS0_BASEADDR_OFFSET_ADDR)
#define C80_CSR_KCS1_BASEADDR_ADDR    (C80_CSR_BASE_ADDR + C80_CSR_KCS1_BASEADDR_OFFSET_ADDR)
#define C80_CSR_KCS2_BASEADDR_ADDR    (C80_CSR_BASE_ADDR + C80_CSR_KCS2_BASEADDR_OFFSET_ADDR)
#define C80_CSR_KCS3_BASEADDR_ADDR    (C80_CSR_BASE_ADDR + C80_CSR_KCS3_BASEADDR_OFFSET_ADDR)
#define C80_CSR_BT0_BASEADDR_ADDR     (C80_CSR_BASE_ADDR + C80_CSR_BT0_BASEADDR_OFFSET_ADDR)
#define C80_CSR_MAILBOX_BASEADDR_ADDR (C80_CSR_BASE_ADDR + C80_CSR_MAILBOX_BASEADDR_OFFSET_ADDR)
#define C80_CSR_BASEADDR_ADDR         (C80_CSR_BASE_ADDR + C80_CSR_BASEADDR_OFFSET_ADDR)
#define C80_CSR_SIO_BASEADDR_ADDR     (C80_CSR_BASE_ADDR + C80_CSR_SIO_BASEADDR_OFFSET_ADDR)
#define C80_CSR_SPIO_IRQ_ADDR         (C80_CSR_BASE_ADDR + C80_CSR_SPIO_IRQ_OFFSET_ADDR)
#define C80_CSR_BT0_IRQ_SEL_ADDR      (C80_CSR_BASE_ADDR + C80_CSR_BT0_IRQ_SEL_OFFSET_ADDR)
#define C80_CSR_MAILBOX_IRQ_SEL_ADDR  (C80_CSR_BASE_ADDR + C80_CSR_MAILBOX_IRQ_SEL_OFFSET_ADDR)
#define C80_CSR_KCS0_IRQ_SEL_ADDR     (C80_CSR_BASE_ADDR + C80_CSR_KCS0_IRQ_SEL_OFFSET_ADDR)
#define C80_CSR_KCS1_IRQ_SEL_ADDR     (C80_CSR_BASE_ADDR + C80_CSR_KCS1_IRQ_SEL_OFFSET_ADDR)
#define C80_CSR_KCS2_IRQ_SEL_ADDR     (C80_CSR_BASE_ADDR + C80_CSR_KCS2_IRQ_SEL_OFFSET_ADDR)
#define C80_CSR_KCS3_IRQ_SEL_ADDR     (C80_CSR_BASE_ADDR + C80_CSR_KCS3_IRQ_SEL_OFFSET_ADDR)
#define C80_CSR_WDI_IRQ_SEL_ADDR      (C80_CSR_BASE_ADDR + C80_CSR_WDI_IRQ_SEL_OFFSET_ADDR)
#define C80_CSR_UART0_IRQ_SEL_ADDR    (C80_CSR_BASE_ADDR + C80_CSR_UART0_IRQ_SEL_OFFSET_ADDR)
#define C80_CSR_UART1_IRQ_SEL_ADDR    (C80_CSR_BASE_ADDR + C80_CSR_UART1_IRQ_SEL_OFFSET_ADDR)
#define C80_CSR_LPC_UNHEART_ADDR      (C80_CSR_BASE_ADDR + C80_CSR_LPC_UNHEART_OFFSET_ADDR)
#define C80_CSR_MODULE_ACT_ADDR       (C80_CSR_BASE_ADDR + C80_CSR_MODULE_ACT_OFFSET_ADDR)
#define C80_CSR_LPC_STATE_ADDR        (C80_CSR_BASE_ADDR + C80_CSR_LPC_STATE_OFFSET_ADDR)
#define C80_CSR_SIRQ_STATE_ADDR       (C80_CSR_BASE_ADDR + C80_CSR_SIRQ_STATE_OFFSET_ADDR)
#define C80_CSR_IRQ_GEN_ADDR          (C80_CSR_BASE_ADDR + C80_CSR_IRQ_GEN_OFFSET_ADDR)
#define C80_CSR_HOSTUART0_DIVSR_ADDR  (C80_CSR_BASE_ADDR + C80_CSR_HOSTUART0_DIVSR_OFFSET_ADDR)
#define C80_CSR_HOSTUART1_DIVSR_ADDR  (C80_CSR_BASE_ADDR + C80_CSR_HOSTUART1_DIVSR_OFFSET_ADDR)
#define C80_CSR_BT1_BASEADDR_ADDR     (C80_CSR_BASE_ADDR + C80_CSR_BT1_BASEADDR_OFFSET_ADDR)
#define C80_CSR_BT1_IRQ_SEL_ADDR      (C80_CSR_BASE_ADDR + C80_CSR_BT1_IRQ_SEL_OFFSET_ADDR)

#endif
