// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __HOST_WDI_CSR_ADDR_DEFINE_H__
#define __HOST_WDI_CSR_ADDR_DEFINE_H__

#define    HOST_WDI_CSR_BASE_ADDR                    0x8726000

#define HOST_WDI_CSR_STA_REG_OFFSET_ADDR 0x0
#define HOST_WDI_CSR_IRM_REG_OFFSET_ADDR 0x4
#define HOST_WDI_CSR_SP1_REG_OFFSET_ADDR 0x8
#define HOST_WDI_CSR_SP2_REG_OFFSET_ADDR 0xC
#define HOST_WDI_CSR_IEN_REG_OFFSET_ADDR 0x10
#define HOST_WDI_CSR_MSC_REG_OFFSET_ADDR 0x18
#define HOST_WDI_CSR_IDF_REG_OFFSET_ADDR 0x1C

#define HOST_WDI_CSR_STA_REG_ADDR (HOST_WDI_CSR_BASE_ADDR + HOST_WDI_CSR_STA_REG_OFFSET_ADDR)
#define HOST_WDI_CSR_IRM_REG_ADDR (HOST_WDI_CSR_BASE_ADDR + HOST_WDI_CSR_IRM_REG_OFFSET_ADDR)
#define HOST_WDI_CSR_SP1_REG_ADDR (HOST_WDI_CSR_BASE_ADDR + HOST_WDI_CSR_SP1_REG_OFFSET_ADDR)
#define HOST_WDI_CSR_SP2_REG_ADDR (HOST_WDI_CSR_BASE_ADDR + HOST_WDI_CSR_SP2_REG_OFFSET_ADDR)
#define HOST_WDI_CSR_IEN_REG_ADDR (HOST_WDI_CSR_BASE_ADDR + HOST_WDI_CSR_IEN_REG_OFFSET_ADDR)
#define HOST_WDI_CSR_MSC_REG_ADDR (HOST_WDI_CSR_BASE_ADDR + HOST_WDI_CSR_MSC_REG_OFFSET_ADDR)
#define HOST_WDI_CSR_IDF_REG_ADDR (HOST_WDI_CSR_BASE_ADDR + HOST_WDI_CSR_IDF_REG_OFFSET_ADDR)

#endif // __HOST_WDI_CSR_ADDR_DEFINE_H__
