// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __I2C_ADDR_DEFINE_H__
#define __I2C_ADDR_DEFINE_H__

#define I2C_BASE_ADDR                    0x8707000
#define I2C_CON_OFFSET_ADDR              0x0
#define I2C_TAR_OFFSET_ADDR              0x4
#define I2C_SAR_OFFSET_ADDR              0x8
#define I2C_HS_MADDR_OFFSET_ADDR         0xC
#define I2C_DATA_CMD_OFFSET_ADDR         0x10
#define I2C_SS_SCL_HCNT_OFFSET_ADDR      0x14
#define I2C_SS_SCL_LCNT_OFFSET_ADDR      0x18
#define I2C_FS_SCL_HCNT_OFFSET_ADDR      0x1C
#define I2C_FS_SCL_LCNT_OFFSET_ADDR      0x20
#define I2C_HS_SCL_HCNT_OFFSET_ADDR      0x24
#define I2C_HS_SCL_LCNT_OFFSET_ADDR      0x28
#define I2C_INTR_STAT_OFFSET_ADDR        0x2C
#define I2C_INTR_MASK_OFFSET_ADDR        0x30
#define I2C_RAW_INTR_STAT_OFFSET_ADDR    0x34
#define I2C_RX_TL_OFFSET_ADDR            0x38
#define I2C_TX_TL_OFFSET_ADDR            0x3C
#define I2C_CLR_INTR_OFFSET_ADDR         0x40
#define I2C_CLR_RX_UNDER_OFFSET_ADDR     0x44
#define I2C_CLR_RX_OVER_OFFSET_ADDR      0x48
#define I2C_CLR_TX_OVER_OFFSET_ADDR      0x4C
#define I2C_CLR_RD_REQ_OFFSET_ADDR       0x50
#define I2C_CLR_TX_ABRT_OFFSET_ADDR      0x54
#define I2C_CLR_RX_DONE_OFFSET_ADDR      0x58
#define I2C_CLR_ACTIVITY_OFFSET_ADDR     0x5C
#define I2C_CLR_STOP_DET_OFFSET_ADDR     0x60
#define I2C_CLR_START_DET_OFFSET_ADDR    0x64
#define I2C_CLR_GEN_CALL_OFFSET_ADDR     0x68
#define I2C_ENABLE_OFFSET_ADDR           0x6C
#define I2C_STATUS_OFFSET_ADDR           0x70
#define I2C_TXFLR_OFFSET_ADDR            0x74
#define I2C_RXFLR_OFFSET_ADDR            0x78
#define I2C_SDA_HOLD_OFFSET_ADDR         0x7C
#define I2C_TX_ABRT_SOURCE_OFFSET_ADDR   0x80
#define I2C_SLV_DATA_ONLY_OFFSET_ADDR    0x84
#define I2C_DMA_CR_OFFSET_ADDR           0x88
#define I2C_DMA_TDLR_OFFSET_ADDR         0x8C
#define I2C_DMA_RDLR_OFFSET_ADDR         0x90
#define I2C_SDA_SETUP_OFFSET_ADDR        0x94
#define I2C_ACK_GENERAL_CALL_OFFSET_ADDR 0x98
#define I2C_ENABLE_STATUS_OFFSET_ADDR    0x9C

#define I2C_CON_ADDR              (I2C_BASE_ADDR + I2C_CON_OFFSET_ADDR)
#define I2C_TAR_ADDR              (I2C_BASE_ADDR + I2C_TAR_OFFSET_ADDR)
#define I2C_SAR_ADDR              (I2C_BASE_ADDR + I2C_SAR_OFFSET_ADDR)
#define I2C_HS_MADDR_ADDR         (I2C_BASE_ADDR + I2C_HS_MADDR_OFFSET_ADDR)
#define I2C_DATA_CMD_ADDR         (I2C_BASE_ADDR + I2C_DATA_CMD_OFFSET_ADDR)
#define I2C_SS_SCL_HCNT_ADDR      (I2C_BASE_ADDR + I2C_SS_SCL_HCNT_OFFSET_ADDR)
#define I2C_SS_SCL_LCNT_ADDR      (I2C_BASE_ADDR + I2C_SS_SCL_LCNT_OFFSET_ADDR)
#define I2C_FS_SCL_HCNT_ADDR      (I2C_BASE_ADDR + I2C_FS_SCL_HCNT_OFFSET_ADDR)
#define I2C_FS_SCL_LCNT_ADDR      (I2C_BASE_ADDR + I2C_FS_SCL_LCNT_OFFSET_ADDR)
#define I2C_HS_SCL_HCNT_ADDR      (I2C_BASE_ADDR + I2C_HS_SCL_HCNT_OFFSET_ADDR)
#define I2C_HS_SCL_LCNT_ADDR      (I2C_BASE_ADDR + I2C_HS_SCL_LCNT_OFFSET_ADDR)
#define I2C_INTR_STAT_ADDR        (I2C_BASE_ADDR + I2C_INTR_STAT_OFFSET_ADDR)
#define I2C_INTR_MASK_ADDR        (I2C_BASE_ADDR + I2C_INTR_MASK_OFFSET_ADDR)
#define I2C_RAW_INTR_STAT_ADDR    (I2C_BASE_ADDR + I2C_RAW_INTR_STAT_OFFSET_ADDR)
#define I2C_RX_TL_ADDR            (I2C_BASE_ADDR + I2C_RX_TL_OFFSET_ADDR)
#define I2C_TX_TL_ADDR            (I2C_BASE_ADDR + I2C_TX_TL_OFFSET_ADDR)
#define I2C_CLR_INTR_ADDR         (I2C_BASE_ADDR + I2C_CLR_INTR_OFFSET_ADDR)
#define I2C_CLR_RX_UNDER_ADDR     (I2C_BASE_ADDR + I2C_CLR_RX_UNDER_OFFSET_ADDR)
#define I2C_CLR_RX_OVER_ADDR      (I2C_BASE_ADDR + I2C_CLR_RX_OVER_OFFSET_ADDR)
#define I2C_CLR_TX_OVER_ADDR      (I2C_BASE_ADDR + I2C_CLR_TX_OVER_OFFSET_ADDR)
#define I2C_CLR_RD_REQ_ADDR       (I2C_BASE_ADDR + I2C_CLR_RD_REQ_OFFSET_ADDR)
#define I2C_CLR_TX_ABRT_ADDR      (I2C_BASE_ADDR + I2C_CLR_TX_ABRT_OFFSET_ADDR)
#define I2C_CLR_RX_DONE_ADDR      (I2C_BASE_ADDR + I2C_CLR_RX_DONE_OFFSET_ADDR)
#define I2C_CLR_ACTIVITY_ADDR     (I2C_BASE_ADDR + I2C_CLR_ACTIVITY_OFFSET_ADDR)
#define I2C_CLR_STOP_DET_ADDR     (I2C_BASE_ADDR + I2C_CLR_STOP_DET_OFFSET_ADDR)
#define I2C_CLR_START_DET_ADDR    (I2C_BASE_ADDR + I2C_CLR_START_DET_OFFSET_ADDR)
#define I2C_CLR_GEN_CALL_ADDR     (I2C_BASE_ADDR + I2C_CLR_GEN_CALL_OFFSET_ADDR)
#define I2C_ENABLE_ADDR           (I2C_BASE_ADDR + I2C_ENABLE_OFFSET_ADDR)
#define I2C_STATUS_ADDR           (I2C_BASE_ADDR + I2C_STATUS_OFFSET_ADDR)
#define I2C_TXFLR_ADDR            (I2C_BASE_ADDR + I2C_TXFLR_OFFSET_ADDR)
#define I2C_RXFLR_ADDR            (I2C_BASE_ADDR + I2C_RXFLR_OFFSET_ADDR)
#define I2C_SDA_HOLD_ADDR         (I2C_BASE_ADDR + I2C_SDA_HOLD_OFFSET_ADDR)
#define I2C_TX_ABRT_SOURCE_ADDR   (I2C_BASE_ADDR + I2C_TX_ABRT_SOURCE_OFFSET_ADDR)
#define I2C_SLV_DATA_ONLY_ADDR    (I2C_BASE_ADDR + I2C_SLV_DATA_ONLY_OFFSET_ADDR)
#define I2C_DMA_CR_ADDR           (I2C_BASE_ADDR + I2C_DMA_CR_OFFSET_ADDR)
#define I2C_DMA_TDLR_ADDR         (I2C_BASE_ADDR + I2C_DMA_TDLR_OFFSET_ADDR)
#define I2C_DMA_RDLR_ADDR         (I2C_BASE_ADDR + I2C_DMA_RDLR_OFFSET_ADDR)
#define I2C_SDA_SETUP_ADDR        (I2C_BASE_ADDR + I2C_SDA_SETUP_OFFSET_ADDR)
#define I2C_ACK_GENERAL_CALL_ADDR (I2C_BASE_ADDR + I2C_ACK_GENERAL_CALL_OFFSET_ADDR)
#define I2C_ENABLE_STATUS_ADDR    (I2C_BASE_ADDR + I2C_ENABLE_STATUS_OFFSET_ADDR)

#endif
