// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __IPMB_ADDR_DEFINE_H__
#define __IPMB_ADDR_DEFINE_H__

#define IPMB_BASE_ADDR               0x8716000
#define IPMB_CTR_OFFSET_ADDR         0x0
#define IPMB_TXR_OFFSET_ADDR         0x4
#define IPMB_RXR_OFFSET_ADDR         0x4
#define IPMB_CR_OFFSET_ADDR          0x8
#define IPMB_SR_OFFSET_ADDR          0xC
#define IPMB_FRM_LEN_OFFSET_ADDR     0x10
#define IPMB_RCV_NUM_OFFSET_ADDR     0x14
#define IPMB_TRANS_LEN_OFFSET_ADDR   0x18
#define IPMB_PRER_OFFSET_ADDR        0x20
#define IPMB_SLVADDR_A_OFFSET_ADDR   0x24
#define IPMB_SLVADDR_B_OFFSET_ADDR   0x28
#define IPMB_MTSR_TEST_OFFSET_ADDR   0x30
#define IPMB_DISCARD_CNT_OFFSET_ADDR 0x34
#define IPMB_RCV_CNT_OFFSET_ADDR     0x38
#define IPMB_TX_STATE_OFFSET_ADDR    0x40
#define IPMB_ECC_ERR_INT_OFFSET_ADDR 0x50
#define IPMB_START_TICK1_OFFSET_ADDR 0x60
#define IPMB_START_TICK2_OFFSET_ADDR 0x64
#define IPMB_STOP_TICK1_OFFSET_ADDR  0x68
#define IPMB_STOP_TICK2_OFFSET_ADDR  0x6C
#define IPMB_WR_TICK1_OFFSET_ADDR    0x70
#define IPMB_WR_TICK2_OFFSET_ADDR    0x74
#define IPMB_RD_TICK1_OFFSET_ADDR    0x78
#define IPMB_RD_TICK2_OFFSET_ADDR    0x7C
#define IPMB_IPMB_ID_OFFSET_ADDR     0xC10

#define IPMB_CTR_ADDR         (IPMB_BASE_ADDR + IPMB_CTR_OFFSET_ADDR)
#define IPMB_TXR_ADDR         (IPMB_BASE_ADDR + IPMB_TXR_OFFSET_ADDR)
#define IPMB_RXR_ADDR         (IPMB_BASE_ADDR + IPMB_RXR_OFFSET_ADDR)
#define IPMB_CR_ADDR          (IPMB_BASE_ADDR + IPMB_CR_OFFSET_ADDR)
#define IPMB_SR_ADDR          (IPMB_BASE_ADDR + IPMB_SR_OFFSET_ADDR)
#define IPMB_FRM_LEN_ADDR     (IPMB_BASE_ADDR + IPMB_FRM_LEN_OFFSET_ADDR)
#define IPMB_RCV_NUM_ADDR     (IPMB_BASE_ADDR + IPMB_RCV_NUM_OFFSET_ADDR)
#define IPMB_TRANS_LEN_ADDR   (IPMB_BASE_ADDR + IPMB_TRANS_LEN_OFFSET_ADDR)
#define IPMB_PRER_ADDR        (IPMB_BASE_ADDR + IPMB_PRER_OFFSET_ADDR)
#define IPMB_SLVADDR_A_ADDR   (IPMB_BASE_ADDR + IPMB_SLVADDR_A_OFFSET_ADDR)
#define IPMB_SLVADDR_B_ADDR   (IPMB_BASE_ADDR + IPMB_SLVADDR_B_OFFSET_ADDR)
#define IPMB_MTSR_TEST_ADDR   (IPMB_BASE_ADDR + IPMB_MTSR_TEST_OFFSET_ADDR)
#define IPMB_DISCARD_CNT_ADDR (IPMB_BASE_ADDR + IPMB_DISCARD_CNT_OFFSET_ADDR)
#define IPMB_RCV_CNT_ADDR     (IPMB_BASE_ADDR + IPMB_RCV_CNT_OFFSET_ADDR)
#define IPMB_TX_STATE_ADDR    (IPMB_BASE_ADDR + IPMB_TX_STATE_OFFSET_ADDR)
#define IPMB_ECC_ERR_INT_ADDR (IPMB_BASE_ADDR + IPMB_ECC_ERR_INT_OFFSET_ADDR)
#define IPMB_START_TICK1_ADDR (IPMB_BASE_ADDR + IPMB_START_TICK1_OFFSET_ADDR)
#define IPMB_START_TICK2_ADDR (IPMB_BASE_ADDR + IPMB_START_TICK2_OFFSET_ADDR)
#define IPMB_STOP_TICK1_ADDR  (IPMB_BASE_ADDR + IPMB_STOP_TICK1_OFFSET_ADDR)
#define IPMB_STOP_TICK2_ADDR  (IPMB_BASE_ADDR + IPMB_STOP_TICK2_OFFSET_ADDR)
#define IPMB_WR_TICK1_ADDR    (IPMB_BASE_ADDR + IPMB_WR_TICK1_OFFSET_ADDR)
#define IPMB_WR_TICK2_ADDR    (IPMB_BASE_ADDR + IPMB_WR_TICK2_OFFSET_ADDR)
#define IPMB_RD_TICK1_ADDR    (IPMB_BASE_ADDR + IPMB_RD_TICK1_OFFSET_ADDR)
#define IPMB_RD_TICK2_ADDR    (IPMB_BASE_ADDR + IPMB_RD_TICK2_OFFSET_ADDR)
#define IPMB_IPMB_ID_ADDR     (IPMB_BASE_ADDR + IPMB_IPMB_ID_OFFSET_ADDR)

#endif
