// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __JLC_CSR_ADDR_DEFINE_H__
#define __JLC_CSR_ADDR_DEFINE_H__

#define JLC_CSR_BASE_ADDR 0x8748000

#define JLC_CSR_CR_OFFSET_ADDR                0x0
#define JLC_CSR_ENABLE_OFFSET_ADDR            0x4
#define JLC_CSR_TDI_DATA_OFFSET_ADDR          0x8
#define JLC_CSR_TDO_DATA_OFFSET_ADDR          0x8
#define JLC_CSR_TDI2_DATA_OFFSET_ADDR         0xC
#define JLC_CSR_TDO2_DATA_OFFSET_ADDR         0xC
#define JLC_CSR_TDI2_SIZE_OFFSET_ADDR         0x10
#define JLC_CSR_TMS_DATA_OFFSET_ADDR          0x14
#define JLC_CSR_TMS_SIZE_OFFSET_ADDR          0x18
#define JLC_CSR_TMS2_DATA_OFFSET_ADDR         0x1C
#define JLC_CSR_TMS2_SIZE_OFFSET_ADDR         0x20
#define JLC_CSR_BUF_LEVEL_OFFSET_ADDR         0x24
#define JLC_CSR_TCK_RATE_OFFSET_ADDR          0x28
#define JLC_CSR_CH_EN_OFFSET_ADDR             0x2C
#define JLC_CSR_STAT_OFFSET_ADDR              0x30
#define JLC_CSR_INT_EN_OFFSET_ADDR            0x34
#define JLC_CSR_INT_STAT_OFFSET_ADDR          0x38
#define JLC_CSR_INT_CLR_OFFSET_ADDR           0x3C
#define JLC_CSR_START_OFFSET_ADDR             0x40
#define JLC_CSR_TRST_OFFSET_ADDR              0x44
#define JLC_CSR_TCK_IDLE_OFFSET_ADDR          0x48
#define JLC_CSR_DW_OFFSET_ADDR                0x4C
#define JLC_CSR_SEN_OFFSET_ADDR               0x50
#define JLC_CSR_TDI2_DATA2_OFFSET_ADDR        0x54
#define JLC_CSR_TDO2_DATA2_OFFSET_ADDR        0x54
#define JLC_CSR_TDI2_SIZE2_OFFSET_ADDR        0x58
#define JLC_CSR_DW_LEN_OFFSET_ADDR            0x5C
#define JLC_CSR_DW_CFG_OFFSET_ADDR            0x60
#define JLC_CSR_DW2_CFG_OFFSET_ADDR           0x64
#define JLC_CSR_BUF2_LEVEL_OFFSET_ADDR        0x68
#define JLC_CSR_DLY_EN_OFFSET_ADDR            0x6C
#define JLC_CSR_SAM_DLY_OFFSET_ADDR           0x70
#define JLC_CSR_VERSION_OFFSET_ADDR           0x80
#define JLC_CSR_TDI_BUF1_DATA_0_OFFSET_ADDR   0x800
#define JLC_CSR_TDI_BUF1_DATA_1_OFFSET_ADDR   0x804
#define JLC_CSR_TDI_BUF1_DATA_2_OFFSET_ADDR   0x808
#define JLC_CSR_TDI_BUF1_DATA_3_OFFSET_ADDR   0x80C
#define JLC_CSR_TDI_BUF1_DATA_4_OFFSET_ADDR   0x810
#define JLC_CSR_TDI_BUF1_DATA_5_OFFSET_ADDR   0x814
#define JLC_CSR_TDI_BUF1_DATA_6_OFFSET_ADDR   0x818
#define JLC_CSR_TDI_BUF1_DATA_7_OFFSET_ADDR   0x81C
#define JLC_CSR_TDI_BUF1_DATA_8_OFFSET_ADDR   0x820
#define JLC_CSR_TDI_BUF1_DATA_9_OFFSET_ADDR   0x824
#define JLC_CSR_TDI_BUF1_DATA_10_OFFSET_ADDR  0x828
#define JLC_CSR_TDI_BUF1_DATA_11_OFFSET_ADDR  0x82C
#define JLC_CSR_TDI_BUF1_DATA_12_OFFSET_ADDR  0x830
#define JLC_CSR_TDI_BUF1_DATA_13_OFFSET_ADDR  0x834
#define JLC_CSR_TDI_BUF1_DATA_14_OFFSET_ADDR  0x838
#define JLC_CSR_TDI_BUF1_DATA_15_OFFSET_ADDR  0x83C
#define JLC_CSR_TDI_BUF1_DATA_16_OFFSET_ADDR  0x840
#define JLC_CSR_TDI_BUF1_DATA_17_OFFSET_ADDR  0x844
#define JLC_CSR_TDI_BUF1_DATA_18_OFFSET_ADDR  0x848
#define JLC_CSR_TDI_BUF1_DATA_19_OFFSET_ADDR  0x84C
#define JLC_CSR_TDI_BUF1_DATA_20_OFFSET_ADDR  0x850
#define JLC_CSR_TDI_BUF1_DATA_21_OFFSET_ADDR  0x854
#define JLC_CSR_TDI_BUF1_DATA_22_OFFSET_ADDR  0x858
#define JLC_CSR_TDI_BUF1_DATA_23_OFFSET_ADDR  0x85C
#define JLC_CSR_TDI_BUF1_DATA_24_OFFSET_ADDR  0x860
#define JLC_CSR_TDI_BUF1_DATA_25_OFFSET_ADDR  0x864
#define JLC_CSR_TDI_BUF1_DATA_26_OFFSET_ADDR  0x868
#define JLC_CSR_TDI_BUF1_DATA_27_OFFSET_ADDR  0x86C
#define JLC_CSR_TDI_BUF1_DATA_28_OFFSET_ADDR  0x870
#define JLC_CSR_TDI_BUF1_DATA_29_OFFSET_ADDR  0x874
#define JLC_CSR_TDI_BUF1_DATA_30_OFFSET_ADDR  0x878
#define JLC_CSR_TDI_BUF1_DATA_31_OFFSET_ADDR  0x87C
#define JLC_CSR_TDI_BUF1_DATA_32_OFFSET_ADDR  0x880
#define JLC_CSR_TDI_BUF1_DATA_33_OFFSET_ADDR  0x884
#define JLC_CSR_TDI_BUF1_DATA_34_OFFSET_ADDR  0x888
#define JLC_CSR_TDI_BUF1_DATA_35_OFFSET_ADDR  0x88C
#define JLC_CSR_TDI_BUF1_DATA_36_OFFSET_ADDR  0x890
#define JLC_CSR_TDI_BUF1_DATA_37_OFFSET_ADDR  0x894
#define JLC_CSR_TDI_BUF1_DATA_38_OFFSET_ADDR  0x898
#define JLC_CSR_TDI_BUF1_DATA_39_OFFSET_ADDR  0x89C
#define JLC_CSR_TDI_BUF1_DATA_40_OFFSET_ADDR  0x8A0
#define JLC_CSR_TDI_BUF1_DATA_41_OFFSET_ADDR  0x8A4
#define JLC_CSR_TDI_BUF1_DATA_42_OFFSET_ADDR  0x8A8
#define JLC_CSR_TDI_BUF1_DATA_43_OFFSET_ADDR  0x8AC
#define JLC_CSR_TDI_BUF1_DATA_44_OFFSET_ADDR  0x8B0
#define JLC_CSR_TDI_BUF1_DATA_45_OFFSET_ADDR  0x8B4
#define JLC_CSR_TDI_BUF1_DATA_46_OFFSET_ADDR  0x8B8
#define JLC_CSR_TDI_BUF1_DATA_47_OFFSET_ADDR  0x8BC
#define JLC_CSR_TDI_BUF1_DATA_48_OFFSET_ADDR  0x8C0
#define JLC_CSR_TDI_BUF1_DATA_49_OFFSET_ADDR  0x8C4
#define JLC_CSR_TDI_BUF1_DATA_50_OFFSET_ADDR  0x8C8
#define JLC_CSR_TDI_BUF1_DATA_51_OFFSET_ADDR  0x8CC
#define JLC_CSR_TDI_BUF1_DATA_52_OFFSET_ADDR  0x8D0
#define JLC_CSR_TDI_BUF1_DATA_53_OFFSET_ADDR  0x8D4
#define JLC_CSR_TDI_BUF1_DATA_54_OFFSET_ADDR  0x8D8
#define JLC_CSR_TDI_BUF1_DATA_55_OFFSET_ADDR  0x8DC
#define JLC_CSR_TDI_BUF1_DATA_56_OFFSET_ADDR  0x8E0
#define JLC_CSR_TDI_BUF1_DATA_57_OFFSET_ADDR  0x8E4
#define JLC_CSR_TDI_BUF1_DATA_58_OFFSET_ADDR  0x8E8
#define JLC_CSR_TDI_BUF1_DATA_59_OFFSET_ADDR  0x8EC
#define JLC_CSR_TDI_BUF1_DATA_60_OFFSET_ADDR  0x8F0
#define JLC_CSR_TDI_BUF1_DATA_61_OFFSET_ADDR  0x8F4
#define JLC_CSR_TDI_BUF1_DATA_62_OFFSET_ADDR  0x8F8
#define JLC_CSR_TDI_BUF1_DATA_63_OFFSET_ADDR  0x8FC
#define JLC_CSR_TDI_BUF1_DATA_64_OFFSET_ADDR  0x900
#define JLC_CSR_TDI_BUF1_DATA_65_OFFSET_ADDR  0x904
#define JLC_CSR_TDI_BUF1_DATA_66_OFFSET_ADDR  0x908
#define JLC_CSR_TDI_BUF1_DATA_67_OFFSET_ADDR  0x90C
#define JLC_CSR_TDI_BUF1_DATA_68_OFFSET_ADDR  0x910
#define JLC_CSR_TDI_BUF1_DATA_69_OFFSET_ADDR  0x914
#define JLC_CSR_TDI_BUF1_DATA_70_OFFSET_ADDR  0x918
#define JLC_CSR_TDI_BUF1_DATA_71_OFFSET_ADDR  0x91C
#define JLC_CSR_TDI_BUF1_DATA_72_OFFSET_ADDR  0x920
#define JLC_CSR_TDI_BUF1_DATA_73_OFFSET_ADDR  0x924
#define JLC_CSR_TDI_BUF1_DATA_74_OFFSET_ADDR  0x928
#define JLC_CSR_TDI_BUF1_DATA_75_OFFSET_ADDR  0x92C
#define JLC_CSR_TDI_BUF1_DATA_76_OFFSET_ADDR  0x930
#define JLC_CSR_TDI_BUF1_DATA_77_OFFSET_ADDR  0x934
#define JLC_CSR_TDI_BUF1_DATA_78_OFFSET_ADDR  0x938
#define JLC_CSR_TDI_BUF1_DATA_79_OFFSET_ADDR  0x93C
#define JLC_CSR_TDI_BUF1_DATA_80_OFFSET_ADDR  0x940
#define JLC_CSR_TDI_BUF1_DATA_81_OFFSET_ADDR  0x944
#define JLC_CSR_TDI_BUF1_DATA_82_OFFSET_ADDR  0x948
#define JLC_CSR_TDI_BUF1_DATA_83_OFFSET_ADDR  0x94C
#define JLC_CSR_TDI_BUF1_DATA_84_OFFSET_ADDR  0x950
#define JLC_CSR_TDI_BUF1_DATA_85_OFFSET_ADDR  0x954
#define JLC_CSR_TDI_BUF1_DATA_86_OFFSET_ADDR  0x958
#define JLC_CSR_TDI_BUF1_DATA_87_OFFSET_ADDR  0x95C
#define JLC_CSR_TDI_BUF1_DATA_88_OFFSET_ADDR  0x960
#define JLC_CSR_TDI_BUF1_DATA_89_OFFSET_ADDR  0x964
#define JLC_CSR_TDI_BUF1_DATA_90_OFFSET_ADDR  0x968
#define JLC_CSR_TDI_BUF1_DATA_91_OFFSET_ADDR  0x96C
#define JLC_CSR_TDI_BUF1_DATA_92_OFFSET_ADDR  0x970
#define JLC_CSR_TDI_BUF1_DATA_93_OFFSET_ADDR  0x974
#define JLC_CSR_TDI_BUF1_DATA_94_OFFSET_ADDR  0x978
#define JLC_CSR_TDI_BUF1_DATA_95_OFFSET_ADDR  0x97C
#define JLC_CSR_TDI_BUF1_DATA_96_OFFSET_ADDR  0x980
#define JLC_CSR_TDI_BUF1_DATA_97_OFFSET_ADDR  0x984
#define JLC_CSR_TDI_BUF1_DATA_98_OFFSET_ADDR  0x988
#define JLC_CSR_TDI_BUF1_DATA_99_OFFSET_ADDR  0x98C
#define JLC_CSR_TDI_BUF1_DATA_100_OFFSET_ADDR 0x990
#define JLC_CSR_TDI_BUF1_DATA_101_OFFSET_ADDR 0x994
#define JLC_CSR_TDI_BUF1_DATA_102_OFFSET_ADDR 0x998
#define JLC_CSR_TDI_BUF1_DATA_103_OFFSET_ADDR 0x99C
#define JLC_CSR_TDI_BUF1_DATA_104_OFFSET_ADDR 0x9A0
#define JLC_CSR_TDI_BUF1_DATA_105_OFFSET_ADDR 0x9A4
#define JLC_CSR_TDI_BUF1_DATA_106_OFFSET_ADDR 0x9A8
#define JLC_CSR_TDI_BUF1_DATA_107_OFFSET_ADDR 0x9AC
#define JLC_CSR_TDI_BUF1_DATA_108_OFFSET_ADDR 0x9B0
#define JLC_CSR_TDI_BUF1_DATA_109_OFFSET_ADDR 0x9B4
#define JLC_CSR_TDI_BUF1_DATA_110_OFFSET_ADDR 0x9B8
#define JLC_CSR_TDI_BUF1_DATA_111_OFFSET_ADDR 0x9BC
#define JLC_CSR_TDI_BUF1_DATA_112_OFFSET_ADDR 0x9C0
#define JLC_CSR_TDI_BUF1_DATA_113_OFFSET_ADDR 0x9C4
#define JLC_CSR_TDI_BUF1_DATA_114_OFFSET_ADDR 0x9C8
#define JLC_CSR_TDI_BUF1_DATA_115_OFFSET_ADDR 0x9CC
#define JLC_CSR_TDI_BUF1_DATA_116_OFFSET_ADDR 0x9D0
#define JLC_CSR_TDI_BUF1_DATA_117_OFFSET_ADDR 0x9D4
#define JLC_CSR_TDI_BUF1_DATA_118_OFFSET_ADDR 0x9D8
#define JLC_CSR_TDI_BUF1_DATA_119_OFFSET_ADDR 0x9DC
#define JLC_CSR_TDI_BUF1_DATA_120_OFFSET_ADDR 0x9E0
#define JLC_CSR_TDI_BUF1_DATA_121_OFFSET_ADDR 0x9E4
#define JLC_CSR_TDI_BUF1_DATA_122_OFFSET_ADDR 0x9E8
#define JLC_CSR_TDI_BUF1_DATA_123_OFFSET_ADDR 0x9EC
#define JLC_CSR_TDI_BUF1_DATA_124_OFFSET_ADDR 0x9F0
#define JLC_CSR_TDI_BUF1_DATA_125_OFFSET_ADDR 0x9F4
#define JLC_CSR_TDI_BUF1_DATA_126_OFFSET_ADDR 0x9F8
#define JLC_CSR_TDI_BUF1_DATA_127_OFFSET_ADDR 0x9FC
#define JLC_CSR_TDI_BUF2_DATA_0_OFFSET_ADDR   0xC00
#define JLC_CSR_TDI_BUF2_DATA_1_OFFSET_ADDR   0xC04
#define JLC_CSR_TDI_BUF2_DATA_2_OFFSET_ADDR   0xC08
#define JLC_CSR_TDI_BUF2_DATA_3_OFFSET_ADDR   0xC0C
#define JLC_CSR_TDI_BUF2_DATA_4_OFFSET_ADDR   0xC10
#define JLC_CSR_TDI_BUF2_DATA_5_OFFSET_ADDR   0xC14
#define JLC_CSR_TDI_BUF2_DATA_6_OFFSET_ADDR   0xC18
#define JLC_CSR_TDI_BUF2_DATA_7_OFFSET_ADDR   0xC1C
#define JLC_CSR_TDI_BUF2_DATA_8_OFFSET_ADDR   0xC20
#define JLC_CSR_TDI_BUF2_DATA_9_OFFSET_ADDR   0xC24
#define JLC_CSR_TDI_BUF2_DATA_10_OFFSET_ADDR  0xC28
#define JLC_CSR_TDI_BUF2_DATA_11_OFFSET_ADDR  0xC2C
#define JLC_CSR_TDI_BUF2_DATA_12_OFFSET_ADDR  0xC30
#define JLC_CSR_TDI_BUF2_DATA_13_OFFSET_ADDR  0xC34
#define JLC_CSR_TDI_BUF2_DATA_14_OFFSET_ADDR  0xC38
#define JLC_CSR_TDI_BUF2_DATA_15_OFFSET_ADDR  0xC3C
#define JLC_CSR_TDI_BUF2_DATA_16_OFFSET_ADDR  0xC40
#define JLC_CSR_TDI_BUF2_DATA_17_OFFSET_ADDR  0xC44
#define JLC_CSR_TDI_BUF2_DATA_18_OFFSET_ADDR  0xC48
#define JLC_CSR_TDI_BUF2_DATA_19_OFFSET_ADDR  0xC4C
#define JLC_CSR_TDI_BUF2_DATA_20_OFFSET_ADDR  0xC50
#define JLC_CSR_TDI_BUF2_DATA_21_OFFSET_ADDR  0xC54
#define JLC_CSR_TDI_BUF2_DATA_22_OFFSET_ADDR  0xC58
#define JLC_CSR_TDI_BUF2_DATA_23_OFFSET_ADDR  0xC5C
#define JLC_CSR_TDI_BUF2_DATA_24_OFFSET_ADDR  0xC60
#define JLC_CSR_TDI_BUF2_DATA_25_OFFSET_ADDR  0xC64
#define JLC_CSR_TDI_BUF2_DATA_26_OFFSET_ADDR  0xC68
#define JLC_CSR_TDI_BUF2_DATA_27_OFFSET_ADDR  0xC6C
#define JLC_CSR_TDI_BUF2_DATA_28_OFFSET_ADDR  0xC70
#define JLC_CSR_TDI_BUF2_DATA_29_OFFSET_ADDR  0xC74
#define JLC_CSR_TDI_BUF2_DATA_30_OFFSET_ADDR  0xC78
#define JLC_CSR_TDI_BUF2_DATA_31_OFFSET_ADDR  0xC7C
#define JLC_CSR_TDI_BUF2_DATA_32_OFFSET_ADDR  0xC80
#define JLC_CSR_TDI_BUF2_DATA_33_OFFSET_ADDR  0xC84
#define JLC_CSR_TDI_BUF2_DATA_34_OFFSET_ADDR  0xC88
#define JLC_CSR_TDI_BUF2_DATA_35_OFFSET_ADDR  0xC8C
#define JLC_CSR_TDI_BUF2_DATA_36_OFFSET_ADDR  0xC90
#define JLC_CSR_TDI_BUF2_DATA_37_OFFSET_ADDR  0xC94
#define JLC_CSR_TDI_BUF2_DATA_38_OFFSET_ADDR  0xC98
#define JLC_CSR_TDI_BUF2_DATA_39_OFFSET_ADDR  0xC9C
#define JLC_CSR_TDI_BUF2_DATA_40_OFFSET_ADDR  0xCA0
#define JLC_CSR_TDI_BUF2_DATA_41_OFFSET_ADDR  0xCA4
#define JLC_CSR_TDI_BUF2_DATA_42_OFFSET_ADDR  0xCA8
#define JLC_CSR_TDI_BUF2_DATA_43_OFFSET_ADDR  0xCAC
#define JLC_CSR_TDI_BUF2_DATA_44_OFFSET_ADDR  0xCB0
#define JLC_CSR_TDI_BUF2_DATA_45_OFFSET_ADDR  0xCB4
#define JLC_CSR_TDI_BUF2_DATA_46_OFFSET_ADDR  0xCB8
#define JLC_CSR_TDI_BUF2_DATA_47_OFFSET_ADDR  0xCBC
#define JLC_CSR_TDI_BUF2_DATA_48_OFFSET_ADDR  0xCC0
#define JLC_CSR_TDI_BUF2_DATA_49_OFFSET_ADDR  0xCC4
#define JLC_CSR_TDI_BUF2_DATA_50_OFFSET_ADDR  0xCC8
#define JLC_CSR_TDI_BUF2_DATA_51_OFFSET_ADDR  0xCCC
#define JLC_CSR_TDI_BUF2_DATA_52_OFFSET_ADDR  0xCD0
#define JLC_CSR_TDI_BUF2_DATA_53_OFFSET_ADDR  0xCD4
#define JLC_CSR_TDI_BUF2_DATA_54_OFFSET_ADDR  0xCD8
#define JLC_CSR_TDI_BUF2_DATA_55_OFFSET_ADDR  0xCDC
#define JLC_CSR_TDI_BUF2_DATA_56_OFFSET_ADDR  0xCE0
#define JLC_CSR_TDI_BUF2_DATA_57_OFFSET_ADDR  0xCE4
#define JLC_CSR_TDI_BUF2_DATA_58_OFFSET_ADDR  0xCE8
#define JLC_CSR_TDI_BUF2_DATA_59_OFFSET_ADDR  0xCEC
#define JLC_CSR_TDI_BUF2_DATA_60_OFFSET_ADDR  0xCF0
#define JLC_CSR_TDI_BUF2_DATA_61_OFFSET_ADDR  0xCF4
#define JLC_CSR_TDI_BUF2_DATA_62_OFFSET_ADDR  0xCF8
#define JLC_CSR_TDI_BUF2_DATA_63_OFFSET_ADDR  0xCFC
#define JLC_CSR_TDI_BUF2_DATA_64_OFFSET_ADDR  0xD00
#define JLC_CSR_TDI_BUF2_DATA_65_OFFSET_ADDR  0xD04
#define JLC_CSR_TDI_BUF2_DATA_66_OFFSET_ADDR  0xD08
#define JLC_CSR_TDI_BUF2_DATA_67_OFFSET_ADDR  0xD0C
#define JLC_CSR_TDI_BUF2_DATA_68_OFFSET_ADDR  0xD10
#define JLC_CSR_TDI_BUF2_DATA_69_OFFSET_ADDR  0xD14
#define JLC_CSR_TDI_BUF2_DATA_70_OFFSET_ADDR  0xD18
#define JLC_CSR_TDI_BUF2_DATA_71_OFFSET_ADDR  0xD1C
#define JLC_CSR_TDI_BUF2_DATA_72_OFFSET_ADDR  0xD20
#define JLC_CSR_TDI_BUF2_DATA_73_OFFSET_ADDR  0xD24
#define JLC_CSR_TDI_BUF2_DATA_74_OFFSET_ADDR  0xD28
#define JLC_CSR_TDI_BUF2_DATA_75_OFFSET_ADDR  0xD2C
#define JLC_CSR_TDI_BUF2_DATA_76_OFFSET_ADDR  0xD30
#define JLC_CSR_TDI_BUF2_DATA_77_OFFSET_ADDR  0xD34
#define JLC_CSR_TDI_BUF2_DATA_78_OFFSET_ADDR  0xD38
#define JLC_CSR_TDI_BUF2_DATA_79_OFFSET_ADDR  0xD3C
#define JLC_CSR_TDI_BUF2_DATA_80_OFFSET_ADDR  0xD40
#define JLC_CSR_TDI_BUF2_DATA_81_OFFSET_ADDR  0xD44
#define JLC_CSR_TDI_BUF2_DATA_82_OFFSET_ADDR  0xD48
#define JLC_CSR_TDI_BUF2_DATA_83_OFFSET_ADDR  0xD4C
#define JLC_CSR_TDI_BUF2_DATA_84_OFFSET_ADDR  0xD50
#define JLC_CSR_TDI_BUF2_DATA_85_OFFSET_ADDR  0xD54
#define JLC_CSR_TDI_BUF2_DATA_86_OFFSET_ADDR  0xD58
#define JLC_CSR_TDI_BUF2_DATA_87_OFFSET_ADDR  0xD5C
#define JLC_CSR_TDI_BUF2_DATA_88_OFFSET_ADDR  0xD60
#define JLC_CSR_TDI_BUF2_DATA_89_OFFSET_ADDR  0xD64
#define JLC_CSR_TDI_BUF2_DATA_90_OFFSET_ADDR  0xD68
#define JLC_CSR_TDI_BUF2_DATA_91_OFFSET_ADDR  0xD6C
#define JLC_CSR_TDI_BUF2_DATA_92_OFFSET_ADDR  0xD70
#define JLC_CSR_TDI_BUF2_DATA_93_OFFSET_ADDR  0xD74
#define JLC_CSR_TDI_BUF2_DATA_94_OFFSET_ADDR  0xD78
#define JLC_CSR_TDI_BUF2_DATA_95_OFFSET_ADDR  0xD7C
#define JLC_CSR_TDI_BUF2_DATA_96_OFFSET_ADDR  0xD80
#define JLC_CSR_TDI_BUF2_DATA_97_OFFSET_ADDR  0xD84
#define JLC_CSR_TDI_BUF2_DATA_98_OFFSET_ADDR  0xD88
#define JLC_CSR_TDI_BUF2_DATA_99_OFFSET_ADDR  0xD8C
#define JLC_CSR_TDI_BUF2_DATA_100_OFFSET_ADDR 0xD90
#define JLC_CSR_TDI_BUF2_DATA_101_OFFSET_ADDR 0xD94
#define JLC_CSR_TDI_BUF2_DATA_102_OFFSET_ADDR 0xD98
#define JLC_CSR_TDI_BUF2_DATA_103_OFFSET_ADDR 0xD9C
#define JLC_CSR_TDI_BUF2_DATA_104_OFFSET_ADDR 0xDA0
#define JLC_CSR_TDI_BUF2_DATA_105_OFFSET_ADDR 0xDA4
#define JLC_CSR_TDI_BUF2_DATA_106_OFFSET_ADDR 0xDA8
#define JLC_CSR_TDI_BUF2_DATA_107_OFFSET_ADDR 0xDAC
#define JLC_CSR_TDI_BUF2_DATA_108_OFFSET_ADDR 0xDB0
#define JLC_CSR_TDI_BUF2_DATA_109_OFFSET_ADDR 0xDB4
#define JLC_CSR_TDI_BUF2_DATA_110_OFFSET_ADDR 0xDB8
#define JLC_CSR_TDI_BUF2_DATA_111_OFFSET_ADDR 0xDBC
#define JLC_CSR_TDI_BUF2_DATA_112_OFFSET_ADDR 0xDC0
#define JLC_CSR_TDI_BUF2_DATA_113_OFFSET_ADDR 0xDC4
#define JLC_CSR_TDI_BUF2_DATA_114_OFFSET_ADDR 0xDC8
#define JLC_CSR_TDI_BUF2_DATA_115_OFFSET_ADDR 0xDCC
#define JLC_CSR_TDI_BUF2_DATA_116_OFFSET_ADDR 0xDD0
#define JLC_CSR_TDI_BUF2_DATA_117_OFFSET_ADDR 0xDD4
#define JLC_CSR_TDI_BUF2_DATA_118_OFFSET_ADDR 0xDD8
#define JLC_CSR_TDI_BUF2_DATA_119_OFFSET_ADDR 0xDDC
#define JLC_CSR_TDI_BUF2_DATA_120_OFFSET_ADDR 0xDE0
#define JLC_CSR_TDI_BUF2_DATA_121_OFFSET_ADDR 0xDE4
#define JLC_CSR_TDI_BUF2_DATA_122_OFFSET_ADDR 0xDE8
#define JLC_CSR_TDI_BUF2_DATA_123_OFFSET_ADDR 0xDEC
#define JLC_CSR_TDI_BUF2_DATA_124_OFFSET_ADDR 0xDF0
#define JLC_CSR_TDI_BUF2_DATA_125_OFFSET_ADDR 0xDF4
#define JLC_CSR_TDI_BUF2_DATA_126_OFFSET_ADDR 0xDF8
#define JLC_CSR_TDI_BUF2_DATA_127_OFFSET_ADDR 0xDFC

#define JLC_CSR_CR_ADDR                (JLC_CSR_BASE_ADDR + JLC_CSR_CR_OFFSET_ADDR)
#define JLC_CSR_ENABLE_ADDR            (JLC_CSR_BASE_ADDR + JLC_CSR_ENABLE_OFFSET_ADDR)
#define JLC_CSR_TDI_DATA_ADDR          (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_DATA_OFFSET_ADDR)
#define JLC_CSR_TDO_DATA_ADDR          (JLC_CSR_BASE_ADDR + JLC_CSR_TDO_DATA_OFFSET_ADDR)
#define JLC_CSR_TDI2_DATA_ADDR         (JLC_CSR_BASE_ADDR + JLC_CSR_TDI2_DATA_OFFSET_ADDR)
#define JLC_CSR_TDO2_DATA_ADDR         (JLC_CSR_BASE_ADDR + JLC_CSR_TDO2_DATA_OFFSET_ADDR)
#define JLC_CSR_TDI2_SIZE_ADDR         (JLC_CSR_BASE_ADDR + JLC_CSR_TDI2_SIZE_OFFSET_ADDR)
#define JLC_CSR_TMS_DATA_ADDR          (JLC_CSR_BASE_ADDR + JLC_CSR_TMS_DATA_OFFSET_ADDR)
#define JLC_CSR_TMS_SIZE_ADDR          (JLC_CSR_BASE_ADDR + JLC_CSR_TMS_SIZE_OFFSET_ADDR)
#define JLC_CSR_TMS2_DATA_ADDR         (JLC_CSR_BASE_ADDR + JLC_CSR_TMS2_DATA_OFFSET_ADDR)
#define JLC_CSR_TMS2_SIZE_ADDR         (JLC_CSR_BASE_ADDR + JLC_CSR_TMS2_SIZE_OFFSET_ADDR)
#define JLC_CSR_BUF_LEVEL_ADDR         (JLC_CSR_BASE_ADDR + JLC_CSR_BUF_LEVEL_OFFSET_ADDR)
#define JLC_CSR_TCK_RATE_ADDR          (JLC_CSR_BASE_ADDR + JLC_CSR_TCK_RATE_OFFSET_ADDR)
#define JLC_CSR_CH_EN_ADDR             (JLC_CSR_BASE_ADDR + JLC_CSR_CH_EN_OFFSET_ADDR)
#define JLC_CSR_STAT_ADDR              (JLC_CSR_BASE_ADDR + JLC_CSR_STAT_OFFSET_ADDR)
#define JLC_CSR_INT_EN_ADDR            (JLC_CSR_BASE_ADDR + JLC_CSR_INT_EN_OFFSET_ADDR)
#define JLC_CSR_INT_STAT_ADDR          (JLC_CSR_BASE_ADDR + JLC_CSR_INT_STAT_OFFSET_ADDR)
#define JLC_CSR_INT_CLR_ADDR           (JLC_CSR_BASE_ADDR + JLC_CSR_INT_CLR_OFFSET_ADDR)
#define JLC_CSR_START_ADDR             (JLC_CSR_BASE_ADDR + JLC_CSR_START_OFFSET_ADDR)
#define JLC_CSR_TRST_ADDR              (JLC_CSR_BASE_ADDR + JLC_CSR_TRST_OFFSET_ADDR)
#define JLC_CSR_TCK_IDLE_ADDR          (JLC_CSR_BASE_ADDR + JLC_CSR_TCK_IDLE_OFFSET_ADDR)
#define JLC_CSR_DW_ADDR                (JLC_CSR_BASE_ADDR + JLC_CSR_DW_OFFSET_ADDR)
#define JLC_CSR_SEN_ADDR               (JLC_CSR_BASE_ADDR + JLC_CSR_SEN_OFFSET_ADDR)
#define JLC_CSR_TDI2_DATA2_ADDR        (JLC_CSR_BASE_ADDR + JLC_CSR_TDI2_DATA2_OFFSET_ADDR)
#define JLC_CSR_TDO2_DATA2_ADDR        (JLC_CSR_BASE_ADDR + JLC_CSR_TDO2_DATA2_OFFSET_ADDR)
#define JLC_CSR_TDI2_SIZE2_ADDR        (JLC_CSR_BASE_ADDR + JLC_CSR_TDI2_SIZE2_OFFSET_ADDR)
#define JLC_CSR_DW_LEN_ADDR            (JLC_CSR_BASE_ADDR + JLC_CSR_DW_LEN_OFFSET_ADDR)
#define JLC_CSR_DW_CFG_ADDR            (JLC_CSR_BASE_ADDR + JLC_CSR_DW_CFG_OFFSET_ADDR)
#define JLC_CSR_DW2_CFG_ADDR           (JLC_CSR_BASE_ADDR + JLC_CSR_DW2_CFG_OFFSET_ADDR)
#define JLC_CSR_BUF2_LEVEL_ADDR        (JLC_CSR_BASE_ADDR + JLC_CSR_BUF2_LEVEL_OFFSET_ADDR)
#define JLC_CSR_DLY_EN_ADDR            (JLC_CSR_BASE_ADDR + JLC_CSR_DLY_EN_OFFSET_ADDR)
#define JLC_CSR_SAM_DLY_ADDR           (JLC_CSR_BASE_ADDR + JLC_CSR_SAM_DLY_OFFSET_ADDR)
#define JLC_CSR_VERSION_ADDR           (JLC_CSR_BASE_ADDR + JLC_CSR_VERSION_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_0_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_0_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_1_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_1_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_2_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_2_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_3_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_3_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_4_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_4_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_5_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_5_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_6_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_6_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_7_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_7_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_8_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_8_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_9_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_9_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_10_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_10_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_11_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_11_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_12_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_12_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_13_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_13_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_14_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_14_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_15_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_15_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_16_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_16_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_17_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_17_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_18_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_18_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_19_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_19_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_20_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_20_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_21_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_21_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_22_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_22_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_23_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_23_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_24_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_24_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_25_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_25_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_26_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_26_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_27_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_27_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_28_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_28_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_29_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_29_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_30_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_30_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_31_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_31_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_32_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_32_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_33_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_33_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_34_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_34_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_35_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_35_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_36_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_36_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_37_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_37_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_38_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_38_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_39_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_39_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_40_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_40_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_41_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_41_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_42_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_42_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_43_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_43_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_44_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_44_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_45_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_45_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_46_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_46_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_47_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_47_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_48_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_48_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_49_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_49_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_50_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_50_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_51_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_51_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_52_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_52_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_53_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_53_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_54_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_54_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_55_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_55_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_56_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_56_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_57_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_57_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_58_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_58_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_59_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_59_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_60_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_60_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_61_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_61_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_62_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_62_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_63_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_63_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_64_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_64_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_65_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_65_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_66_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_66_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_67_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_67_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_68_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_68_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_69_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_69_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_70_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_70_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_71_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_71_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_72_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_72_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_73_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_73_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_74_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_74_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_75_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_75_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_76_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_76_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_77_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_77_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_78_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_78_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_79_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_79_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_80_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_80_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_81_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_81_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_82_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_82_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_83_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_83_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_84_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_84_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_85_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_85_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_86_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_86_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_87_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_87_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_88_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_88_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_89_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_89_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_90_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_90_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_91_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_91_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_92_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_92_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_93_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_93_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_94_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_94_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_95_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_95_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_96_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_96_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_97_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_97_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_98_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_98_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_99_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_99_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_100_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_100_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_101_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_101_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_102_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_102_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_103_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_103_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_104_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_104_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_105_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_105_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_106_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_106_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_107_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_107_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_108_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_108_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_109_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_109_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_110_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_110_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_111_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_111_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_112_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_112_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_113_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_113_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_114_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_114_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_115_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_115_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_116_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_116_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_117_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_117_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_118_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_118_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_119_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_119_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_120_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_120_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_121_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_121_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_122_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_122_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_123_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_123_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_124_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_124_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_125_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_125_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_126_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_126_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF1_DATA_127_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF1_DATA_127_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_0_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_0_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_1_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_1_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_2_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_2_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_3_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_3_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_4_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_4_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_5_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_5_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_6_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_6_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_7_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_7_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_8_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_8_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_9_ADDR   (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_9_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_10_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_10_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_11_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_11_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_12_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_12_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_13_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_13_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_14_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_14_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_15_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_15_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_16_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_16_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_17_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_17_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_18_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_18_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_19_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_19_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_20_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_20_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_21_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_21_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_22_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_22_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_23_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_23_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_24_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_24_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_25_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_25_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_26_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_26_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_27_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_27_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_28_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_28_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_29_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_29_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_30_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_30_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_31_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_31_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_32_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_32_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_33_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_33_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_34_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_34_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_35_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_35_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_36_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_36_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_37_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_37_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_38_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_38_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_39_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_39_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_40_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_40_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_41_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_41_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_42_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_42_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_43_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_43_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_44_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_44_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_45_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_45_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_46_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_46_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_47_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_47_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_48_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_48_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_49_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_49_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_50_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_50_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_51_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_51_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_52_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_52_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_53_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_53_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_54_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_54_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_55_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_55_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_56_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_56_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_57_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_57_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_58_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_58_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_59_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_59_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_60_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_60_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_61_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_61_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_62_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_62_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_63_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_63_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_64_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_64_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_65_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_65_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_66_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_66_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_67_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_67_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_68_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_68_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_69_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_69_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_70_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_70_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_71_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_71_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_72_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_72_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_73_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_73_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_74_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_74_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_75_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_75_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_76_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_76_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_77_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_77_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_78_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_78_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_79_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_79_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_80_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_80_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_81_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_81_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_82_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_82_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_83_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_83_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_84_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_84_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_85_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_85_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_86_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_86_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_87_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_87_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_88_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_88_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_89_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_89_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_90_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_90_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_91_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_91_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_92_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_92_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_93_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_93_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_94_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_94_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_95_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_95_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_96_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_96_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_97_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_97_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_98_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_98_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_99_ADDR  (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_99_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_100_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_100_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_101_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_101_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_102_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_102_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_103_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_103_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_104_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_104_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_105_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_105_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_106_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_106_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_107_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_107_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_108_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_108_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_109_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_109_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_110_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_110_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_111_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_111_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_112_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_112_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_113_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_113_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_114_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_114_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_115_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_115_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_116_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_116_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_117_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_117_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_118_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_118_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_119_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_119_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_120_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_120_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_121_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_121_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_122_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_122_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_123_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_123_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_124_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_124_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_125_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_125_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_126_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_126_OFFSET_ADDR)
#define JLC_CSR_TDI_BUF2_DATA_127_ADDR (JLC_CSR_BASE_ADDR + JLC_CSR_TDI_BUF2_DATA_127_OFFSET_ADDR)

#endif
