// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __KCS_CSR_ADDR_DEFINE_H__
#define __KCS_CSR_ADDR_DEFINE_H__

#define KCS_CSR_BASE_ADDR              0x8722000
#define KCS_CSR_DATA_IN_OFFSET_ADDR    0x0
#define KCS_CSR_DATA_OUT_OFFSET_ADDR   0x4
#define KCS_CSR_COMMMAND_OFFSET_ADDR   0x8
#define KCS_CSR_STATUS_OFFSET_ADDR     0xC
#define KCS_CSR_BMC_INT_EN_OFFSET_ADDR 0x10

#define KCS_CSR_DATA_IN_ADDR    (KCS_CSR_BASE_ADDR + KCS_CSR_DATA_IN_OFFSET_ADDR)
#define KCS_CSR_DATA_OUT_ADDR   (KCS_CSR_BASE_ADDR + KCS_CSR_DATA_OUT_OFFSET_ADDR)
#define KCS_CSR_COMMMAND_ADDR   (KCS_CSR_BASE_ADDR + KCS_CSR_COMMMAND_OFFSET_ADDR)
#define KCS_CSR_STATUS_ADDR     (KCS_CSR_BASE_ADDR + KCS_CSR_STATUS_OFFSET_ADDR)
#define KCS_CSR_BMC_INT_EN_ADDR (KCS_CSR_BASE_ADDR + KCS_CSR_BMC_INT_EN_OFFSET_ADDR)

#endif
