// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __LOCAL_BUS_ADDR_DEFINE_H__
#define __LOCAL_BUS_ADDR_DEFINE_H__


#define    LB_BASE_ADDR                  0x8712000

/* offset address for Local_Bus registers */
#define LB_CS0_BASE_ADDR_OFFSET_ADDR     0x0
#define LB_CS1_BASE_ADDR_OFFSET_ADDR     0x4
#define LB_CS2_BASE_ADDR_OFFSET_ADDR     0x8
#define LB_CS3_BASE_ADDR_OFFSET_ADDR     0xC
#define LB_CS0_CTRL_OFFSET_ADDR          0x20
#define LB_CS1_CTRL_OFFSET_ADDR          0x24
#define LB_CS2_CTRL_OFFSET_ADDR          0x28
#define LB_CS3_CTRL_OFFSET_ADDR          0x2C
#define LB_CS0_T_SET0_OFFSET_ADDR        0x40
#define LB_CS0_T_SET1_OFFSET_ADDR        0x44
#define LB_CS0_T_SET2_OFFSET_ADDR        0x48
#define LB_CS1_T_SET0_OFFSET_ADDR        0x4C
#define LB_CS1_T_SET1_OFFSET_ADDR        0x50
#define LB_CS1_T_SET2_OFFSET_ADDR        0x54
#define LB_CS2_T_SET0_OFFSET_ADDR        0x58
#define LB_CS2_T_SET1_OFFSET_ADDR        0x5C
#define LB_CS2_T_SET2_OFFSET_ADDR        0x60
#define LB_CS3_T_SET0_OFFSET_ADDR        0x64
#define LB_CS3_T_SET1_OFFSET_ADDR        0x68
#define LB_CS3_T_SET2_OFFSET_ADDR        0x6C
#define LB_INTMSK_OFFSET_ADDR            0xA0
#define LB_INTSTS_OFFSET_ADDR            0xA4
#define LB_RINT_OFFSET_ADDR              0xA8
#define LB_RDY_TOUT_0_OFFSET_ADDR        0xAC
#define LB_RDY_TOUT_1_OFFSET_ADDR        0xB0
#define LB_RDY_TOUT_2_OFFSET_ADDR        0xB4
#define LB_RDY_TOUT_3_OFFSET_ADDR        0xB8
#define LB_CTRL_OFFSET_ADDR              0xCC
#define LB_PROT_ADDR_START_0_OFFSET_ADDR 0xD0
#define LB_PROT_ADDR_OVER_0_OFFSET_ADDR  0xD4
#define LB_PROT_ADDR_START_1_OFFSET_ADDR 0xD8
#define LB_PROT_ADDR_OVER_1_OFFSET_ADDR  0xDC
#define LB_PROT_ADDR_START_2_OFFSET_ADDR 0xE0
#define LB_PROT_ADDR_OVER_2_OFFSET_ADDR  0xE4
#define LB_PROT_ADDR_START_3_OFFSET_ADDR 0xE8
#define LB_PROT_ADDR_OVER_3_OFFSET_ADDR  0xEC
#define LB_PROT_ADDR_START_4_OFFSET_ADDR 0xF0
#define LB_PROT_ADDR_OVER_4_OFFSET_ADDR  0xF4
#define LB_PROT_ADDR_START_5_OFFSET_ADDR 0xF8
#define LB_PROT_ADDR_OVER_5_OFFSET_ADDR  0xFC
#define LB_PROT_ADDR_START_6_OFFSET_ADDR 0x100
#define LB_PROT_ADDR_OVER_6_OFFSET_ADDR  0x104
#define LB_PROT_ADDR_START_7_OFFSET_ADDR 0x108
#define LB_PROT_ADDR_OVER_7_OFFSET_ADDR  0x10C
#define LB_NOR_CMD0_ADDR_OFFSET_ADDR     0x110
#define LB_NOR_CMD0_MASK_OFFSET_ADDR     0x114
#define LB_NOR_CMD1_ADDR_OFFSET_ADDR     0x118
#define LB_NOR_CMD1_MASK_OFFSET_ADDR     0x11C
#define LB_NOR_CMD2_ADDR_OFFSET_ADDR     0x120
#define LB_NOR_CMD2_MASK_OFFSET_ADDR     0x124
#define LB_NOR_CMD3_ADDR_OFFSET_ADDR     0x128
#define LB_NOR_CMD3_MASK_OFFSET_ADDR     0x12C
#define LB_HL_PROT_KEY0_OFFSET_ADDR      0x130
#define LB_HL_PROT_KEY1_OFFSET_ADDR      0x134
#define LB_HL_PROT_KEY2_OFFSET_ADDR      0x138
#define LB_HL_PROT_KEY3_OFFSET_ADDR      0x13C
#define LB_DBG_ST0_OFFSET_ADDR           0x140
#define LB_DBG_OVER_TIME_ADDR_OFFSET_ADDR   0x144
#define LB_DBG_T_CFG_OFFSET_ADDR         0x148
#define LB_CF_CARD_ST_OFFSET_ADDR        0x150
#define LB_CFG_T_UPDATE_EN_OFFSET_ADDR   0x154
#define LB_WP_RSP_ERR_EN_OFFSET_ADDR     0x158

#define LB_CS0_BASE_ADDR_ADDR     (LB_BASE_ADDR + LB_CS0_BASE_ADDR_OFFSET_ADDR)
#define LB_CS1_BASE_ADDR_ADDR     (LB_BASE_ADDR + LB_CS1_BASE_ADDR_OFFSET_ADDR)
#define LB_CS2_BASE_ADDR_ADDR     (LB_BASE_ADDR + LB_CS2_BASE_ADDR_OFFSET_ADDR)
#define LB_CS3_BASE_ADDR_ADDR     (LB_BASE_ADDR + LB_CS3_BASE_ADDR_OFFSET_ADDR)
#define LB_CS0_CTRL_ADDR          (LB_BASE_ADDR + LB_CS0_CTRL_OFFSET_ADDR)
#define LB_CS1_CTRL_ADDR          (LB_BASE_ADDR + LB_CS1_CTRL_OFFSET_ADDR)
#define LB_CS2_CTRL_ADDR          (LB_BASE_ADDR + LB_CS2_CTRL_OFFSET_ADDR)
#define LB_CS3_CTRL_ADDR          (LB_BASE_ADDR + LB_CS3_CTRL_OFFSET_ADDR)
#define LB_CS0_T_SET0_ADDR        (LB_BASE_ADDR + LB_CS0_T_SET0_OFFSET_ADDR)
#define LB_CS0_T_SET1_ADDR        (LB_BASE_ADDR + LB_CS0_T_SET1_OFFSET_ADDR)
#define LB_CS0_T_SET2_ADDR        (LB_BASE_ADDR + LB_CS0_T_SET2_OFFSET_ADDR)
#define LB_CS1_T_SET0_ADDR        (LB_BASE_ADDR + LB_CS1_T_SET0_OFFSET_ADDR)
#define LB_CS1_T_SET1_ADDR        (LB_BASE_ADDR + LB_CS1_T_SET1_OFFSET_ADDR)
#define LB_CS1_T_SET2_ADDR        (LB_BASE_ADDR + LB_CS1_T_SET2_OFFSET_ADDR)
#define LB_CS2_T_SET0_ADDR        (LB_BASE_ADDR + LB_CS2_T_SET0_OFFSET_ADDR)
#define LB_CS2_T_SET1_ADDR        (LB_BASE_ADDR + LB_CS2_T_SET1_OFFSET_ADDR)
#define LB_CS2_T_SET2_ADDR        (LB_BASE_ADDR + LB_CS2_T_SET2_OFFSET_ADDR)
#define LB_CS3_T_SET0_ADDR        (LB_BASE_ADDR + LB_CS3_T_SET0_OFFSET_ADDR)
#define LB_CS3_T_SET1_ADDR        (LB_BASE_ADDR + LB_CS3_T_SET1_OFFSET_ADDR)
#define LB_CS3_T_SET2_ADDR        (LB_BASE_ADDR + LB_CS3_T_SET2_OFFSET_ADDR)
#define LB_INTMSK_ADDR            (LB_BASE_ADDR + LB_INTMSK_OFFSET_ADDR)
#define LB_INTSTS_ADDR            (LB_BASE_ADDR + LB_INTSTS_OFFSET_ADDR)
#define LB_RINT_ADDR              (LB_BASE_ADDR + LB_RINT_OFFSET_ADDR)
#define LB_RDY_TOUT_0_ADDR        (LB_BASE_ADDR + LB_RDY_TOUT_0_OFFSET_ADDR)
#define LB_RDY_TOUT_1_ADDR        (LB_BASE_ADDR + LB_RDY_TOUT_1_OFFSET_ADDR)
#define LB_RDY_TOUT_2_ADDR        (LB_BASE_ADDR + LB_RDY_TOUT_2_OFFSET_ADDR)
#define LB_RDY_TOUT_3_ADDR        (LB_BASE_ADDR + LB_RDY_TOUT_3_OFFSET_ADDR)
#define LB_CTRL_ADDR              (LB_BASE_ADDR + LB_CTRL_OFFSET_ADDR)
#define LB_PROT_ADDR_START_0_ADDR (LB_BASE_ADDR + LB_PROT_ADDR_START_0_OFFSET_ADDR)
#define LB_PROT_ADDR_OVER_0_ADDR  (LB_BASE_ADDR + LB_PROT_ADDR_OVER_0_OFFSET_ADDR)
#define LB_PROT_ADDR_START_1_ADDR (LB_BASE_ADDR + LB_PROT_ADDR_START_1_OFFSET_ADDR)
#define LB_PROT_ADDR_OVER_1_ADDR  (LB_BASE_ADDR + LB_PROT_ADDR_OVER_1_OFFSET_ADDR)
#define LB_PROT_ADDR_START_2_ADDR (LB_BASE_ADDR + LB_PROT_ADDR_START_2_OFFSET_ADDR)
#define LB_PROT_ADDR_OVER_2_ADDR  (LB_BASE_ADDR + LB_PROT_ADDR_OVER_2_OFFSET_ADDR)
#define LB_PROT_ADDR_START_3_ADDR (LB_BASE_ADDR + LB_PROT_ADDR_START_3_OFFSET_ADDR)
#define LB_PROT_ADDR_OVER_3_ADDR  (LB_BASE_ADDR + LB_PROT_ADDR_OVER_3_OFFSET_ADDR)
#define LB_PROT_ADDR_START_4_ADDR (LB_BASE_ADDR + LB_PROT_ADDR_START_4_OFFSET_ADDR)
#define LB_PROT_ADDR_OVER_4_ADDR  (LB_BASE_ADDR + LB_PROT_ADDR_OVER_4_OFFSET_ADDR)
#define LB_PROT_ADDR_START_5_ADDR (LB_BASE_ADDR + LB_PROT_ADDR_START_5_OFFSET_ADDR)
#define LB_PROT_ADDR_OVER_5_ADDR  (LB_BASE_ADDR + LB_PROT_ADDR_OVER_5_OFFSET_ADDR)
#define LB_PROT_ADDR_START_6_ADDR (LB_BASE_ADDR + LB_PROT_ADDR_START_6_OFFSET_ADDR)
#define LB_PROT_ADDR_OVER_6_ADDR  (LB_BASE_ADDR + LB_PROT_ADDR_OVER_6_OFFSET_ADDR)
#define LB_PROT_ADDR_START_7_ADDR (LB_BASE_ADDR + LB_PROT_ADDR_START_7_OFFSET_ADDR)
#define LB_PROT_ADDR_OVER_7_ADDR  (LB_BASE_ADDR + LB_PROT_ADDR_OVER_7_OFFSET_ADDR)
#define LB_NOR_CMD0_ADDR_ADDR     (LB_BASE_ADDR + LB_NOR_CMD0_ADDR_OFFSET_ADDR)
#define LB_NOR_CMD0_MASK_ADDR     (LB_BASE_ADDR + LB_NOR_CMD0_MASK_OFFSET_ADDR)
#define LB_NOR_CMD1_ADDR_ADDR     (LB_BASE_ADDR + LB_NOR_CMD1_ADDR_OFFSET_ADDR)
#define LB_NOR_CMD1_MASK_ADDR     (LB_BASE_ADDR + LB_NOR_CMD1_MASK_OFFSET_ADDR)
#define LB_NOR_CMD2_ADDR_ADDR     (LB_BASE_ADDR + LB_NOR_CMD2_ADDR_OFFSET_ADDR)
#define LB_NOR_CMD2_MASK_ADDR     (LB_BASE_ADDR + LB_NOR_CMD2_MASK_OFFSET_ADDR)
#define LB_NOR_CMD3_ADDR_ADDR     (LB_BASE_ADDR + LB_NOR_CMD3_ADDR_OFFSET_ADDR)
#define LB_NOR_CMD3_MASK_ADDR     (LB_BASE_ADDR + LB_NOR_CMD3_MASK_OFFSET_ADDR)
#define LB_HL_PROT_KEY0_ADDR      (LB_BASE_ADDR + LB_HL_PROT_KEY0_OFFSET_ADDR)
#define LB_HL_PROT_KEY1_ADDR      (LB_BASE_ADDR + LB_HL_PROT_KEY1_OFFSET_ADDR)
#define LB_HL_PROT_KEY2_ADDR      (LB_BASE_ADDR + LB_HL_PROT_KEY2_OFFSET_ADDR)
#define LB_HL_PROT_KEY3_ADDR      (LB_BASE_ADDR + LB_HL_PROT_KEY3_OFFSET_ADDR)
#define LB_DBG_ST0_ADDR           (LB_BASE_ADDR + LB_DBG_ST0_OFFSET_ADDR)
#define LB_DBG_OVER_TIME_ADDR_ADDR   (LB_BASE_ADDR + LB_DBG_OVER_TIME_ADDR_OFFSET_ADDR)
#define LB_DBG_T_CFG_ADDR         (LB_BASE_ADDR + LB_DBG_T_CFG_OFFSET_ADDR)
#define LB_CF_CARD_ST_ADDR        (LB_BASE_ADDR + LB_CF_CARD_ST_OFFSET_ADDR)
#define LB_CFG_T_UPDATE_EN_ADDR   (LB_BASE_ADDR + LB_CFG_T_UPDATE_EN_OFFSET_ADDR)
#define LB_WP_RSP_ERR_EN_ADDR     (LB_BASE_ADDR + LB_WP_RSP_ERR_EN_OFFSET_ADDR)

#endif /* __LOCAL_BUS_ADDR_DEFINE_H__ */
