// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __PCU_CSR_ADDR_DEFINE_H__
#define __PCU_CSR_ADDR_DEFINE_H__

#define    PCU_CSR_BASE_ADDR                    0xcd00000

#define PCU_CSR_CF_TX_FIFO_THRSLD_OFFSET_ADDR  0x420
#define PCU_CSR_CF_RX_FIFO_THRSLD_OFFSET_ADDR  0x424
#define PCU_CSR_CF_CFG_FIFO_THRSLD_OFFSET_ADDR 0x428
#define PCU_CSR_CF_INTRPT_MSK_OFFSET_ADDR      0x42C
#define PCU_CSR_CF_INTRPT_STAT_OFFSET_ADDR     0x434
#define PCU_CSR_CF_INTRPT_CLR_OFFSET_ADDR      0x438
#define PCU_CSR_TX_BUS_ERR_ADDR_OFFSET_ADDR    0x43C
#define PCU_CSR_RX_BUS_ERR_ADDR_OFFSET_ADDR    0x440
#define PCU_CSR_MAX_FRAME_LEN_OFFSET_ADDR      0x444
#define PCU_CSR_TX_DROP_CNT_OFFSET_ADDR        0x448
#define PCU_CSR_RX_OVER_FLOW_CNT_OFFSET_ADDR   0x44C
#define PCU_CSR_DEBUG_ST_MCH_OFFSET_ADDR       0x450
#define PCU_CSR_FIFO_CURR_STATUS_OFFSET_ADDR   0x454
#define PCU_CSR_FIFO_HIS_STATUS_OFFSET_ADDR    0x458
#define PCU_CSR_CF_CFF_DATA_NUM_OFFSET_ADDR    0x45C
#define PCU_CSR_TX_CS_FAIL_CNT_OFFSET_ADDR     0x460
#define PCU_CSR_RX_TRANS_PKG_CNT_OFFSET_ADDR   0x464
#define PCU_CSR_TX_TRANS_PKG_CNT_OFFSET_ADDR   0x468
#define PCU_CSR_CF_TX_PAUSE_OFFSET_ADDR        0x470
#define PCU_CSR_TX_CFF_ADDR_0_OFFSET_ADDR      0x488
#define PCU_CSR_TX_CFF_ADDR_1_OFFSET_ADDR      0x48C
#define PCU_CSR_TX_CFF_ADDR_2_OFFSET_ADDR      0x490
#define PCU_CSR_TX_CFF_ADDR_3_OFFSET_ADDR      0x494
#define PCU_CSR_RX_CFF_ADDR_OFFSET_ADDR        0x4A0
#define PCU_CSR_WE_ADDR_OFFSET_ADDR            0x4E0
#define PCU_CSR_RX_BUF_SIZE_OFFSET_ADDR        0x4E4
#define PCU_CSR_BUS_CTRL_OFFSET_ADDR           0x4E8
#define PCU_CSR_RX_BUF_REQ_ADDR_OFFSET_ADDR    0x4EC
#define PCU_CSR_RX_CTRL_OFFSET_ADDR            0x4F0
#define PCU_CSR_RX_PKT_MODE_OFFSET_ADDR        0x4F4
#define PCU_CSR_QOS_MODE_OFFSET_ADDR           0x4F8
#define PCU_CSR_VLAN_QOS_OFFSET_ADDR           0x4FC
#define PCU_CSR_IP_QOS_0_OFFSET_ADDR           0x500
#define PCU_CSR_IP_QOS_1_OFFSET_ADDR           0x504
#define PCU_CSR_IP_QOS_2_OFFSET_ADDR           0x508
#define PCU_CSR_IP_QOS_3_OFFSET_ADDR           0x50C
#define PCU_CSR_IP_QOS_4_OFFSET_ADDR           0x510
#define PCU_CSR_IP_QOS_5_OFFSET_ADDR           0x514
#define PCU_CSR_IP_QOS_6_OFFSET_ADDR           0x518
#define PCU_CSR_IP_QOS_7_OFFSET_ADDR           0x51C
#define PCU_CSR_GRP_MODE_0_OFFSET_ADDR         0x520
#define PCU_CSR_GRP_MODE_1_OFFSET_ADDR         0x524
#define PCU_CSR_TT_MODE_OFFSET_ADDR            0x528
#define PCU_CSR_TAG_MODE_OFFSET_ADDR           0x52C
#define PCU_CSR_TAG_MASK_0_OFFSET_ADDR         0x530
#define PCU_CSR_TAG_MASK_1_OFFSET_ADDR         0x534
#define PCU_CSR_MATCH_MASK_0_OFFSET_ADDR       0x538
#define PCU_CSR_MATCH_TBL_0_OFFSET_ADDR        0x540
#define PCU_CSR_MATCH_TBL_1_OFFSET_ADDR        0x544
#define PCU_CSR_MATCH_TBL_2_OFFSET_ADDR        0x548
#define PCU_CSR_MATCH_TBL_3_OFFSET_ADDR        0x54C
#define PCU_CSR_MATCH_TBL_4_OFFSET_ADDR        0x550
#define PCU_CSR_MATCH_TBL_5_OFFSET_ADDR        0x554
#define PCU_CSR_MATCH_TBL_6_OFFSET_ADDR        0x558
#define PCU_CSR_MATCH_TBL_7_OFFSET_ADDR        0x55C
#define PCU_CSR_RXBUF_REQ_TIMER_OFFSET_ADDR    0x580
#define PCU_CSR_RX_WE_TIMER_OFFSET_ADDR        0x584
#define PCU_CSR_TX_REL_TIMER_OFFSET_ADDR       0x588
#define PCU_CSR_RX_BUFRQ_ERR_CNT_OFFSET_ADDR   0x58C
#define PCU_CSR_TX_BUFRL_ERR_CNT_OFFSET_ADDR   0x590
#define PCU_CSR_RX_WE_ERR_CNT_OFFSET_ADDR      0x594
#define PCU_CSR_RX_GRP_TBL_0_OFFSET_ADDR       0x598
#define PCU_CSR_RX_GRP_TBL_1_OFFSET_ADDR       0x59C
#define PCU_CSR_RX_GRP_TBL_2_OFFSET_ADDR       0x5A0
#define PCU_CSR_RX_GRP_TBL_3_OFFSET_ADDR       0x5A4
#define PCU_CSR_RX_GRP_TBL_4_OFFSET_ADDR       0x5A8
#define PCU_CSR_RX_GRP_TBL_5_OFFSET_ADDR       0x5AC
#define PCU_CSR_RX_GRP_TBL_6_OFFSET_ADDR       0x5B0
#define PCU_CSR_RX_GRP_TBL_7_OFFSET_ADDR       0x5B4
#define PCU_CSR_RX_GRP_RES_OFFSET_ADDR         0x5B8
#define PCU_CSR_RX_GRP_MSK_OFFSET_ADDR         0x5BC
#define PCU_CSR_ADDR_FILT_S0_OFFSET_ADDR       0x5C0
#define PCU_CSR_ADDR_FILT_E0_OFFSET_ADDR       0x5C4
#define PCU_CSR_ADDR_FILT_S1_OFFSET_ADDR       0x5C8
#define PCU_CSR_ADDR_FILT_E1_OFFSET_ADDR       0x5CC
#define PCU_CSR_ADDR_FILT_S2_OFFSET_ADDR       0x5D0
#define PCU_CSR_ADDR_FILT_E2_OFFSET_ADDR       0x5D4
#define PCU_CSR_ADDR_FILT_S3_OFFSET_ADDR       0x5D8
#define PCU_CSR_ADDR_FILT_E3_OFFSET_ADDR       0x5DC
#define PCU_CSR_IDLE_CNT_OFFSET_ADDR           0x5E0
#define PCU_CSR_DBG_ST0_OFFSET_ADDR            0x5E4
#define PCU_CSR_DBG_ST1_OFFSET_ADDR            0x5E8
#define PCU_CSR_DBG_ST2_OFFSET_ADDR            0x5EC
#define PCU_CSR_BUS_RST_EN_OFFSET_ADDR         0x688

#define PCU_CSR_CF_TX_FIFO_THRSLD_ADDR  (PCU_CSR_BASE_ADDR + PCU_CSR_CF_TX_FIFO_THRSLD_OFFSET_ADDR)
#define PCU_CSR_CF_RX_FIFO_THRSLD_ADDR  (PCU_CSR_BASE_ADDR + PCU_CSR_CF_RX_FIFO_THRSLD_OFFSET_ADDR)
#define PCU_CSR_CF_CFG_FIFO_THRSLD_ADDR (PCU_CSR_BASE_ADDR + PCU_CSR_CF_CFG_FIFO_THRSLD_OFFSET_ADDR)
#define PCU_CSR_CF_INTRPT_MSK_ADDR      (PCU_CSR_BASE_ADDR + PCU_CSR_CF_INTRPT_MSK_OFFSET_ADDR)
#define PCU_CSR_CF_INTRPT_STAT_ADDR     (PCU_CSR_BASE_ADDR + PCU_CSR_CF_INTRPT_STAT_OFFSET_ADDR)
#define PCU_CSR_CF_INTRPT_CLR_ADDR      (PCU_CSR_BASE_ADDR + PCU_CSR_CF_INTRPT_CLR_OFFSET_ADDR)
#define PCU_CSR_TX_BUS_ERR_ADDR_ADDR    (PCU_CSR_BASE_ADDR + PCU_CSR_TX_BUS_ERR_ADDR_OFFSET_ADDR)
#define PCU_CSR_RX_BUS_ERR_ADDR_ADDR    (PCU_CSR_BASE_ADDR + PCU_CSR_RX_BUS_ERR_ADDR_OFFSET_ADDR)
#define PCU_CSR_MAX_FRAME_LEN_ADDR      (PCU_CSR_BASE_ADDR + PCU_CSR_MAX_FRAME_LEN_OFFSET_ADDR)
#define PCU_CSR_TX_DROP_CNT_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_TX_DROP_CNT_OFFSET_ADDR)
#define PCU_CSR_RX_OVER_FLOW_CNT_ADDR   (PCU_CSR_BASE_ADDR + PCU_CSR_RX_OVER_FLOW_CNT_OFFSET_ADDR)
#define PCU_CSR_DEBUG_ST_MCH_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_DEBUG_ST_MCH_OFFSET_ADDR)
#define PCU_CSR_FIFO_CURR_STATUS_ADDR   (PCU_CSR_BASE_ADDR + PCU_CSR_FIFO_CURR_STATUS_OFFSET_ADDR)
#define PCU_CSR_FIFO_HIS_STATUS_ADDR    (PCU_CSR_BASE_ADDR + PCU_CSR_FIFO_HIS_STATUS_OFFSET_ADDR)
#define PCU_CSR_CF_CFF_DATA_NUM_ADDR    (PCU_CSR_BASE_ADDR + PCU_CSR_CF_CFF_DATA_NUM_OFFSET_ADDR)
#define PCU_CSR_TX_CS_FAIL_CNT_ADDR     (PCU_CSR_BASE_ADDR + PCU_CSR_TX_CS_FAIL_CNT_OFFSET_ADDR)
#define PCU_CSR_RX_TRANS_PKG_CNT_ADDR   (PCU_CSR_BASE_ADDR + PCU_CSR_RX_TRANS_PKG_CNT_OFFSET_ADDR)
#define PCU_CSR_TX_TRANS_PKG_CNT_ADDR   (PCU_CSR_BASE_ADDR + PCU_CSR_TX_TRANS_PKG_CNT_OFFSET_ADDR)
#define PCU_CSR_CF_TX_PAUSE_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_CF_TX_PAUSE_OFFSET_ADDR)
#define PCU_CSR_TX_CFF_ADDR_0_ADDR      (PCU_CSR_BASE_ADDR + PCU_CSR_TX_CFF_ADDR_0_OFFSET_ADDR)
#define PCU_CSR_TX_CFF_ADDR_1_ADDR      (PCU_CSR_BASE_ADDR + PCU_CSR_TX_CFF_ADDR_1_OFFSET_ADDR)
#define PCU_CSR_TX_CFF_ADDR_2_ADDR      (PCU_CSR_BASE_ADDR + PCU_CSR_TX_CFF_ADDR_2_OFFSET_ADDR)
#define PCU_CSR_TX_CFF_ADDR_3_ADDR      (PCU_CSR_BASE_ADDR + PCU_CSR_TX_CFF_ADDR_3_OFFSET_ADDR)
#define PCU_CSR_RX_CFF_ADDR_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_RX_CFF_ADDR_OFFSET_ADDR)
#define PCU_CSR_WE_ADDR_ADDR            (PCU_CSR_BASE_ADDR + PCU_CSR_WE_ADDR_OFFSET_ADDR)
#define PCU_CSR_RX_BUF_SIZE_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_RX_BUF_SIZE_OFFSET_ADDR)
#define PCU_CSR_BUS_CTRL_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_BUS_CTRL_OFFSET_ADDR)
#define PCU_CSR_RX_BUF_REQ_ADDR_ADDR    (PCU_CSR_BASE_ADDR + PCU_CSR_RX_BUF_REQ_ADDR_OFFSET_ADDR)
#define PCU_CSR_RX_CTRL_ADDR            (PCU_CSR_BASE_ADDR + PCU_CSR_RX_CTRL_OFFSET_ADDR)
#define PCU_CSR_RX_PKT_MODE_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_RX_PKT_MODE_OFFSET_ADDR)
#define PCU_CSR_QOS_MODE_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_QOS_MODE_OFFSET_ADDR)
#define PCU_CSR_VLAN_QOS_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_VLAN_QOS_OFFSET_ADDR)
#define PCU_CSR_IP_QOS_0_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_IP_QOS_0_OFFSET_ADDR)
#define PCU_CSR_IP_QOS_1_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_IP_QOS_1_OFFSET_ADDR)
#define PCU_CSR_IP_QOS_2_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_IP_QOS_2_OFFSET_ADDR)
#define PCU_CSR_IP_QOS_3_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_IP_QOS_3_OFFSET_ADDR)
#define PCU_CSR_IP_QOS_4_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_IP_QOS_4_OFFSET_ADDR)
#define PCU_CSR_IP_QOS_5_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_IP_QOS_5_OFFSET_ADDR)
#define PCU_CSR_IP_QOS_6_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_IP_QOS_6_OFFSET_ADDR)
#define PCU_CSR_IP_QOS_7_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_IP_QOS_7_OFFSET_ADDR)
#define PCU_CSR_GRP_MODE_0_ADDR         (PCU_CSR_BASE_ADDR + PCU_CSR_GRP_MODE_0_OFFSET_ADDR)
#define PCU_CSR_GRP_MODE_1_ADDR         (PCU_CSR_BASE_ADDR + PCU_CSR_GRP_MODE_1_OFFSET_ADDR)
#define PCU_CSR_TT_MODE_ADDR            (PCU_CSR_BASE_ADDR + PCU_CSR_TT_MODE_OFFSET_ADDR)
#define PCU_CSR_TAG_MODE_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_TAG_MODE_OFFSET_ADDR)
#define PCU_CSR_TAG_MASK_0_ADDR         (PCU_CSR_BASE_ADDR + PCU_CSR_TAG_MASK_0_OFFSET_ADDR)
#define PCU_CSR_TAG_MASK_1_ADDR         (PCU_CSR_BASE_ADDR + PCU_CSR_TAG_MASK_1_OFFSET_ADDR)
#define PCU_CSR_MATCH_MASK_0_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_MATCH_MASK_0_OFFSET_ADDR)
#define PCU_CSR_MATCH_TBL_0_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_MATCH_TBL_0_OFFSET_ADDR)
#define PCU_CSR_MATCH_TBL_1_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_MATCH_TBL_1_OFFSET_ADDR)
#define PCU_CSR_MATCH_TBL_2_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_MATCH_TBL_2_OFFSET_ADDR)
#define PCU_CSR_MATCH_TBL_3_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_MATCH_TBL_3_OFFSET_ADDR)
#define PCU_CSR_MATCH_TBL_4_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_MATCH_TBL_4_OFFSET_ADDR)
#define PCU_CSR_MATCH_TBL_5_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_MATCH_TBL_5_OFFSET_ADDR)
#define PCU_CSR_MATCH_TBL_6_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_MATCH_TBL_6_OFFSET_ADDR)
#define PCU_CSR_MATCH_TBL_7_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_MATCH_TBL_7_OFFSET_ADDR)
#define PCU_CSR_RXBUF_REQ_TIMER_ADDR    (PCU_CSR_BASE_ADDR + PCU_CSR_RXBUF_REQ_TIMER_OFFSET_ADDR)
#define PCU_CSR_RX_WE_TIMER_ADDR        (PCU_CSR_BASE_ADDR + PCU_CSR_RX_WE_TIMER_OFFSET_ADDR)
#define PCU_CSR_TX_REL_TIMER_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_TX_REL_TIMER_OFFSET_ADDR)
#define PCU_CSR_RX_BUFRQ_ERR_CNT_ADDR   (PCU_CSR_BASE_ADDR + PCU_CSR_RX_BUFRQ_ERR_CNT_OFFSET_ADDR)
#define PCU_CSR_TX_BUFRL_ERR_CNT_ADDR   (PCU_CSR_BASE_ADDR + PCU_CSR_TX_BUFRL_ERR_CNT_OFFSET_ADDR)
#define PCU_CSR_RX_WE_ERR_CNT_ADDR      (PCU_CSR_BASE_ADDR + PCU_CSR_RX_WE_ERR_CNT_OFFSET_ADDR)
#define PCU_CSR_RX_GRP_TBL_0_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_RX_GRP_TBL_0_OFFSET_ADDR)
#define PCU_CSR_RX_GRP_TBL_1_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_RX_GRP_TBL_1_OFFSET_ADDR)
#define PCU_CSR_RX_GRP_TBL_2_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_RX_GRP_TBL_2_OFFSET_ADDR)
#define PCU_CSR_RX_GRP_TBL_3_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_RX_GRP_TBL_3_OFFSET_ADDR)
#define PCU_CSR_RX_GRP_TBL_4_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_RX_GRP_TBL_4_OFFSET_ADDR)
#define PCU_CSR_RX_GRP_TBL_5_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_RX_GRP_TBL_5_OFFSET_ADDR)
#define PCU_CSR_RX_GRP_TBL_6_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_RX_GRP_TBL_6_OFFSET_ADDR)
#define PCU_CSR_RX_GRP_TBL_7_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_RX_GRP_TBL_7_OFFSET_ADDR)
#define PCU_CSR_RX_GRP_RES_ADDR         (PCU_CSR_BASE_ADDR + PCU_CSR_RX_GRP_RES_OFFSET_ADDR)
#define PCU_CSR_RX_GRP_MSK_ADDR         (PCU_CSR_BASE_ADDR + PCU_CSR_RX_GRP_MSK_OFFSET_ADDR)
#define PCU_CSR_ADDR_FILT_S0_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_ADDR_FILT_S0_OFFSET_ADDR)
#define PCU_CSR_ADDR_FILT_E0_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_ADDR_FILT_E0_OFFSET_ADDR)
#define PCU_CSR_ADDR_FILT_S1_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_ADDR_FILT_S1_OFFSET_ADDR)
#define PCU_CSR_ADDR_FILT_E1_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_ADDR_FILT_E1_OFFSET_ADDR)
#define PCU_CSR_ADDR_FILT_S2_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_ADDR_FILT_S2_OFFSET_ADDR)
#define PCU_CSR_ADDR_FILT_E2_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_ADDR_FILT_E2_OFFSET_ADDR)
#define PCU_CSR_ADDR_FILT_S3_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_ADDR_FILT_S3_OFFSET_ADDR)
#define PCU_CSR_ADDR_FILT_E3_ADDR       (PCU_CSR_BASE_ADDR + PCU_CSR_ADDR_FILT_E3_OFFSET_ADDR)
#define PCU_CSR_IDLE_CNT_ADDR           (PCU_CSR_BASE_ADDR + PCU_CSR_IDLE_CNT_OFFSET_ADDR)
#define PCU_CSR_DBG_ST0_ADDR            (PCU_CSR_BASE_ADDR + PCU_CSR_DBG_ST0_OFFSET_ADDR)
#define PCU_CSR_DBG_ST1_ADDR            (PCU_CSR_BASE_ADDR + PCU_CSR_DBG_ST1_OFFSET_ADDR)
#define PCU_CSR_DBG_ST2_ADDR            (PCU_CSR_BASE_ADDR + PCU_CSR_DBG_ST2_OFFSET_ADDR)
#define PCU_CSR_BUS_RST_EN_ADDR         (PCU_CSR_BASE_ADDR + PCU_CSR_BUS_RST_EN_OFFSET_ADDR)

#endif // __PCU_CSR_ADDR_DEFINE_H__
