// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __PECI_CSR_ADDR_DEFINE_H__
#define __PECI_CSR_ADDR_DEFINE_H__

#define    PECI_CSR_BASE_ADDR                   0x8746000

/* offset address for PECI_CSR registers */
#define PECI_CSR_CTRL_OFFSET_ADDR               0x0
#define PECI_CSR_WR_LENGTH_OFFSET_ADDR          0x4
#define PECI_CSR_RD_LENGTH_OFFSET_ADDR          0x8
#define PECI_CSR_HOST_SPEED_OFFSET_ADDR         0xC
#define PECI_CSR_INT_EN_OFFSET_ADDR             0x10
#define PECI_CSR_NEGO_SPEED_OFFSET_ADDR         0x14
#define PECI_CSR_WR_DAT0_OFFSET_ADDR            0x70
#define PECI_CSR_WR_DAT1_OFFSET_ADDR            0x74
#define PECI_CSR_WR_DAT2_OFFSET_ADDR            0x78
#define PECI_CSR_WR_DAT3_OFFSET_ADDR            0x7C
#define PECI_CSR_WR_DAT4_OFFSET_ADDR            0x80
#define PECI_CSR_WR_DAT5_OFFSET_ADDR            0x84
#define PECI_CSR_WR_DAT6_OFFSET_ADDR            0x88
#define PECI_CSR_WR_DAT7_OFFSET_ADDR            0x8C
#define PECI_CSR_RD_DAT0_OFFSET_ADDR            0xB0
#define PECI_CSR_RD_DAT1_OFFSET_ADDR            0xB4
#define PECI_CSR_RD_DAT2_OFFSET_ADDR            0xB8
#define PECI_CSR_RD_DAT3_OFFSET_ADDR            0xBC
#define PECI_CSR_RD_DAT4_OFFSET_ADDR            0xC0
#define PECI_CSR_RD_DAT5_OFFSET_ADDR            0xC4
#define PECI_CSR_RD_DAT6_OFFSET_ADDR            0xC8
#define PECI_CSR_RD_DAT7_OFFSET_ADDR            0xCC
#define PECI_CSR_ST_OFFSET_ADDR                 0x20
#define PECI_CSR_ST2_OFFSET_ADDR                0x24

#define PECI_CSR_CTRL_ADDR                      (PECI_CSR_BASE_ADDR + PECI_CSR_CTRL_OFFSET_ADDR)
#define PECI_CSR_WR_LENGTH_ADDR                 (PECI_CSR_BASE_ADDR + PECI_CSR_WR_LENGTH_OFFSET_ADDR)
#define PECI_CSR_RD_LENGTH_ADDR                 (PECI_CSR_BASE_ADDR + PECI_CSR_RD_LENGTH_OFFSET_ADDR)
#define PECI_CSR_HOST_SPEED_ADDR                (PECI_CSR_BASE_ADDR + PECI_CSR_HOST_SPEED_OFFSET_ADDR)
#define PECI_CSR_INT_EN_ADDR                    (PECI_CSR_BASE_ADDR + PECI_CSR_INT_EN_OFFSET_ADDR)
#define PECI_CSR_NEGO_SPEED_ADDR                (PECI_CSR_BASE_ADDR + PECI_CSR_NEGO_SPEED_OFFSET_ADDR)
#define PECI_CSR_WR_DAT0_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_WR_DAT0_OFFSET_ADDR)
#define PECI_CSR_WR_DAT1_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_WR_DAT1_OFFSET_ADDR)
#define PECI_CSR_WR_DAT2_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_WR_DAT2_OFFSET_ADDR)
#define PECI_CSR_WR_DAT3_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_WR_DAT3_OFFSET_ADDR)
#define PECI_CSR_WR_DAT4_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_WR_DAT4_OFFSET_ADDR)
#define PECI_CSR_WR_DAT5_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_WR_DAT5_OFFSET_ADDR)
#define PECI_CSR_WR_DAT6_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_WR_DAT6_OFFSET_ADDR)
#define PECI_CSR_WR_DAT7_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_WR_DAT7_OFFSET_ADDR)
#define PECI_CSR_RD_DAT0_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_RD_DAT0_OFFSET_ADDR)
#define PECI_CSR_RD_DAT1_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_RD_DAT1_OFFSET_ADDR)
#define PECI_CSR_RD_DAT2_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_RD_DAT2_OFFSET_ADDR)
#define PECI_CSR_RD_DAT3_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_RD_DAT3_OFFSET_ADDR)
#define PECI_CSR_RD_DAT4_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_RD_DAT4_OFFSET_ADDR)
#define PECI_CSR_RD_DAT5_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_RD_DAT5_OFFSET_ADDR)
#define PECI_CSR_RD_DAT6_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_RD_DAT6_OFFSET_ADDR)
#define PECI_CSR_RD_DAT7_ADDR                   (PECI_CSR_BASE_ADDR + PECI_CSR_RD_DAT7_OFFSET_ADDR)
#define PECI_CSR_ST_ADDR                        (PECI_CSR_BASE_ADDR + PECI_CSR_ST_OFFSET_ADDR)
#define PECI_CSR_ST2_ADDR                       (PECI_CSR_BASE_ADDR + PECI_CSR_ST2_OFFSET_ADDR)

#endif /* __PECI_CSR_ADDR_DEFINE_H__ */
