// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __PWM_CSR_ADDR_DEFINE_H__
#define __PWM_CSR_ADDR_DEFINE_H__

#define    PWM_CSR_BASE_ADDR                    0x8759000

/* offset address for PWM_CSR registers */
#define PWM_CSR_CHEN_OFFSET_ADDR           0x0
#define PWM_CSR_INIT_VALUE_OFFSET_ADDR     0x4
#define PWM_CSR_PRD0_OFFSET_ADDR           0x8
#define PWM_CSR_CH0_PWL_OFFSET_ADDR        0xC
#define PWM_CSR_CH0_PWH_OFFSET_ADDR        0x10
#define PWM_CSR_PRD1_OFFSET_ADDR           0x14
#define PWM_CSR_CH1_PWL_OFFSET_ADDR        0x18
#define PWM_CSR_CH1_PWH_OFFSET_ADDR        0x1C
#define PWM_CSR_PRD2_OFFSET_ADDR           0x20
#define PWM_CSR_CH2_PWL_OFFSET_ADDR        0x24
#define PWM_CSR_CH2_PWH_OFFSET_ADDR        0x28
#define PWM_CSR_PRD3_OFFSET_ADDR           0x2C
#define PWM_CSR_CH3_PWL_OFFSET_ADDR        0x30
#define PWM_CSR_CH3_PWH_OFFSET_ADDR        0x34
#define PWM_CSR_PRD4_OFFSET_ADDR           0x38
#define PWM_CSR_CH4_PWL_OFFSET_ADDR        0x3C
#define PWM_CSR_CH4_PWH_OFFSET_ADDR        0x40
#define PWM_CSR_PRD5_OFFSET_ADDR           0x44
#define PWM_CSR_CH5_PWL_OFFSET_ADDR        0x48
#define PWM_CSR_CH5_PWH_OFFSET_ADDR        0x4C
#define PWM_CSR_PRD6_OFFSET_ADDR           0x50
#define PWM_CSR_CH6_PWL_OFFSET_ADDR        0x54
#define PWM_CSR_CH6_PWH_OFFSET_ADDR        0x58
#define PWM_CSR_PRD7_OFFSET_ADDR           0x5C
#define PWM_CSR_CH7_PWL_OFFSET_ADDR        0x60
#define PWM_CSR_CH7_PWH_OFFSET_ADDR        0x64
#define PWM_CSR_PRD8_OFFSET_ADDR           0x68
#define PWM_CSR_CH8_PWL_OFFSET_ADDR        0x6C
#define PWM_CSR_CH8_PWH_OFFSET_ADDR        0x70
#define PWM_CSR_PRD9_OFFSET_ADDR           0x74
#define PWM_CSR_CH9_PWL_OFFSET_ADDR        0x78
#define PWM_CSR_CH9_PWH_OFFSET_ADDR        0x7C
#define PWM_CSR_PRD10_OFFSET_ADDR          0x80
#define PWM_CSR_CH10_PWL_OFFSET_ADDR       0x84
#define PWM_CSR_CH10_PWH_OFFSET_ADDR       0x88
#define PWM_CSR_PRD11_OFFSET_ADDR          0x8C
#define PWM_CSR_CH11_PWL_OFFSET_ADDR       0x90
#define PWM_CSR_CH11_PWH_OFFSET_ADDR       0x94
#define PWM_CSR_FAN_CTRL_OFFSET_ADDR       0x98
#define PWM_CSR_FAN_EDGE_SEL_OFFSET_ADDR   0x9C
#define PWM_CSR_FAN_STATUS_OFFSET_ADDR     0xA0
#define PWM_CSR_FAN_SR0_OFFSET_ADDR        0xA4
#define PWM_CSR_FAN_TH0_OFFSET_ADDR        0xA8
#define PWM_CSR_FAN_SR1_OFFSET_ADDR        0xAC
#define PWM_CSR_FAN_TH1_OFFSET_ADDR        0xB0
#define PWM_CSR_FAN_SR2_OFFSET_ADDR        0xB4
#define PWM_CSR_FAN_TH2_OFFSET_ADDR        0xB8
#define PWM_CSR_FAN_SR3_OFFSET_ADDR        0xBC
#define PWM_CSR_FAN_TH3_OFFSET_ADDR        0xC0
#define PWM_CSR_FAN_SR4_OFFSET_ADDR        0xC4
#define PWM_CSR_FAN_TH4_OFFSET_ADDR        0xC8
#define PWM_CSR_FAN_SR5_OFFSET_ADDR        0xCC
#define PWM_CSR_FAN_TH5_OFFSET_ADDR        0xD0
#define PWM_CSR_FAN_SR6_OFFSET_ADDR        0xD4
#define PWM_CSR_FAN_TH6_OFFSET_ADDR        0xD8
#define PWM_CSR_FAN_SR7_OFFSET_ADDR        0xDC
#define PWM_CSR_FAN_TH7_OFFSET_ADDR        0xE0
#define PWM_CSR_FAN_SR8_OFFSET_ADDR        0xE4
#define PWM_CSR_FAN_TH8_OFFSET_ADDR        0xE8
#define PWM_CSR_FAN_SR9_OFFSET_ADDR        0xEC
#define PWM_CSR_FAN_TH9_OFFSET_ADDR        0xF0
#define PWM_CSR_FAN_SR10_OFFSET_ADDR       0xF4
#define PWM_CSR_FAN_TH10_OFFSET_ADDR       0xF8
#define PWM_CSR_FAN_SR11_OFFSET_ADDR       0xFC
#define PWM_CSR_FAN_TH11_OFFSET_ADDR       0x100
#define PWM_CSR_FAN_INT_EN_OFFSET_ADDR     0x104
#define PWM_CSR_MEASURE_TIME_OFFSET_ADDR   0x108

#define PWM_CSR_CHEN_ADDR           (PWM_CSR_BASE_ADDR + PWM_CSR_CHEN_OFFSET_ADDR)
#define PWM_CSR_INIT_VALUE_ADDR     (PWM_CSR_BASE_ADDR + PWM_CSR_INIT_VALUE_OFFSET_ADDR)
#define PWM_CSR_PRD0_ADDR           (PWM_CSR_BASE_ADDR + PWM_CSR_PRD0_OFFSET_ADDR)
#define PWM_CSR_CH0_PWL_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH0_PWL_OFFSET_ADDR)
#define PWM_CSR_CH0_PWH_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH0_PWH_OFFSET_ADDR)
#define PWM_CSR_PRD1_ADDR           (PWM_CSR_BASE_ADDR + PWM_CSR_PRD1_OFFSET_ADDR)
#define PWM_CSR_CH1_PWL_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH1_PWL_OFFSET_ADDR)
#define PWM_CSR_CH1_PWH_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH1_PWH_OFFSET_ADDR)
#define PWM_CSR_PRD2_ADDR           (PWM_CSR_BASE_ADDR + PWM_CSR_PRD2_OFFSET_ADDR)
#define PWM_CSR_CH2_PWL_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH2_PWL_OFFSET_ADDR)
#define PWM_CSR_CH2_PWH_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH2_PWH_OFFSET_ADDR)
#define PWM_CSR_PRD3_ADDR           (PWM_CSR_BASE_ADDR + PWM_CSR_PRD3_OFFSET_ADDR)
#define PWM_CSR_CH3_PWL_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH3_PWL_OFFSET_ADDR)
#define PWM_CSR_CH3_PWH_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH3_PWH_OFFSET_ADDR)
#define PWM_CSR_PRD4_ADDR           (PWM_CSR_BASE_ADDR + PWM_CSR_PRD4_OFFSET_ADDR)
#define PWM_CSR_CH4_PWL_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH4_PWL_OFFSET_ADDR)
#define PWM_CSR_CH4_PWH_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH4_PWH_OFFSET_ADDR)
#define PWM_CSR_PRD5_ADDR           (PWM_CSR_BASE_ADDR + PWM_CSR_PRD5_OFFSET_ADDR)
#define PWM_CSR_CH5_PWL_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH5_PWL_OFFSET_ADDR)
#define PWM_CSR_CH5_PWH_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH5_PWH_OFFSET_ADDR)
#define PWM_CSR_PRD6_ADDR           (PWM_CSR_BASE_ADDR + PWM_CSR_PRD6_OFFSET_ADDR)
#define PWM_CSR_CH6_PWL_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH6_PWL_OFFSET_ADDR)
#define PWM_CSR_CH6_PWH_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH6_PWH_OFFSET_ADDR)
#define PWM_CSR_PRD7_ADDR           (PWM_CSR_BASE_ADDR + PWM_CSR_PRD7_OFFSET_ADDR)
#define PWM_CSR_CH7_PWL_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH7_PWL_OFFSET_ADDR)
#define PWM_CSR_CH7_PWH_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH7_PWH_OFFSET_ADDR)
#define PWM_CSR_PRD8_ADDR           (PWM_CSR_BASE_ADDR + PWM_CSR_PRD8_OFFSET_ADDR)
#define PWM_CSR_CH8_PWL_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH8_PWL_OFFSET_ADDR)
#define PWM_CSR_CH8_PWH_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH8_PWH_OFFSET_ADDR)
#define PWM_CSR_PRD9_ADDR           (PWM_CSR_BASE_ADDR + PWM_CSR_PRD9_OFFSET_ADDR)
#define PWM_CSR_CH9_PWL_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH9_PWL_OFFSET_ADDR)
#define PWM_CSR_CH9_PWH_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_CH9_PWH_OFFSET_ADDR)
#define PWM_CSR_PRD10_ADDR          (PWM_CSR_BASE_ADDR + PWM_CSR_PRD10_OFFSET_ADDR)
#define PWM_CSR_CH10_PWL_ADDR       (PWM_CSR_BASE_ADDR + PWM_CSR_CH10_PWL_OFFSET_ADDR)
#define PWM_CSR_CH10_PWH_ADDR       (PWM_CSR_BASE_ADDR + PWM_CSR_CH10_PWH_OFFSET_ADDR)
#define PWM_CSR_PRD11_ADDR          (PWM_CSR_BASE_ADDR + PWM_CSR_PRD11_OFFSET_ADDR)
#define PWM_CSR_CH11_PWL_ADDR       (PWM_CSR_BASE_ADDR + PWM_CSR_CH11_PWL_OFFSET_ADDR)
#define PWM_CSR_CH11_PWH_ADDR       (PWM_CSR_BASE_ADDR + PWM_CSR_CH11_PWH_OFFSET_ADDR)
#define PWM_CSR_FAN_CTRL_ADDR       (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_CTRL_OFFSET_ADDR)
#define PWM_CSR_FAN_EDGE_SEL_ADDR   (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_EDGE_SEL_OFFSET_ADDR)
#define PWM_CSR_FAN_STATUS_ADDR     (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_STATUS_OFFSET_ADDR)
#define PWM_CSR_FAN_SR0_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR0_OFFSET_ADDR)
#define PWM_CSR_FAN_TH0_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH0_OFFSET_ADDR)
#define PWM_CSR_FAN_SR1_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR1_OFFSET_ADDR)
#define PWM_CSR_FAN_TH1_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH1_OFFSET_ADDR)
#define PWM_CSR_FAN_SR2_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR2_OFFSET_ADDR)
#define PWM_CSR_FAN_TH2_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH2_OFFSET_ADDR)
#define PWM_CSR_FAN_SR3_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR3_OFFSET_ADDR)
#define PWM_CSR_FAN_TH3_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH3_OFFSET_ADDR)
#define PWM_CSR_FAN_SR4_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR4_OFFSET_ADDR)
#define PWM_CSR_FAN_TH4_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH4_OFFSET_ADDR)
#define PWM_CSR_FAN_SR5_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR5_OFFSET_ADDR)
#define PWM_CSR_FAN_TH5_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH5_OFFSET_ADDR)
#define PWM_CSR_FAN_SR6_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR6_OFFSET_ADDR)
#define PWM_CSR_FAN_TH6_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH6_OFFSET_ADDR)
#define PWM_CSR_FAN_SR7_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR7_OFFSET_ADDR)
#define PWM_CSR_FAN_TH7_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH7_OFFSET_ADDR)
#define PWM_CSR_FAN_SR8_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR8_OFFSET_ADDR)
#define PWM_CSR_FAN_TH8_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH8_OFFSET_ADDR)
#define PWM_CSR_FAN_SR9_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR9_OFFSET_ADDR)
#define PWM_CSR_FAN_TH9_ADDR        (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH9_OFFSET_ADDR)
#define PWM_CSR_FAN_SR10_ADDR       (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR10_OFFSET_ADDR)
#define PWM_CSR_FAN_TH10_ADDR       (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH10_OFFSET_ADDR)
#define PWM_CSR_FAN_SR11_ADDR       (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_SR11_OFFSET_ADDR)
#define PWM_CSR_FAN_TH11_ADDR       (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_TH11_OFFSET_ADDR)
#define PWM_CSR_FAN_INT_EN_ADDR     (PWM_CSR_BASE_ADDR + PWM_CSR_FAN_INT_EN_OFFSET_ADDR)
#define PWM_CSR_MEASURE_TIME_ADDR   (PWM_CSR_BASE_ADDR + PWM_CSR_MEASURE_TIME_OFFSET_ADDR)

#endif /* __PWM_CSR_ADDR_DEFINE_H__ */
