// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __SOL_CSR_ADDR_DEFINE_H__
#define __SOL_CSR_ADDR_DEFINE_H__

#define    SOL_CSR_BASE_ADDR                    0x872c000

#define SOL_CSR_START_OFFSET_ADDR           0x0
#define SOL_CSR_TX_START_ADDR_L_OFFSET_ADDR 0x4
#define SOL_CSR_TX_DDR_SIZE_OFFSET_ADDR     0x8
#define SOL_CSR_RX_START_ADDR_L_OFFSET_ADDR 0xC
#define SOL_CSR_RX_DDR_SIZE_OFFSET_ADDR     0x10
#define SOL_CSR_TX_DDR_WADDR_L_OFFSET_ADDR  0x14
#define SOL_CSR_RX_DDR_WADDR_L_OFFSET_ADDR  0x18
#define SOL_CSR_FIFO_STATUS_OFFSET_ADDR     0x1C
#define SOL_CSR_HERR_TIME_OFFSET_ADDR       0x20
#define SOL_CSR_IRQ_ST_OFFSET_ADDR          0x24
#define SOL_CSR_RE_TIME_TH_OFFSET_ADDR      0x28

#define SOL_CSR_START_ADDR           (SOL_CSR_BASE_ADDR + SOL_CSR_START_OFFSET_ADDR)
#define SOL_CSR_TX_START_ADDR_L_ADDR (SOL_CSR_BASE_ADDR + SOL_CSR_TX_START_ADDR_L_OFFSET_ADDR)
#define SOL_CSR_TX_DDR_SIZE_ADDR     (SOL_CSR_BASE_ADDR + SOL_CSR_TX_DDR_SIZE_OFFSET_ADDR)
#define SOL_CSR_RX_START_ADDR_L_ADDR (SOL_CSR_BASE_ADDR + SOL_CSR_RX_START_ADDR_L_OFFSET_ADDR)
#define SOL_CSR_RX_DDR_SIZE_ADDR     (SOL_CSR_BASE_ADDR + SOL_CSR_RX_DDR_SIZE_OFFSET_ADDR)
#define SOL_CSR_TX_DDR_WADDR_L_ADDR  (SOL_CSR_BASE_ADDR + SOL_CSR_TX_DDR_WADDR_L_OFFSET_ADDR)
#define SOL_CSR_RX_DDR_WADDR_L_ADDR  (SOL_CSR_BASE_ADDR + SOL_CSR_RX_DDR_WADDR_L_OFFSET_ADDR)
#define SOL_CSR_FIFO_STATUS_ADDR     (SOL_CSR_BASE_ADDR + SOL_CSR_FIFO_STATUS_OFFSET_ADDR)
#define SOL_CSR_HERR_TIME_ADDR       (SOL_CSR_BASE_ADDR + SOL_CSR_HERR_TIME_OFFSET_ADDR)
#define SOL_CSR_IRQ_ST_ADDR          (SOL_CSR_BASE_ADDR + SOL_CSR_IRQ_ST_OFFSET_ADDR)
#define SOL_CSR_RE_TIME_TH_ADDR      (SOL_CSR_BASE_ADDR + SOL_CSR_RE_TIME_TH_OFFSET_ADDR)

#endif // __SOL_CSR_ADDR_DEFINE_H__
