// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __SPI_ADDR_DEFINE_H__
#define __SPI_ADDR_DEFINE_H__

#define SPI_BASE_ADDR           0x8713000
#define SPI_CTRLR0_OFFSET_ADDR  0x0
#define SPI_CTRLR1_OFFSET_ADDR  0x4
#define SPI_SSIENR_OFFSET_ADDR  0x8
#define SPI_MWCR_OFFSET_ADDR    0xC
#define SPI_SER_OFFSET_ADDR     0x10
#define SPI_BAUDR_OFFSET_ADDR   0x14
#define SPI_TXFTLR_OFFSET_ADDR  0x18
#define SPI_RXFTLR_OFFSET_ADDR  0x1C
#define SPI_TXFLR_OFFSET_ADDR   0x20
#define SPI_RXFLR_OFFSET_ADDR   0x24
#define SPI_SR_OFFSET_ADDR      0x28
#define SPI_IMR_OFFSET_ADDR     0x2C
#define SPI_ISR_OFFSET_ADDR     0x30
#define SPI_SISR_OFFSET_ADDR    0x34
#define SPI_TXOICR_OFFSET_ADDR  0x38
#define SPI_RXOICR_OFFSET_ADDR  0x3C
#define SPI_RXUICR_OFFSET_ADDR  0x40
#define SPI_MSTICR_OFFSET_ADDR  0x44
#define SPI_ICR_OFFSET_ADDR     0x48
#define SPI_DMACR_OFFSET_ADDR   0x4C
#define SPI_DMATDLR_OFFSET_ADDR 0x50
#define SPI_DMARDLR_OFFSET_ADDR 0x54
#define SPI_IDR_OFFSET_ADDR     0x58
#define SPI_DR0_OFFSET_ADDR     0x60
#define SPI_DR1_OFFSET_ADDR     0x64
#define SPI_DR2_OFFSET_ADDR     0x68
#define SPI_DR3_OFFSET_ADDR     0x6C
#define SPI_DR4_OFFSET_ADDR     0x70
#define SPI_DR5_OFFSET_ADDR     0x74
#define SPI_DR6_OFFSET_ADDR     0x78
#define SPI_DR7_OFFSET_ADDR     0x7C
#define SPI_DR8_OFFSET_ADDR     0x80
#define SPI_DR9_OFFSET_ADDR     0x84
#define SPI_DR10_OFFSET_ADDR    0x88
#define SPI_DR11_OFFSET_ADDR    0x8C
#define SPI_DR12_OFFSET_ADDR    0x90
#define SPI_DR13_OFFSET_ADDR    0x94
#define SPI_DR14_OFFSET_ADDR    0x98
#define SPI_DR15_OFFSET_ADDR    0x9C

#define SPI_CTRLR0_ADDR  (SPI_BASE_ADDR + SPI_CTRLR0_OFFSET_ADDR)
#define SPI_CTRLR1_ADDR  (SPI_BASE_ADDR + SPI_CTRLR1_OFFSET_ADDR)
#define SPI_SSIENR_ADDR  (SPI_BASE_ADDR + SPI_SSIENR_OFFSET_ADDR)
#define SPI_MWCR_ADDR    (SPI_BASE_ADDR + SPI_MWCR_OFFSET_ADDR)
#define SPI_SER_ADDR     (SPI_BASE_ADDR + SPI_SER_OFFSET_ADDR)
#define SPI_BAUDR_ADDR   (SPI_BASE_ADDR + SPI_BAUDR_OFFSET_ADDR)
#define SPI_TXFTLR_ADDR  (SPI_BASE_ADDR + SPI_TXFTLR_OFFSET_ADDR)
#define SPI_RXFTLR_ADDR  (SPI_BASE_ADDR + SPI_RXFTLR_OFFSET_ADDR)
#define SPI_TXFLR_ADDR   (SPI_BASE_ADDR + SPI_TXFLR_OFFSET_ADDR)
#define SPI_RXFLR_ADDR   (SPI_BASE_ADDR + SPI_RXFLR_OFFSET_ADDR)
#define SPI_SR_ADDR      (SPI_BASE_ADDR + SPI_SR_OFFSET_ADDR)
#define SPI_IMR_ADDR     (SPI_BASE_ADDR + SPI_IMR_OFFSET_ADDR)
#define SPI_ISR_ADDR     (SPI_BASE_ADDR + SPI_ISR_OFFSET_ADDR)
#define SPI_SISR_ADDR    (SPI_BASE_ADDR + SPI_SISR_OFFSET_ADDR)
#define SPI_TXOICR_ADDR  (SPI_BASE_ADDR + SPI_TXOICR_OFFSET_ADDR)
#define SPI_RXOICR_ADDR  (SPI_BASE_ADDR + SPI_RXOICR_OFFSET_ADDR)
#define SPI_RXUICR_ADDR  (SPI_BASE_ADDR + SPI_RXUICR_OFFSET_ADDR)
#define SPI_MSTICR_ADDR  (SPI_BASE_ADDR + SPI_MSTICR_OFFSET_ADDR)
#define SPI_ICR_ADDR     (SPI_BASE_ADDR + SPI_ICR_OFFSET_ADDR)
#define SPI_DMACR_ADDR   (SPI_BASE_ADDR + SPI_DMACR_OFFSET_ADDR)
#define SPI_DMATDLR_ADDR (SPI_BASE_ADDR + SPI_DMATDLR_OFFSET_ADDR)
#define SPI_DMARDLR_ADDR (SPI_BASE_ADDR + SPI_DMARDLR_OFFSET_ADDR)
#define SPI_IDR_ADDR     (SPI_BASE_ADDR + SPI_IDR_OFFSET_ADDR)
#define SPI_DR0_ADDR     (SPI_BASE_ADDR + SPI_DR0_OFFSET_ADDR)
#define SPI_DR1_ADDR     (SPI_BASE_ADDR + SPI_DR1_OFFSET_ADDR)
#define SPI_DR2_ADDR     (SPI_BASE_ADDR + SPI_DR2_OFFSET_ADDR)
#define SPI_DR3_ADDR     (SPI_BASE_ADDR + SPI_DR3_OFFSET_ADDR)
#define SPI_DR4_ADDR     (SPI_BASE_ADDR + SPI_DR4_OFFSET_ADDR)
#define SPI_DR5_ADDR     (SPI_BASE_ADDR + SPI_DR5_OFFSET_ADDR)
#define SPI_DR6_ADDR     (SPI_BASE_ADDR + SPI_DR6_OFFSET_ADDR)
#define SPI_DR7_ADDR     (SPI_BASE_ADDR + SPI_DR7_OFFSET_ADDR)
#define SPI_DR8_ADDR     (SPI_BASE_ADDR + SPI_DR8_OFFSET_ADDR)
#define SPI_DR9_ADDR     (SPI_BASE_ADDR + SPI_DR9_OFFSET_ADDR)
#define SPI_DR10_ADDR    (SPI_BASE_ADDR + SPI_DR10_OFFSET_ADDR)
#define SPI_DR11_ADDR    (SPI_BASE_ADDR + SPI_DR11_OFFSET_ADDR)
#define SPI_DR12_ADDR    (SPI_BASE_ADDR + SPI_DR12_OFFSET_ADDR)
#define SPI_DR13_ADDR    (SPI_BASE_ADDR + SPI_DR13_OFFSET_ADDR)
#define SPI_DR14_ADDR    (SPI_BASE_ADDR + SPI_DR14_OFFSET_ADDR)
#define SPI_DR15_ADDR    (SPI_BASE_ADDR + SPI_DR15_OFFSET_ADDR)

#endif
