// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef __WDG_CSR_ADDR_DEFINE_H__
#define __WDG_CSR_ADDR_DEFINE_H__

#define    WDG_CSR_BASE_ADDR                    0x8763000

#define WDG_CSR_LOAD_OFFSET_ADDR    0x0
#define WDG_CSR_VALUE_OFFSET_ADDR   0x4
#define WDG_CSR_CONTROL_OFFSET_ADDR 0x8
#define WDG_CSR_INTCLR_OFFSET_ADDR  0xC
#define WDG_CSR_RIS_OFFSET_ADDR     0x10
#define WDG_CSR_MIS_OFFSET_ADDR     0x14
#define WDG_CSR_LOCK_OFFSET_ADDR    0xC00

#define WDG_CSR_LOAD_ADDR    (WDG_CSR_BASE_ADDR + WDG_CSR_LOAD_OFFSET_ADDR)
#define WDG_CSR_VALUE_ADDR   (WDG_CSR_BASE_ADDR + WDG_CSR_VALUE_OFFSET_ADDR)
#define WDG_CSR_CONTROL_ADDR (WDG_CSR_BASE_ADDR + WDG_CSR_CONTROL_OFFSET_ADDR)
#define WDG_CSR_INTCLR_ADDR  (WDG_CSR_BASE_ADDR + WDG_CSR_INTCLR_OFFSET_ADDR)
#define WDG_CSR_RIS_ADDR     (WDG_CSR_BASE_ADDR + WDG_CSR_RIS_OFFSET_ADDR)
#define WDG_CSR_MIS_ADDR     (WDG_CSR_BASE_ADDR + WDG_CSR_MIS_OFFSET_ADDR)
#define WDG_CSR_LOCK_ADDR    (WDG_CSR_BASE_ADDR + WDG_CSR_LOCK_OFFSET_ADDR)

#endif // __WDG_CSR_ADDR_DEFINE_H__
