/*
 * Copyright (c) Hisilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 * UniProton is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 * 	http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * See the Mulan PSL v2 for more details.
 */

#ifndef __DMAC_REGS_H__
#define __DMAC_REGS_H__

#define    DMAC_BASE_ADDR                    0x8714000

#define DMAC_INT_1_OFFSET_ADDR              0x0
#define DMAC_ITC_MASK_INT_1_OFFSET_ADDR     0x4
#define DMAC_IE_MASK_INT_1_OFFSET_ADDR      0x8
#define DMAC_INT_TC_1_OFFSET_ADDR           0xC
#define DMAC_INT_ERR_1_OFFSET_ADDR          0x10
#define DMAC_INT_2_OFFSET_ADDR              0x14
#define DMAC_ITC_MASK_INT_2_OFFSET_ADDR     0x18
#define DMAC_IE_MASK_INT_2_OFFSET_ADDR      0x1C
#define DMAC_INT_TC_2_OFFSET_ADDR           0x20
#define DMAC_INT_ERR_2_OFFSET_ADDR          0x24
#define DMAC_INT_3_OFFSET_ADDR              0x28
#define DMAC_ITC_MASK_INT_3_OFFSET_ADDR     0x2C
#define DMAC_IE_MASK_INT_3_OFFSET_ADDR      0x30
#define DMAC_INT_TC_3_OFFSET_ADDR           0x34
#define DMAC_INT_ERR_3_OFFSET_ADDR          0x38
#define DMAC_INT_TC_CLR_OFFSET_ADDR         0x3C
#define DMAC_INT_ERR_CLR_OFFSET_ADDR        0x40
#define DMAC_INT_TC_RAW_OFFSET_ADDR         0x44
#define DMAC_INT_ERR_RAW_OFFSET_ADDR        0x48
#define DMAC_EN_CH_STATUS_OFFSET_ADDR       0x4C
#define DMAC_BREQ_OFFSET_ADDR               0x50
#define DMAC_SREQ_OFFSET_ADDR               0x58
#define DMAC_LBREQ_OFFSET_ADDR              0x60
#define DMAC_LSREQ_OFFSET_ADDR              0x68
#define DMAC_SECURIRY_READ_OFFSET_ADDR      0x70
#define DMAC_SECURIRY_WRITE_OFFSET_ADDR     0x74
#define DMAC_G_EN_OFFSET_ADDR               0x78
#define DMAC_AUDIO_JP_SIZE_OFFSET_ADDR      0x7C
#define DMAC_STRID_CH_SIZE_OFFSET_ADDR      0x80
#define DMAC_VIDEO_LN_SIZE_OFFSET_ADDR      0x84
#define DMAC_CMSRCADDR_0_OFFSET_ADDR        0x100
#define DMAC_CMSRCADDR_1_OFFSET_ADDR        0x110
#define DMAC_CMSRCADDR_2_OFFSET_ADDR        0x120
#define DMAC_CMSRCADDR_3_OFFSET_ADDR        0x130
#define DMAC_CMSRCADDR_4_OFFSET_ADDR        0x140
#define DMAC_CMSRCADDR_5_OFFSET_ADDR        0x150
#define DMAC_CMSRCADDR_6_OFFSET_ADDR        0x160
#define DMAC_CMSRCADDR_7_OFFSET_ADDR        0x170
#define DMAC_CMSRCADDR_8_OFFSET_ADDR        0x180
#define DMAC_CMSRCADDR_9_OFFSET_ADDR        0x190
#define DMAC_CMSRCADDR_10_OFFSET_ADDR       0x1A0
#define DMAC_CMSRCADDR_11_OFFSET_ADDR       0x1B0
#define DMAC_CMSRCADDR_12_OFFSET_ADDR       0x1C0
#define DMAC_CMSRCADDR_13_OFFSET_ADDR       0x1D0
#define DMAC_CMSRCADDR_14_OFFSET_ADDR       0x1E0
#define DMAC_CMSRCADDR_15_OFFSET_ADDR       0x1F0
#define DMAC_CMDESTADDR_0_OFFSET_ADDR       0x104
#define DMAC_CMDESTADDR_1_OFFSET_ADDR       0x114
#define DMAC_CMDESTADDR_2_OFFSET_ADDR       0x124
#define DMAC_CMDESTADDR_3_OFFSET_ADDR       0x134
#define DMAC_CMDESTADDR_4_OFFSET_ADDR       0x144
#define DMAC_CMDESTADDR_5_OFFSET_ADDR       0x154
#define DMAC_CMDESTADDR_6_OFFSET_ADDR       0x164
#define DMAC_CMDESTADDR_7_OFFSET_ADDR       0x174
#define DMAC_CMDESTADDR_8_OFFSET_ADDR       0x184
#define DMAC_CMDESTADDR_9_OFFSET_ADDR       0x194
#define DMAC_CMDESTADDR_10_OFFSET_ADDR      0x1A4
#define DMAC_CMDESTADDR_11_OFFSET_ADDR      0x1B4
#define DMAC_CMDESTADDR_12_OFFSET_ADDR      0x1C4
#define DMAC_CMDESTADDR_13_OFFSET_ADDR      0x1D4
#define DMAC_CMDESTADDR_14_OFFSET_ADDR      0x1E4
#define DMAC_CMDESTADDR_15_OFFSET_ADDR      0x1F4
#define DMAC_CMLLI_0_OFFSET_ADDR            0x108
#define DMAC_CMLLI_1_OFFSET_ADDR            0x118
#define DMAC_CMLLI_2_OFFSET_ADDR            0x128
#define DMAC_CMLLI_3_OFFSET_ADDR            0x138
#define DMAC_CMLLI_4_OFFSET_ADDR            0x148
#define DMAC_CMLLI_5_OFFSET_ADDR            0x158
#define DMAC_CMLLI_6_OFFSET_ADDR            0x168
#define DMAC_CMLLI_7_OFFSET_ADDR            0x178
#define DMAC_CMLLI_8_OFFSET_ADDR            0x188
#define DMAC_CMLLI_9_OFFSET_ADDR            0x198
#define DMAC_CMLLI_10_OFFSET_ADDR           0x1A8
#define DMAC_CMLLI_11_OFFSET_ADDR           0x1B8
#define DMAC_CMLLI_12_OFFSET_ADDR           0x1C8
#define DMAC_CMLLI_13_OFFSET_ADDR           0x1D8
#define DMAC_CMLLI_14_OFFSET_ADDR           0x1E8
#define DMAC_CMLLI_15_OFFSET_ADDR           0x1F8
#define DMAC_CMCONTROL_0_OFFSET_ADDR        0x10C
#define DMAC_CMCONTROL_1_OFFSET_ADDR        0x11C
#define DMAC_CMCONTROL_2_OFFSET_ADDR        0x12C
#define DMAC_CMCONTROL_3_OFFSET_ADDR        0x13C
#define DMAC_CMCONTROL_4_OFFSET_ADDR        0x14C
#define DMAC_CMCONTROL_5_OFFSET_ADDR        0x15C
#define DMAC_CMCONTROL_6_OFFSET_ADDR        0x16C
#define DMAC_CMCONTROL_7_OFFSET_ADDR        0x17C
#define DMAC_CMCONTROL_8_OFFSET_ADDR        0x18C
#define DMAC_CMCONTROL_9_OFFSET_ADDR        0x19C
#define DMAC_CMCONTROL_10_OFFSET_ADDR       0x1AC
#define DMAC_CMCONTROL_11_OFFSET_ADDR       0x1BC
#define DMAC_CMCONTROL_12_OFFSET_ADDR       0x1CC
#define DMAC_CMCONTROL_13_OFFSET_ADDR       0x1DC
#define DMAC_CMCONTROL_14_OFFSET_ADDR       0x1EC
#define DMAC_CMCONTROL_15_OFFSET_ADDR       0x1FC
#define DMAC_CMCONFIG_0_OFFSET_ADDR         0x300
#define DMAC_CMCONFIG_1_OFFSET_ADDR         0x304
#define DMAC_CMCONFIG_2_OFFSET_ADDR         0x308
#define DMAC_CMCONFIG_3_OFFSET_ADDR         0x30C
#define DMAC_CMCONFIG_4_OFFSET_ADDR         0x310
#define DMAC_CMCONFIG_5_OFFSET_ADDR         0x314
#define DMAC_CMCONFIG_6_OFFSET_ADDR         0x318
#define DMAC_CMCONFIG_7_OFFSET_ADDR         0x31C
#define DMAC_CMCONFIG_8_OFFSET_ADDR         0x320
#define DMAC_CMCONFIG_9_OFFSET_ADDR         0x324
#define DMAC_CMCONFIG_10_OFFSET_ADDR        0x328
#define DMAC_CMCONFIG_11_OFFSET_ADDR        0x32C
#define DMAC_CMCONFIG_12_OFFSET_ADDR        0x330
#define DMAC_CMCONFIG_13_OFFSET_ADDR        0x334
#define DMAC_CMCONFIG_14_OFFSET_ADDR        0x338
#define DMAC_CMCONFIG_15_OFFSET_ADDR        0x33C
#define DMAC_CMSRCADDR_H2_0_OFFSET_ADDR     0x200
#define DMAC_CMSRCADDR_H2_1_OFFSET_ADDR     0x210
#define DMAC_CMSRCADDR_H2_2_OFFSET_ADDR     0x220
#define DMAC_CMSRCADDR_H2_3_OFFSET_ADDR     0x230
#define DMAC_CMSRCADDR_H2_4_OFFSET_ADDR     0x240
#define DMAC_CMSRCADDR_H2_5_OFFSET_ADDR     0x250
#define DMAC_CMSRCADDR_H2_6_OFFSET_ADDR     0x260
#define DMAC_CMSRCADDR_H2_7_OFFSET_ADDR     0x270
#define DMAC_CMSRCADDR_H2_8_OFFSET_ADDR     0x280
#define DMAC_CMSRCADDR_H2_9_OFFSET_ADDR     0x290
#define DMAC_CMSRCADDR_H2_10_OFFSET_ADDR    0x2A0
#define DMAC_CMSRCADDR_H2_11_OFFSET_ADDR    0x2B0
#define DMAC_CMSRCADDR_H2_12_OFFSET_ADDR    0x2C0
#define DMAC_CMSRCADDR_H2_13_OFFSET_ADDR    0x2D0
#define DMAC_CMSRCADDR_H2_14_OFFSET_ADDR    0x2E0
#define DMAC_CMSRCADDR_H2_15_OFFSET_ADDR    0x2F0
#define DMAC_CMDESTADDR_H2_0_OFFSET_ADDR    0x204
#define DMAC_CMDESTADDR_H2_1_OFFSET_ADDR    0x214
#define DMAC_CMDESTADDR_H2_2_OFFSET_ADDR    0x224
#define DMAC_CMDESTADDR_H2_3_OFFSET_ADDR    0x234
#define DMAC_CMDESTADDR_H2_4_OFFSET_ADDR    0x244
#define DMAC_CMDESTADDR_H2_5_OFFSET_ADDR    0x254
#define DMAC_CMDESTADDR_H2_6_OFFSET_ADDR    0x264
#define DMAC_CMDESTADDR_H2_7_OFFSET_ADDR    0x274
#define DMAC_CMDESTADDR_H2_8_OFFSET_ADDR    0x284
#define DMAC_CMDESTADDR_H2_9_OFFSET_ADDR    0x294
#define DMAC_CMDESTADDR_H2_10_OFFSET_ADDR   0x2A4
#define DMAC_CMDESTADDR_H2_11_OFFSET_ADDR   0x2B4
#define DMAC_CMDESTADDR_H2_12_OFFSET_ADDR   0x2C4
#define DMAC_CMDESTADDR_H2_13_OFFSET_ADDR   0x2D4
#define DMAC_CMDESTADDR_H2_14_OFFSET_ADDR   0x2E4
#define DMAC_CMDESTADDR_H2_15_OFFSET_ADDR   0x2F4

#define DMAC_INT_1_ADDR            (DMAC_BASE_ADDR + DMAC_INT_1_OFFSET_ADDR)
#define DMAC_ITC_MASK_INT_1_ADDR   (DMAC_BASE_ADDR + DMAC_ITC_MASK_INT_1_OFFSET_ADDR)
#define DMAC_IE_MASK_INT_1_ADDR    (DMAC_BASE_ADDR + DMAC_IE_MASK_INT_1_OFFSET_ADDR)
#define DMAC_INT_TC_1_ADDR         (DMAC_BASE_ADDR + DMAC_INT_TC_1_OFFSET_ADDR)
#define DMAC_INT_ERR_1_ADDR        (DMAC_BASE_ADDR + DMAC_INT_ERR_1_OFFSET_ADDR)
#define DMAC_INT_2_ADDR            (DMAC_BASE_ADDR + DMAC_INT_2_OFFSET_ADDR)
#define DMAC_ITC_MASK_INT_2_ADDR   (DMAC_BASE_ADDR + DMAC_ITC_MASK_INT_2_OFFSET_ADDR)
#define DMAC_IE_MASK_INT_2_ADDR    (DMAC_BASE_ADDR + DMAC_IE_MASK_INT_2_OFFSET_ADDR)
#define DMAC_INT_TC_2_ADDR         (DMAC_BASE_ADDR + DMAC_INT_TC_2_OFFSET_ADDR)
#define DMAC_INT_ERR_2_ADDR        (DMAC_BASE_ADDR + DMAC_INT_ERR_2_OFFSET_ADDR)
#define DMAC_INT_3_ADDR            (DMAC_BASE_ADDR + DMAC_INT_3_OFFSET_ADDR)
#define DMAC_ITC_MASK_INT_3_ADDR   (DMAC_BASE_ADDR + DMAC_ITC_MASK_INT_3_OFFSET_ADDR)
#define DMAC_IE_MASK_INT_3_ADDR    (DMAC_BASE_ADDR + DMAC_IE_MASK_INT_3_OFFSET_ADDR)
#define DMAC_INT_TC_3_ADDR         (DMAC_BASE_ADDR + DMAC_INT_TC_3_OFFSET_ADDR)
#define DMAC_INT_ERR_3_ADDR        (DMAC_BASE_ADDR + DMAC_INT_ERR_3_OFFSET_ADDR)
#define DMAC_INT_TC_CLR_ADDR       (DMAC_BASE_ADDR + DMAC_INT_TC_CLR_OFFSET_ADDR)
#define DMAC_INT_ERR_CLR_ADDR      (DMAC_BASE_ADDR + DMAC_INT_ERR_CLR_OFFSET_ADDR)
#define DMAC_INT_TC_RAW_ADDR       (DMAC_BASE_ADDR + DMAC_INT_TC_RAW_OFFSET_ADDR)
#define DMAC_INT_ERR_RAW_ADDR      (DMAC_BASE_ADDR + DMAC_INT_ERR_RAW_OFFSET_ADDR)
#define DMAC_EN_CH_STATUS_ADDR     (DMAC_BASE_ADDR + DMAC_EN_CH_STATUS_OFFSET_ADDR)
#define DMAC_BREQ_ADDR             (DMAC_BASE_ADDR + DMAC_BREQ_OFFSET_ADDR)
#define DMAC_SREQ_ADDR             (DMAC_BASE_ADDR + DMAC_SREQ_OFFSET_ADDR)
#define DMAC_LBREQ_ADDR            (DMAC_BASE_ADDR + DMAC_LBREQ_OFFSET_ADDR)
#define DMAC_LSREQ_ADDR            (DMAC_BASE_ADDR + DMAC_LSREQ_OFFSET_ADDR)
#define DMAC_SECURIRY_READ_ADDR    (DMAC_BASE_ADDR + DMAC_SECURIRY_READ_OFFSET_ADDR)
#define DMAC_SECURIRY_WRITE_ADDR   (DMAC_BASE_ADDR + DMAC_SECURIRY_WRITE_OFFSET_ADDR)
#define DMAC_G_EN_ADDR             (DMAC_BASE_ADDR + DMAC_G_EN_OFFSET_ADDR)
#define DMAC_AUDIO_JP_SIZE_ADDR    (DMAC_BASE_ADDR + DMAC_AUDIO_JP_SIZE_OFFSET_ADDR)
#define DMAC_STRID_CH_SIZE_ADDR    (DMAC_BASE_ADDR + DMAC_STRID_CH_SIZE_OFFSET_ADDR)
#define DMAC_VIDEO_LN_SIZE_ADDR    (DMAC_BASE_ADDR + DMAC_VIDEO_LN_SIZE_OFFSET_ADDR)
#define DMAC_CMSRCADDR_0_ADDR      (DMAC_BASE_ADDR + DMAC_CMSRCADDR_0_OFFSET_ADDR)
#define DMAC_CMSRCADDR_1_ADDR      (DMAC_BASE_ADDR + DMAC_CMSRCADDR_1_OFFSET_ADDR)
#define DMAC_CMSRCADDR_2_ADDR      (DMAC_BASE_ADDR + DMAC_CMSRCADDR_2_OFFSET_ADDR)
#define DMAC_CMSRCADDR_3_ADDR      (DMAC_BASE_ADDR + DMAC_CMSRCADDR_3_OFFSET_ADDR)
#define DMAC_CMSRCADDR_4_ADDR      (DMAC_BASE_ADDR + DMAC_CMSRCADDR_4_OFFSET_ADDR)
#define DMAC_CMSRCADDR_5_ADDR      (DMAC_BASE_ADDR + DMAC_CMSRCADDR_5_OFFSET_ADDR)
#define DMAC_CMSRCADDR_6_ADDR      (DMAC_BASE_ADDR + DMAC_CMSRCADDR_6_OFFSET_ADDR)
#define DMAC_CMSRCADDR_7_ADDR      (DMAC_BASE_ADDR + DMAC_CMSRCADDR_7_OFFSET_ADDR)
#define DMAC_CMSRCADDR_8_ADDR      (DMAC_BASE_ADDR + DMAC_CMSRCADDR_8_OFFSET_ADDR)
#define DMAC_CMSRCADDR_9_ADDR      (DMAC_BASE_ADDR + DMAC_CMSRCADDR_9_OFFSET_ADDR)
#define DMAC_CMSRCADDR_10_ADDR     (DMAC_BASE_ADDR + DMAC_CMSRCADDR_10_OFFSET_ADDR)
#define DMAC_CMSRCADDR_11_ADDR     (DMAC_BASE_ADDR + DMAC_CMSRCADDR_11_OFFSET_ADDR)
#define DMAC_CMSRCADDR_12_ADDR     (DMAC_BASE_ADDR + DMAC_CMSRCADDR_12_OFFSET_ADDR)
#define DMAC_CMSRCADDR_13_ADDR     (DMAC_BASE_ADDR + DMAC_CMSRCADDR_13_OFFSET_ADDR)
#define DMAC_CMSRCADDR_14_ADDR     (DMAC_BASE_ADDR + DMAC_CMSRCADDR_14_OFFSET_ADDR)
#define DMAC_CMSRCADDR_15_ADDR     (DMAC_BASE_ADDR + DMAC_CMSRCADDR_15_OFFSET_ADDR)
#define DMAC_CMDESTADDR_0_ADDR     (DMAC_BASE_ADDR + DMAC_CMDESTADDR_0_OFFSET_ADDR)
#define DMAC_CMDESTADDR_1_ADDR     (DMAC_BASE_ADDR + DMAC_CMDESTADDR_1_OFFSET_ADDR)
#define DMAC_CMDESTADDR_2_ADDR     (DMAC_BASE_ADDR + DMAC_CMDESTADDR_2_OFFSET_ADDR)
#define DMAC_CMDESTADDR_3_ADDR     (DMAC_BASE_ADDR + DMAC_CMDESTADDR_3_OFFSET_ADDR)
#define DMAC_CMDESTADDR_4_ADDR     (DMAC_BASE_ADDR + DMAC_CMDESTADDR_4_OFFSET_ADDR)
#define DMAC_CMDESTADDR_5_ADDR     (DMAC_BASE_ADDR + DMAC_CMDESTADDR_5_OFFSET_ADDR)
#define DMAC_CMDESTADDR_6_ADDR     (DMAC_BASE_ADDR + DMAC_CMDESTADDR_6_OFFSET_ADDR)
#define DMAC_CMDESTADDR_7_ADDR     (DMAC_BASE_ADDR + DMAC_CMDESTADDR_7_OFFSET_ADDR)
#define DMAC_CMDESTADDR_8_ADDR     (DMAC_BASE_ADDR + DMAC_CMDESTADDR_8_OFFSET_ADDR)
#define DMAC_CMDESTADDR_9_ADDR     (DMAC_BASE_ADDR + DMAC_CMDESTADDR_9_OFFSET_ADDR)
#define DMAC_CMDESTADDR_10_ADDR    (DMAC_BASE_ADDR + DMAC_CMDESTADDR_10_OFFSET_ADDR)
#define DMAC_CMDESTADDR_11_ADDR    (DMAC_BASE_ADDR + DMAC_CMDESTADDR_11_OFFSET_ADDR)
#define DMAC_CMDESTADDR_12_ADDR    (DMAC_BASE_ADDR + DMAC_CMDESTADDR_12_OFFSET_ADDR)
#define DMAC_CMDESTADDR_13_ADDR    (DMAC_BASE_ADDR + DMAC_CMDESTADDR_13_OFFSET_ADDR)
#define DMAC_CMDESTADDR_14_ADDR    (DMAC_BASE_ADDR + DMAC_CMDESTADDR_14_OFFSET_ADDR)
#define DMAC_CMDESTADDR_15_ADDR    (DMAC_BASE_ADDR + DMAC_CMDESTADDR_15_OFFSET_ADDR)
#define DMAC_CMLLI_0_ADDR          (DMAC_BASE_ADDR + DMAC_CMLLI_0_OFFSET_ADDR)
#define DMAC_CMLLI_1_ADDR          (DMAC_BASE_ADDR + DMAC_CMLLI_1_OFFSET_ADDR)
#define DMAC_CMLLI_2_ADDR          (DMAC_BASE_ADDR + DMAC_CMLLI_2_OFFSET_ADDR)
#define DMAC_CMLLI_3_ADDR          (DMAC_BASE_ADDR + DMAC_CMLLI_3_OFFSET_ADDR)
#define DMAC_CMLLI_4_ADDR          (DMAC_BASE_ADDR + DMAC_CMLLI_4_OFFSET_ADDR)
#define DMAC_CMLLI_5_ADDR          (DMAC_BASE_ADDR + DMAC_CMLLI_5_OFFSET_ADDR)
#define DMAC_CMLLI_6_ADDR          (DMAC_BASE_ADDR + DMAC_CMLLI_6_OFFSET_ADDR)
#define DMAC_CMLLI_7_ADDR          (DMAC_BASE_ADDR + DMAC_CMLLI_7_OFFSET_ADDR)
#define DMAC_CMLLI_8_ADDR          (DMAC_BASE_ADDR + DMAC_CMLLI_8_OFFSET_ADDR)
#define DMAC_CMLLI_9_ADDR          (DMAC_BASE_ADDR + DMAC_CMLLI_9_OFFSET_ADDR)
#define DMAC_CMLLI_10_ADDR         (DMAC_BASE_ADDR + DMAC_CMLLI_10_OFFSET_ADDR)
#define DMAC_CMLLI_11_ADDR         (DMAC_BASE_ADDR + DMAC_CMLLI_11_OFFSET_ADDR)
#define DMAC_CMLLI_12_ADDR         (DMAC_BASE_ADDR + DMAC_CMLLI_12_OFFSET_ADDR)
#define DMAC_CMLLI_13_ADDR         (DMAC_BASE_ADDR + DMAC_CMLLI_13_OFFSET_ADDR)
#define DMAC_CMLLI_14_ADDR         (DMAC_BASE_ADDR + DMAC_CMLLI_14_OFFSET_ADDR)
#define DMAC_CMLLI_15_ADDR         (DMAC_BASE_ADDR + DMAC_CMLLI_15_OFFSET_ADDR)
#define DMAC_CMCONTROL_0_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONTROL_0_OFFSET_ADDR)
#define DMAC_CMCONTROL_1_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONTROL_1_OFFSET_ADDR)
#define DMAC_CMCONTROL_2_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONTROL_2_OFFSET_ADDR)
#define DMAC_CMCONTROL_3_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONTROL_3_OFFSET_ADDR)
#define DMAC_CMCONTROL_4_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONTROL_4_OFFSET_ADDR)
#define DMAC_CMCONTROL_5_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONTROL_5_OFFSET_ADDR)
#define DMAC_CMCONTROL_6_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONTROL_6_OFFSET_ADDR)
#define DMAC_CMCONTROL_7_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONTROL_7_OFFSET_ADDR)
#define DMAC_CMCONTROL_8_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONTROL_8_OFFSET_ADDR)
#define DMAC_CMCONTROL_9_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONTROL_9_OFFSET_ADDR)
#define DMAC_CMCONTROL_10_ADDR     (DMAC_BASE_ADDR + DMAC_CMCONTROL_10_OFFSET_ADDR)
#define DMAC_CMCONTROL_11_ADDR     (DMAC_BASE_ADDR + DMAC_CMCONTROL_11_OFFSET_ADDR)
#define DMAC_CMCONTROL_12_ADDR     (DMAC_BASE_ADDR + DMAC_CMCONTROL_12_OFFSET_ADDR)
#define DMAC_CMCONTROL_13_ADDR     (DMAC_BASE_ADDR + DMAC_CMCONTROL_13_OFFSET_ADDR)
#define DMAC_CMCONTROL_14_ADDR     (DMAC_BASE_ADDR + DMAC_CMCONTROL_14_OFFSET_ADDR)
#define DMAC_CMCONTROL_15_ADDR     (DMAC_BASE_ADDR + DMAC_CMCONTROL_15_OFFSET_ADDR)
#define DMAC_CMCONFIG_0_ADDR       (DMAC_BASE_ADDR + DMAC_CMCONFIG_0_OFFSET_ADDR)
#define DMAC_CMCONFIG_1_ADDR       (DMAC_BASE_ADDR + DMAC_CMCONFIG_1_OFFSET_ADDR)
#define DMAC_CMCONFIG_2_ADDR       (DMAC_BASE_ADDR + DMAC_CMCONFIG_2_OFFSET_ADDR)
#define DMAC_CMCONFIG_3_ADDR       (DMAC_BASE_ADDR + DMAC_CMCONFIG_3_OFFSET_ADDR)
#define DMAC_CMCONFIG_4_ADDR       (DMAC_BASE_ADDR + DMAC_CMCONFIG_4_OFFSET_ADDR)
#define DMAC_CMCONFIG_5_ADDR       (DMAC_BASE_ADDR + DMAC_CMCONFIG_5_OFFSET_ADDR)
#define DMAC_CMCONFIG_6_ADDR       (DMAC_BASE_ADDR + DMAC_CMCONFIG_6_OFFSET_ADDR)
#define DMAC_CMCONFIG_7_ADDR       (DMAC_BASE_ADDR + DMAC_CMCONFIG_7_OFFSET_ADDR)
#define DMAC_CMCONFIG_8_ADDR       (DMAC_BASE_ADDR + DMAC_CMCONFIG_8_OFFSET_ADDR)
#define DMAC_CMCONFIG_9_ADDR       (DMAC_BASE_ADDR + DMAC_CMCONFIG_9_OFFSET_ADDR)
#define DMAC_CMCONFIG_10_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONFIG_10_OFFSET_ADDR)
#define DMAC_CMCONFIG_11_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONFIG_11_OFFSET_ADDR)
#define DMAC_CMCONFIG_12_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONFIG_12_OFFSET_ADDR)
#define DMAC_CMCONFIG_13_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONFIG_13_OFFSET_ADDR)
#define DMAC_CMCONFIG_14_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONFIG_14_OFFSET_ADDR)
#define DMAC_CMCONFIG_15_ADDR      (DMAC_BASE_ADDR + DMAC_CMCONFIG_15_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_0_ADDR   (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_0_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_1_ADDR   (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_1_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_2_ADDR   (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_2_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_3_ADDR   (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_3_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_4_ADDR   (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_4_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_5_ADDR   (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_5_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_6_ADDR   (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_6_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_7_ADDR   (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_7_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_8_ADDR   (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_8_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_9_ADDR   (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_9_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_10_ADDR  (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_10_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_11_ADDR  (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_11_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_12_ADDR  (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_12_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_13_ADDR  (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_13_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_14_ADDR  (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_14_OFFSET_ADDR)
#define DMAC_CMSRCADDR_H2_15_ADDR  (DMAC_BASE_ADDR + DMAC_CMSRCADDR_H2_15_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_0_ADDR  (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_0_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_1_ADDR  (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_1_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_2_ADDR  (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_2_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_3_ADDR  (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_3_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_4_ADDR  (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_4_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_5_ADDR  (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_5_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_6_ADDR  (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_6_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_7_ADDR  (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_7_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_8_ADDR  (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_8_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_9_ADDR  (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_9_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_10_ADDR (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_10_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_11_ADDR (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_11_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_12_ADDR (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_12_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_13_ADDR (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_13_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_14_ADDR (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_14_OFFSET_ADDR)
#define DMAC_CMDESTADDR_H2_15_ADDR (DMAC_BASE_ADDR + DMAC_CMDESTADDR_H2_15_OFFSET_ADDR)

#endif /* __DMAC_REGS_H__ */