/*
 * Copyright (c) Hisilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
 * UniProton is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 * 	http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * See the Mulan PSL v2 for more details.
 */
#ifndef __SPI_ADDR_DEFINE_H__
#define __SPI_ADDR_DEFINE_H__

#define SPI0_BASE_ADDR 0x8713000
#define SPI1_BASE_ADDR 0x8715000

#define SPI_CTRLR0_OFFSET_ADDR 0x0
#define SPI_CTRLR1_OFFSET_ADDR 0x4
#define SPI_SSIENR_OFFSET_ADDR 0x8
#define SPI_MWCR_OFFSET_ADDR 0xC
#define SPI_SER_OFFSET_ADDR 0x10
#define SPI_BAUDR_OFFSET_ADDR 0x14
#define SPI_TXFTLR_OFFSET_ADDR 0x18
#define SPI_RXFTLR_OFFSET_ADDR 0x1C
#define SPI_TXFLR_OFFSET_ADDR 0x20
#define SPI_RXFLR_OFFSET_ADDR 0x24
#define SPI_SR_OFFSET_ADDR 0x28
#define SPI_IMR_OFFSET_ADDR 0x2C
#define SPI_ISR_OFFSET_ADDR 0x30
#define SPI_SISR_OFFSET_ADDR 0x34
#define SPI_TXOICR_OFFSET_ADDR 0x38
#define SPI_RXOICR_OFFSET_ADDR 0x3C
#define SPI_RXUICR_OFFSET_ADDR 0x40
#define SPI_MSTICR_OFFSET_ADDR 0x44
#define SPI_ICR_OFFSET_ADDR 0x48
#define SPI_DMACR_OFFSET_ADDR 0x4C
#define SPI_DMATDLR_OFFSET_ADDR 0x50
#define SPI_DMARDLR_OFFSET_ADDR 0x54
#define SPI_IDR_OFFSET_ADDR 0x58
#define SPI_DR0_OFFSET_ADDR 0x60
#define SPI_DR1_OFFSET_ADDR 0x64
#define SPI_DR2_OFFSET_ADDR 0x68
#define SPI_DR3_OFFSET_ADDR 0x6C
#define SPI_DR4_OFFSET_ADDR 0x70
#define SPI_DR5_OFFSET_ADDR 0x74
#define SPI_DR6_OFFSET_ADDR 0x78
#define SPI_DR7_OFFSET_ADDR 0x7C
#define SPI_DR8_OFFSET_ADDR 0x80
#define SPI_DR9_OFFSET_ADDR 0x84
#define SPI_DR10_OFFSET_ADDR 0x88
#define SPI_DR11_OFFSET_ADDR 0x8C
#define SPI_DR12_OFFSET_ADDR 0x90
#define SPI_DR13_OFFSET_ADDR 0x94
#define SPI_DR14_OFFSET_ADDR 0x98
#define SPI_DR15_OFFSET_ADDR 0x9C

#endif
