ccflags-y += -I$(SDK_ROOT)/include/ -I$(SDK_ROOT)/include/register -I$(SDK_ROOT)/include/usr_api -I$(SDK_ROOT)/comm -I$(SRC_DIR)/non_real_time/include -I/${SECUREC_PATH}/include
ccflags-y += -DSDK_VER=\"$(SDK_VERSION)\" -D_FORTIFY_SOURCE=2
ccflags-y += -fstack-protector-strong -Wl,-z,relro -z,now -Wl,-z,noexecstack -Wformat=2 -Wfloat-equal -Werror -Wno-error=type-limits
ccflags-y += -funsigned-char -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -std=gnu11 -fno-common